# Install packages

In [ ]:
!pip3 install ffmpeg-python deepspeed

Requirement already satisfied: ffmpeg-python in /usr/local/lib/python3.11/dist-packages (0.2.0)
Requirement already satisfied: deepspeed in /usr/local/lib/python3.11/dist-packages (0.16.7)
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from ffmpeg-python) (1.0.0)
Requirement already satisfied: einops in /usr/local/lib/python3.11/dist-packages (from deepspeed) (0.8.1)
Requirement already satisfied: hjson in /usr/local/lib/python3.11/dist-packages (from deepspeed) (3.1.0)
Requirement already satisfied: msgpack in /usr/local/lib/python3.11/dist-packages (from deepspeed) (1.1.0)
Requirement already satisfied: ninja in /usr/local/lib/python3.11/dist-packages (from deepspeed) (1.11.1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from deepspeed) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from deepspeed) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from deepspeed) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from deepspeed) (9.0.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from deepspeed) (2.11.4)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from deepspeed) (2.6.0+cu124)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from deepspeed) (4.67.1)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.11/dist-packages (from deepspeed) (12.575.51)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (0.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (3.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (2.8.8)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->deepspeed) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->deepspeed) (3.0.2)

# Import libraries

In [ ]:
from google.colab import runtime
runtime.unassign()

In [ ]:
import os
import shutil
import ffmpeg
import tarfile
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

# Dataset Preparation

In [ ]:
import pandas as pd
df = pd.read_excel('/content/gdrive/MyDrive/85cleaned_file.xlsx')
# df1 = pd.read_csv('/content/gdrive/MyDrive/finetuning_dataset/audio_text_youssef.csv')
# df2 = pd.read_csv('/content/gdrive/MyDrive/finetuning_dataset/audio_text_amir.csv')

# df = pd.concat([df1, df2])

In [ ]:
# df = df[df['is_remove'] == 0]
df

,Chunk Name,Start Time (ms),End Time (ms),Duration (s),Chunk Path,Transcript,Word Count,Words Per Second,Is_Music,Detected_Emotions,Is_Denoised,phonemes,transcript_with_emotions,PlayAudio,Unnamed: 14,Unnamed: 15
0,audio001-chunk0.wav,0,13124,13.124,dataset\audio001-chunk0.wav,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...,30,2.285888,False,NaN,0,knɪŋ gʊ ənə ɪ b n tæ ɪlɪʃɪ dɪnm təwəðiaɪ fɪʃ ...,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...,▶ Play,NaN,NaN
1,audio001-chunk1.wav,13757,36498,22.741,dataset\audio001-chunk1.wav,عامه يقرا كتاب يحس روحه باللي را ناجح انت غير ...,31,1.363177,False,"{'Laughter': {'confidence': 0.142, 'start_time...",0,khɪ kənə k tə jihəsəhə b lɪhnɛʃ təɪ kəni tə k...,عامه يقرا كتاب <Laughter> يحس روحه باللي را نا...,▶ Play,باللي را ناجح انت غير قيت كتا,NaN
2,audio001-chunk2.wav,37027,42197,5.170,dataset\audio001-chunk2.wav,في حياتهم يا اما فر يا اماي,7,1.353965,False,NaN,0,jɛ ɛməðeɪɑhaɪ ə ʧivɝz jɛ ɛməðeɪɑɹəloʊ dɛɹ ən d...,في حياتهم يا اما فر يا اماي,▶ Play,NaN,NaN
3,audio001-chunk3.wav,42386,47554,5.168,dataset\audio001-chunk3.wav,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك,9,1.741486,False,NaN,0,hʊ ziumə gə dəwhɑɾɑnioʊ ʃɪv t kʊm zuʃ b niɛ də...,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك,▶ Play,NaN,NaN
4,audio001-chunk4.wav,47828,51925,4.097,dataset\audio001-chunk4.wav,تعرفت عليهم هنا في دباي ومن مدينتي من,8,1.952648,False,NaN,0,ə gʊsənɑ dɑh k tɾəf tɛɾioʊmhənəfɪ du baɪ wumɪm...,تعرفت عليهم هنا في دباي ومن مدينتي من,▶ Play,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8156,audio022-chunk339.wav,2320814,2326703,5.889,dataset\audio022-chunk339.wav,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...,17,2.886738,False,NaN,0,kɪ tfɑʃɪ kənæɑ tɑ k wɪʃ t əhɪ dɪɪ sθɪnəhə deɪ...,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...,▶ Play,NaN,NaN
8157,audio022-chunk340.wav,2326832,2330809,3.977,dataset\audio022-chunk340.wav,كييقوللك اوكي طاك واش ندير بابليش,6,1.508675,False,NaN,0,ki oʊlɪ k oʊ keɪtɑ k wuʃn dɪɾoʊ bɑ b leɪ,كييقوللك اوكي طاك واش ندير بابليش,▶ Play,NaN,NaN
8158,audio022-chunk341.wav,2331038,2334331,3.293,dataset\audio022-chunk341.wav,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك,9,2.733070,False,NaN,0,ʃ k li k ɛɾəhə di mən bæ dɪ təhɑɹ ʤlɪ k lə pɪ ...,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك,▶ Play,NaN,NaN
8159,audio022-chunk342.wav,2334605,2354064,19.459,dataset\audio022-chunk342.wav,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...,50,2.569505,False,NaN,0,hnæɑ wɛʃ daʊ hnɛf diɪvɪɾi ɪ tɪ b lɪ bɪi jɛni...,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...,▶ Play,NaN,NaN
8160,audio022-chunk343.wav,2354158,2377394,23.236,dataset\audio022-chunk343.wav,تكون فخور بهم ان شاء الله ما كناش بزاف تقال عل...,67,2.883457,False,"{'Sigh': {'confidence': 0.361, 'start_time': 0...",0,mɪhʃələmə kənəʃ b zɛf kəɛɾə kəɪ p kəm haɪvə k...,<Sigh> تكون فخور بهم ان شاء الله ما كناش بزاف ...,▶ Play,NaN,NaN

## Remove audios

In [ ]:
# audios_path = '/content/gdrive/MyDrive/finetuning_dataset/dataset/audios'
# audios = os.listdir(audios_path)

# for audio in audios:
#   current_audio_path = os.path.join(audios_path, audio)
#   os.remove(current_audio_path)

## Copy audios to another folder

In [ ]:

# os.makedirs('/content/gdrive/MyDrive/finetuning_dataset/dataset/wavs', exist_ok=True)

# source_path = '/content/gdrive/MyDrive/finetuning_dataset/dataset/splitted_audios'
# distination_path = '/content/gdrive/MyDrive/finetuning_dataset/dataset/wavs'

# audios = df['filename'].tolist()
# for audio in audios:
#   if audio.endswith('.wav'):
#     current_audio_path = os.path.join(source_path, audio)
#     new_audio_path = os.path.join(distination_path, audio)
#     shutil.copy2(current_audio_path, new_audio_path)

In [ ]:
df.drop(columns=['is_remove', 'duration'], axis=1, inplace=True)

In [ ]:
df['filename'] = df['filename'].apply(lambda x: x.replace('.wav', ''))
# df['text'] = df['text'].apply(lambda x: str(x)+'|')
# df['normalized_text'] = df['normalized_text'].apply(lambda x: str(x)+'|')

In [ ]:
import os
import pandas as pd


# Create the new DataFrame with required columns
df2 = pd.DataFrame({
    "filename": df["Chunk Name"],
    "text": df["Transcript"],
    "normalized_text": df["Transcript"]  # Just copying for now
})

In [ ]:
df2.to_csv('/content/gdrive/MyDrive/dataset22050/metadata.csv', encoding='utf-8-sig', index=False, header=False, sep='|',)

In [ ]:
df2

,filename,text,normalized_text
0,audio001-chunk0.wav,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...
1,audio001-chunk1.wav,عامه يقرا كتاب يحس روحه باللي را ناجح انت غير ...,عامه يقرا كتاب يحس روحه باللي را ناجح انت غير ...
2,audio001-chunk2.wav,في حياتهم يا اما فر يا اماي,في حياتهم يا اما فر يا اماي
3,audio001-chunk3.wav,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك
4,audio001-chunk4.wav,تعرفت عليهم هنا في دباي ومن مدينتي من,تعرفت عليهم هنا في دباي ومن مدينتي من
...,...,...,...
8156,audio022-chunk339.wav,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...
8157,audio022-chunk340.wav,كييقوللك اوكي طاك واش ندير بابليش,كييقوللك اوكي طاك واش ندير بابليش
8158,audio022-chunk341.wav,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك
8159,audio022-chunk342.wav,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...
8160,audio022-chunk343.wav,تكون فخور بهم ان شاء الله ما كناش بزاف تقال عل...,تكون فخور بهم ان شاء الله ما كناش بزاف تقال عل...

In [ ]:
metadata_path = os.path.join('/content/gdrive/MyDrive/dataset22050', "metadata.csv")
with open(metadata_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
      if i > 5:
        break
      cols = line.strip().split("|")
      if len(cols) < 3:  # Check if there are fewer than 3 columns
          print(f"Error on line {i}: {line}")
      else:
          print(f"Line {i} is valid: {cols[2]}")

Line 1 is valid: خليني نقول انا ابن عائله جدا متواضعه طيب وين تقدر تقول همي الوحيد كان نخدم كنت نبيع قصبر كبيع بورسات نخدم باش نجاوب على الغلطه اللي يطيح فيها الجزائري بصفه
Line 2 is valid: عامه يقرا كتاب يحس روحه باللي را ناجح انت غير قيت كتا كيتفرج كيتفرج على اندر اندر ناجح تتفرج على واح ناجح ما تنج بالعكس تلا واحدي دوها عندهم ترا في
Line 3 is valid: في حياتهم يا اما فر يا اماي
Line 4 is valid: اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك
Line 5 is valid: تعرفت عليهم هنا في دباي ومن مدينتي من

In [ ]:
len(os.listdir('/content/gdrive/MyDrive/dataset'))

8191

## Change audio sample rate

In [ ]:
import time

def convert_sample_rate(audios_path, output_path, target_sample_rate):
  os.makedirs(output_path, exist_ok=True)
  audios = os.listdir(audios_path)
  start = time.time()
  for i, audio in enumerate(audios):
    if i % 100 == 0:
      current = time.time()
      print(f'Time take to process {i} audios: {current-start:.1f} seconds')
    audio_path = os.path.join(audios_path, audio)
    audio_output_path = os.path.join(output_path, audio)
    try:
      ffmpeg.input(audio_path).output(audio_output_path, ar=target_sample_rate).run(capture_stdout=True, capture_stderr=True) # .overwrite_output()
      print(f'Converted audio {i}')
      print(f"Successfully converted {audio_path} to {target_sample_rate} Hz")
    except ffmpeg.Error as e:
      print(f"Conversion failed. Error: {e.stderr.decode()}")


audios_path = '/content/gdrive/MyDrive/dataset'
output_path = '/content/gdrive/MyDrive/dataset22050'
target_sample_rate = 22050
convert_sample_rate(audios_path, output_path, target_sample_rate)

Streaming output truncated to the last 5000 lines.
Converted audio 5703
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk377.wav to 22050 Hz
Converted audio 5704
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk416.wav to 22050 Hz
Converted audio 5705
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk371.wav to 22050 Hz
Converted audio 5706
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk417.wav to 22050 Hz
Converted audio 5707
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk4.wav to 22050 Hz
Converted audio 5708
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk77.wav to 22050 Hz
Converted audio 5709
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk110.wav to 22050 Hz
Converted audio 5710
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk29.wav to 22050 Hz
Converted audio 5711
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk60.wav to 22050 Hz
Converted audio 5712
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk62.wav to 22050 Hz
Converted audio 5713
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk54.wav to 22050 Hz
Converted audio 5714
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk13.wav to 22050 Hz
Converted audio 5715
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk79.wav to 22050 Hz
Converted audio 5716
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk38.wav to 22050 Hz
Converted audio 5717
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk26.wav to 22050 Hz
Converted audio 5718
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk24.wav to 22050 Hz
Converted audio 5719
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk103.wav to 22050 Hz
Converted audio 5720
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk9.wav to 22050 Hz
Converted audio 5721
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk16.wav to 22050 Hz
Converted audio 5722
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk105.wav to 22050 Hz
Converted audio 5723
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk0.wav to 22050 Hz
Converted audio 5724
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk6.wav to 22050 Hz
Converted audio 5725
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk113.wav to 22050 Hz
Converted audio 5726
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk31.wav to 22050 Hz
Converted audio 5727
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk97.wav to 22050 Hz
Converted audio 5728
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk58.wav to 22050 Hz
Converted audio 5729
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk23.wav to 22050 Hz
Converted audio 5730
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk119.wav to 22050 Hz
Converted audio 5731
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk80.wav to 22050 Hz
Converted audio 5732
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk55.wav to 22050 Hz
Converted audio 5733
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk41.wav to 22050 Hz
Converted audio 5734
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk25.wav to 22050 Hz
Converted audio 5735
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk46.wav to 22050 Hz
Converted audio 5736
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk90.wav to 22050 Hz
Converted audio 5737
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk95.wav to 22050 Hz
Converted audio 5738
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk36.wav to 22050 Hz
Converted audio 5739
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk50.wav to 22050 Hz
Converted audio 5740
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk121.wav to 22050 Hz
Converted audio 5741
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk7.wav to 22050 Hz
Converted audio 5742
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk47.wav to 22050 Hz
Converted audio 5743
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk37.wav to 22050 Hz
Converted audio 5744
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk98.wav to 22050 Hz
Converted audio 5745
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk73.wav to 22050 Hz
Converted audio 5746
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk72.wav to 22050 Hz
Converted audio 5747
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk35.wav to 22050 Hz
Converted audio 5748
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk81.wav to 22050 Hz
Converted audio 5749
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk78.wav to 22050 Hz
Converted audio 5750
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk65.wav to 22050 Hz
Converted audio 5751
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk85.wav to 22050 Hz
Converted audio 5752
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk45.wav to 22050 Hz
Converted audio 5753
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk39.wav to 22050 Hz
Converted audio 5754
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk83.wav to 22050 Hz
Converted audio 5755
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk34.wav to 22050 Hz
Converted audio 5756
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk107.wav to 22050 Hz
Converted audio 5757
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk53.wav to 22050 Hz
Converted audio 5758
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk70.wav to 22050 Hz
Converted audio 5759
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk118.wav to 22050 Hz
Converted audio 5760
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk84.wav to 22050 Hz
Converted audio 5761
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk15.wav to 22050 Hz
Converted audio 5762
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk116.wav to 22050 Hz
Converted audio 5763
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk76.wav to 22050 Hz
Converted audio 5764
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk56.wav to 22050 Hz
Converted audio 5765
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk19.wav to 22050 Hz
Converted audio 5766
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk44.wav to 22050 Hz
Converted audio 5767
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk11.wav to 22050 Hz
Converted audio 5768
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk33.wav to 22050 Hz
Converted audio 5769
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk100.wav to 22050 Hz
Converted audio 5770
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk112.wav to 22050 Hz
Converted audio 5771
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk86.wav to 22050 Hz
Converted audio 5772
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk102.wav to 22050 Hz
Converted audio 5773
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk3.wav to 22050 Hz
Converted audio 5774
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk66.wav to 22050 Hz
Converted audio 5775
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk5.wav to 22050 Hz
Converted audio 5776
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk120.wav to 22050 Hz
Converted audio 5777
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk91.wav to 22050 Hz
Converted audio 5778
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk114.wav to 22050 Hz
Converted audio 5779
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk63.wav to 22050 Hz
Converted audio 5780
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk88.wav to 22050 Hz
Converted audio 5781
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk1.wav to 22050 Hz
Converted audio 5782
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk67.wav to 22050 Hz
Converted audio 5783
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk32.wav to 22050 Hz
Converted audio 5784
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk64.wav to 22050 Hz
Converted audio 5785
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk96.wav to 22050 Hz
Converted audio 5786
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk82.wav to 22050 Hz
Converted audio 5787
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk2.wav to 22050 Hz
Converted audio 5788
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk57.wav to 22050 Hz
Converted audio 5789
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk48.wav to 22050 Hz
Converted audio 5790
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk8.wav to 22050 Hz
Converted audio 5791
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk42.wav to 22050 Hz
Converted audio 5792
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk93.wav to 22050 Hz
Converted audio 5793
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk30.wav to 22050 Hz
Converted audio 5794
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk104.wav to 22050 Hz
Converted audio 5795
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk94.wav to 22050 Hz
Converted audio 5796
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk108.wav to 22050 Hz
Converted audio 5797
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk14.wav to 22050 Hz
Converted audio 5798
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk52.wav to 22050 Hz
Converted audio 5799
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk22.wav to 22050 Hz
Time take to process 5800 audios: 1628.2 seconds
Converted audio 5800
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk20.wav to 22050 Hz
Converted audio 5801
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk10.wav to 22050 Hz
Converted audio 5802
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk106.wav to 22050 Hz
Converted audio 5803
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk17.wav to 22050 Hz
Converted audio 5804
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk115.wav to 22050 Hz
Converted audio 5805
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk117.wav to 22050 Hz
Converted audio 5806
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk21.wav to 22050 Hz
Converted audio 5807
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk27.wav to 22050 Hz
Converted audio 5808
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk49.wav to 22050 Hz
Converted audio 5809
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk51.wav to 22050 Hz
Converted audio 5810
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk71.wav to 22050 Hz
Converted audio 5811
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk74.wav to 22050 Hz
Converted audio 5812
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk61.wav to 22050 Hz
Converted audio 5813
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk111.wav to 22050 Hz
Converted audio 5814
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk101.wav to 22050 Hz
Converted audio 5815
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk43.wav to 22050 Hz
Converted audio 5816
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk18.wav to 22050 Hz
Converted audio 5817
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk109.wav to 22050 Hz
Converted audio 5818
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk28.wav to 22050 Hz
Converted audio 5819
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk69.wav to 22050 Hz
Converted audio 5820
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk92.wav to 22050 Hz
Converted audio 5821
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk59.wav to 22050 Hz
Converted audio 5822
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk12.wav to 22050 Hz
Converted audio 5823
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk89.wav to 22050 Hz
Converted audio 5824
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk75.wav to 22050 Hz
Converted audio 5825
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk40.wav to 22050 Hz
Converted audio 5826
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk87.wav to 22050 Hz
Converted audio 5827
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk122.wav to 22050 Hz
Converted audio 5828
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk68.wav to 22050 Hz
Converted audio 5829
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk99.wav to 22050 Hz
Converted audio 5830
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk126.wav to 22050 Hz
Converted audio 5831
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk160.wav to 22050 Hz
Converted audio 5832
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk140.wav to 22050 Hz
Converted audio 5833
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk150.wav to 22050 Hz
Converted audio 5834
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk123.wav to 22050 Hz
Converted audio 5835
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk149.wav to 22050 Hz
Converted audio 5836
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk156.wav to 22050 Hz
Converted audio 5837
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk129.wav to 22050 Hz
Converted audio 5838
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk131.wav to 22050 Hz
Converted audio 5839
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk139.wav to 22050 Hz
Converted audio 5840
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk124.wav to 22050 Hz
Converted audio 5841
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk125.wav to 22050 Hz
Converted audio 5842
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk144.wav to 22050 Hz
Converted audio 5843
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk127.wav to 22050 Hz
Converted audio 5844
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk137.wav to 22050 Hz
Converted audio 5845
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk159.wav to 22050 Hz
Converted audio 5846
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk138.wav to 22050 Hz
Converted audio 5847
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk141.wav to 22050 Hz
Converted audio 5848
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk151.wav to 22050 Hz
Converted audio 5849
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk143.wav to 22050 Hz
Converted audio 5850
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk135.wav to 22050 Hz
Converted audio 5851
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk157.wav to 22050 Hz
Converted audio 5852
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk154.wav to 22050 Hz
Converted audio 5853
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk158.wav to 22050 Hz
Converted audio 5854
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk136.wav to 22050 Hz
Converted audio 5855
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk142.wav to 22050 Hz
Converted audio 5856
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk146.wav to 22050 Hz
Converted audio 5857
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk155.wav to 22050 Hz
Converted audio 5858
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk161.wav to 22050 Hz
Converted audio 5859
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk145.wav to 22050 Hz
Converted audio 5860
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk147.wav to 22050 Hz
Converted audio 5861
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk148.wav to 22050 Hz
Converted audio 5862
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk128.wav to 22050 Hz
Converted audio 5863
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk152.wav to 22050 Hz
Converted audio 5864
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk133.wav to 22050 Hz
Converted audio 5865
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk132.wav to 22050 Hz
Converted audio 5866
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk134.wav to 22050 Hz
Converted audio 5867
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk130.wav to 22050 Hz
Converted audio 5868
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk153.wav to 22050 Hz
Converted audio 5869
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk2.wav to 22050 Hz
Converted audio 5870
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk24.wav to 22050 Hz
Converted audio 5871
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk26.wav to 22050 Hz
Converted audio 5872
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk16.wav to 22050 Hz
Converted audio 5873
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk0.wav to 22050 Hz
Converted audio 5874
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk11.wav to 22050 Hz
Converted audio 5875
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk25.wav to 22050 Hz
Converted audio 5876
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk19.wav to 22050 Hz
Converted audio 5877
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk6.wav to 22050 Hz
Converted audio 5878
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk4.wav to 22050 Hz
Converted audio 5879
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk17.wav to 22050 Hz
Converted audio 5880
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk15.wav to 22050 Hz
Converted audio 5881
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk21.wav to 22050 Hz
Converted audio 5882
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk9.wav to 22050 Hz
Converted audio 5883
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk8.wav to 22050 Hz
Converted audio 5884
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk23.wav to 22050 Hz

# FINE-TUNING XTTS-v2 #

In [ ]:
!pip install git+https://github.com/coqui-ai/TTS

Collecting git+https://github.com/coqui-ai/TTS
  Cloning https://github.com/coqui-ai/TTS to /tmp/pip-req-build-cl03d4_i
  Running command git clone --filter=blob:none --quiet https://github.com/coqui-ai/TTS /tmp/pip-req-build-cl03d4_i
  Resolved https://github.com/coqui-ai/TTS to commit dbf1a08a0d4e47fdad6172e433eeb34bc6b13b4e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.26.4)
Requirement already satisfied: cython>=0.29.30 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.0.12)
Requirement already satisfied: scipy>=1.11.2 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.15.3)
Requirement already satisfied: torch>=2.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (2.6.0+cu124)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (2.6.0+cu124)
Requirement already satisfied: soundfile>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.13.1)
Requirement already satisfied: librosa>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.11.0)
Requirement already satisfied: scikit-learn>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.6.1)
Requirement already satisfied: numba>=0.57.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.60.0)
Requirement already satisfied: inflect>=5.6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (7.5.0)
Requirement already satisfied: tqdm>=4.64.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (4.67.1)
Requirement already satisfied: anyascii>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.3.2)
Requirement already satisfied: pyyaml>=6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (6.0.2)
Requirement already satisfied: fsspec>=2023.6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (2025.3.2)
Requirement already satisfied: aiohttp>=3.8.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.11.15)
Requirement already satisfied: packaging>=23.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (24.2)
Requirement already satisfied: mutagen==1.47.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.47.0)
Requirement already satisfied: flask>=2.0.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.1.1)
Requirement already satisfied: pysbd>=0.3.4 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.3.4)
Requirement already satisfied: umap-learn>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.5.7)
Requirement already satisfied: pandas<2.0,>=1.4 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.5.3)
Requirement already satisfied: matplotlib>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.10.0)
Requirement already satisfied: trainer>=0.0.36 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.0.36)
Requirement already satisfied: coqpit>=0.0.16 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.0.17)
Requirement already satisfied: jieba in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.42.1)
Requirement already satisfied: pypinyin in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.54.0)
Requirement already satisfied: hangul_romanize in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.1.0)
Requirement already satisfied: gruut==2.2.3 in /usr/local/lib/python3.11/dist-packages (from gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.2.3)
Requirement already satisfied: jamo in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.4.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.9.1)
Requirement already satisfied: g2pkk>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.1.2)
Requirement already satisfied: bangla in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.0.5)
Requirement already satisfied: bnnumerizer in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.0.2)
Requirement already satisfied: bnunicodenormalizer in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.1.7)
Requirement already satisfied: einops>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.8.1)
Requirement already satisfied: transformers>=4.33.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (4.37.1)
Requirement already satisfied: encodec>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.1.1)
Requirement already satisfied: unidecode>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.4.0)
Requirement already satisfied: num2words in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.5.14)
Requirement already satisfied: spacy>=3 in /usr/local/lib/python3.11/dist-packages (from spacy[ja]>=3->TTS==0.22.0) (3.8.5)
Requirement already satisfied: Babel<3.0.0,>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.17.0)
Requirement already satisfied: dateparser~=1.1.0 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (1.1.8)
Requirement already satisfied: gruut-ipa<1.0,>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (0.13.0)
Requirement already satisfied: gruut-lang-en~=2.0.0 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.0.1)
Requirement already satisfied: jsonlines~=1.2.0 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (1.2.0)
Requirement already satisfied: networkx<3.0.0,>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.8.8)
Requirement already satisfied: python-crfsuite~=0.9.7 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (0.9.11)
Requirement already satisfied: gruut-lang-de~=2.0.0 in /usr/local/lib/python3.11/dist-packages (from gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.0.1)
Requirement already satisfied: gruut-lang-es~=2.0.0 in /usr/local/lib/python3.11/dist-packages (from gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.0.1)
Requirement already satisfied: gruut-lang-fr~=2.0.0 in /usr/local/lib/python3.11/dist-packages (from gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (1.20.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (8.2.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (3.1.3)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.11/dist-packages (from inflect>=5.6.0->TTS==0.22.0) (10.7.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from inflect>=5.6.0->TTS==0.22.0) (4.4.2)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (3.0.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (1.5.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (0.5.0.post1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (4.13.2)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (1.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (2.9.0.post0)
Requirement already satisfied: docopt>=0.6.2 in /usr/local/lib/python3.11/dist-packages (from num2words->TTS==0.22.0) (0.6.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.57.0->TTS==0.22.0) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.0,>=1.4->TTS==0.22.0) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.0->TTS==0.22.0) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.11/dist-packages (from soundfile>=0.12.0->TTS==0.22.0) (1.17.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.15.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.11.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (75.2.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.5.0)
Requirement already satisfied: sudachipy!=0.6.1,>=0.5.2 in /usr/local/lib/python3.11/dist-packages (from spacy[ja]>=3->TTS==0.22.0) (0.6.10)
Requirement already satisfied: sudachidict_core>=20211220 in /usr/local/lib/python3.11/dist-packages (from spacy[ja]>=3->TTS==0.22.0) (20250129)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (3.18.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.1->TTS==0.22.0) (1.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from trainer>=0.0.36->TTS==0.22.0) (5.9.5)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.11/dist-packages (from trainer>=0.0.36->TTS==0.22.0) (2.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (0.31.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (0.15.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (0.5.3)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.1->TTS==0.22.0) (0.5.13)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0->soundfile>=0.12.0->TTS==0.22.0) (2.22)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.11/dist-packages (from dateparser~=1.1.0->gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (5.3.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from jsonlines~=1.2.0->gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (1.17.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.3.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pooch>=1.1->librosa>=0.10.0->TTS==0.22.0) (4.3.8)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2025.4.26)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.2.1)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.1.5)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.5.4)

In [ ]:
!pip install transformers==4.37.1

Requirement already satisfied: transformers==4.37.1 in /usr/local/lib/python3.11/dist-packages (4.37.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (0.31.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (2.32.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (0.15.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.37.1) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.37.1) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (2025.4.26)

In [ ]:
###updated training zone####

In [ ]:
from trainer import Trainer, TrainerArgs
#from trainer.logging.wandb_logger import WandbLogger
from TTS.tts.configs.shared_configs import BaseDatasetConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.layers.xtts.trainer.gpt_trainer import GPTArgs, GPTTrainer, GPTTrainerConfig, XttsAudioConfig
from TTS.utils.manage import ModelManager

import sys
import os
import wandb

### Monkey Patching for wandb

In [ ]:
from trainer.logging.wandb_logger import WandbLogger

In [ ]:
def add_artifact(self, file_or_dir, name, artifact_type, aliases=None):
    ###instead of adding artifact, do nothing###
    print(f"========Ignoring artifact: {name} {file_or_dir}========")
    return


WandbLogger.add_artifact = add_artifact

In [ ]:
# Logging parameters
RUN_NAME = "finetuned_egtts_v2"
PROJECT_NAME = "dz_ar_model"
DASHBOARD_LOGGER = "wandb"
LOGGER_URI = None

### Dir for Training Run

In [ ]:
OUT_PATH = '/content/gdrive/MyDrive/models'
os.makedirs(OUT_PATH, exist_ok=True)

Retreive the base model files.

In [ ]:
# Define the path where XTTS v2.0.1 files will be downloaded
CHECKPOINTS_OUT_PATH = os.path.join(OUT_PATH, "EGTTS_v2.0_original_model_files/")
os.makedirs(CHECKPOINTS_OUT_PATH, exist_ok=True)

# DVAE files
DVAE_CHECKPOINT_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/dvae.pth"
MEL_NORM_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/mel_stats.pth"

# Set the path to the downloaded files
DVAE_CHECKPOINT = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(DVAE_CHECKPOINT_LINK))
MEL_NORM_FILE = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(MEL_NORM_LINK))

# download DVAE files if needed
if not os.path.isfile(DVAE_CHECKPOINT) or not os.path.isfile(MEL_NORM_FILE):
    print(" > Downloading DVAE files!")
    ModelManager._download_model_files([MEL_NORM_LINK, DVAE_CHECKPOINT_LINK], CHECKPOINTS_OUT_PATH, progress_bar=True)

# Download XTTS v2.0 checkpoint if needed
TOKENIZER_FILE_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/vocab.json"
XTTS_CHECKPOINT_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/model.pth"

# XTTS transfer learning parameters: You we need to provide the paths of XTTS model checkpoint that you want to do the fine tuning.
TOKENIZER_FILE = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(TOKENIZER_FILE_LINK))  # vocab.json file
XTTS_CHECKPOINT = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(XTTS_CHECKPOINT_LINK))  # model.pth file

# download XTTS v2.0 files if needed
if not os.path.isfile(TOKENIZER_FILE) or not os.path.isfile(XTTS_CHECKPOINT):
    print(" > Downloading XTTS v2.0 files!")
    ModelManager._download_model_files(
        [TOKENIZER_FILE_LINK, XTTS_CHECKPOINT_LINK], CHECKPOINTS_OUT_PATH, progress_bar=True
    )

 > Downloading DVAE files!

  0%|          | 0.00/1.07k [00:00<?, ?iB/s]
100%|██████████| 1.07k/1.07k [00:00<00:00, 3.50kiB/s]

  1%|          | 1.60M/211M [00:00<00:13, 16.0MiB/s]
  4%|▍         | 8.33M/211M [00:00<00:04, 46.1MiB/s]
  8%|▊         | 16.3M/211M [00:00<00:03, 61.5MiB/s]
 11%|█         | 23.3M/211M [00:00<00:02, 64.8MiB/s]
 15%|█▍        | 31.1M/211M [00:00<00:02, 69.6MiB/s]
 18%|█▊        | 38.9M/211M [00:00<00:02, 72.2MiB/s]
 22%|██▏       | 47.1M/211M [00:00<00:02, 75.6MiB/s]
 26%|██▌       | 54.9M/211M [00:00<00:02, 76.1MiB/s]
 30%|██▉       | 62.9M/211M [00:00<00:01, 77.3MiB/s]
 34%|███▎      | 70.7M/211M [00:01<00:01, 77.8MiB/s]
 37%|███▋      | 78.7M/211M [00:01<00:01, 78.3MiB/s]
 41%|████      | 86.6M/211M [00:01<00:01, 78.6MiB/s]
 45%|████▍     | 94.6M/211M [00:01<00:01, 79.0MiB/s]
 49%|████▊     | 103M/211M [00:01<00:01, 76.7MiB/s]
 52%|█████▏    | 110M/211M [00:01<00:01, 77.0MiB/s]
 56%|█████▌    | 118M/211M [00:01<00:01, 69.4MiB/s]
 60%|█████▉    | 126M/211M [00:01<00:01, 71.3MiB/s]
 63%|██████▎   | 133M/211M [00:01<00:01, 72.1MiB/s]
 67%|██████▋   | 141M/211M [00:01<00:00, 73.2MiB/s]
 70%|███████   | 148M/211M [00:02<00:00, 74.4MiB/s]
 74%|███████▍  | 156M/211M [00:02<00:00, 74.3MiB/s]
 78%|███████▊  | 163M/211M [00:02<00:00, 74.8MiB/s]
 81%|████████  | 171M/211M [00:02<00:00, 74.3MiB/s]
 85%|████████▍ | 178M/211M [00:02<00:00, 73.1MiB/s]
 88%|████████▊ | 186M/211M [00:02<00:00, 74.2MiB/s]
 92%|█████████▏| 194M/211M [00:02<00:00, 73.4MiB/s]
 96%|█████████▌| 202M/211M [00:02<00:00, 75.5MiB/s]
100%|█████████▉| 210M/211M [00:02<00:00, 76.8MiB/s]

 > Downloading XTTS v2.0 files!

100%|██████████| 211M/211M [00:03<00:00, 65.5MiB/s]
 62%|██████▏   | 222k/361k [00:00<00:00, 2.21MiB/s]
100%|██████████| 361k/361k [00:00<00:00, 811kiB/s]

  0%|          | 897k/1.87G [00:00<03:29, 8.90MiB/s]
  0%|          | 4.73M/1.87G [00:00<01:11, 26.1MiB/s]
  1%|          | 10.7M/1.87G [00:00<00:44, 41.4MiB/s]
  1%|          | 16.4M/1.87G [00:00<00:38, 47.6MiB/s]
  1%|          | 21.2M/1.87G [00:00<00:43, 42.6MiB/s]
  1%|▏         | 27.2M/1.87G [00:00<00:38, 48.2MiB/s]
  2%|▏         | 32.1M/1.87G [00:00<00:37, 48.4MiB/s]
  2%|▏         | 37.8M/1.87G [00:00<00:36, 50.8MiB/s]
  2%|▏         | 43.6M/1.87G [00:00<00:34, 53.0MiB/s]
  3%|▎         | 49.6M/1.87G [00:01<00:33, 55.0MiB/s]
  3%|▎         | 55.1M/1.87G [00:01<00:33, 54.5MiB/s]
  3%|▎         | 61.5M/1.87G [00:01<00:31, 57.4MiB/s]
  4%|▎         | 67.9M/1.87G [00:01<00:30, 59.2MiB/s]
  4%|▍         | 74.1M/1.87G [00:01<00:29, 60.0MiB/s]
  4%|▍         | 80.5M/1.87G [00:01<00:29, 61.4MiB/s]
  5%|▍         | 86.7M/1.87G [00:01<00:29, 60.2MiB/s]
  5%|▍         | 92.7M/1.87G [00:01<00:30, 57.4MiB/s]
  5%|▌         | 99.1M/1.87G [00:01<00:29, 59.2MiB/s]
  6%|▌         | 105M/1.87G [00:01<00:31, 56.7MiB/s]
  6%|▌         | 111M/1.87G [00:02<00:30, 57.9MiB/s]
  6%|▋         | 117M/1.87G [00:02<00:30, 57.9MiB/s]
  7%|▋         | 123M/1.87G [00:02<00:30, 57.2MiB/s]
  7%|▋         | 128M/1.87G [00:02<00:30, 57.1MiB/s]
  7%|▋         | 135M/1.87G [00:02<00:29, 59.0MiB/s]
  8%|▊         | 141M/1.87G [00:02<00:30, 57.0MiB/s]
  8%|▊         | 147M/1.87G [00:02<00:28, 59.7MiB/s]
  8%|▊         | 155M/1.87G [00:02<00:26, 64.4MiB/s]
  9%|▊         | 163M/1.87G [00:02<00:25, 68.0MiB/s]
  9%|▉         | 169M/1.87G [00:03<00:25, 67.3MiB/s]
  9%|▉         | 177M/1.87G [00:03<00:24, 70.3MiB/s]
 10%|▉         | 185M/1.87G [00:03<00:23, 71.6MiB/s]
 10%|█         | 192M/1.87G [00:03<00:23, 72.6MiB/s]
 11%|█         | 200M/1.87G [00:03<00:22, 72.7MiB/s]
 11%|█         | 207M/1.87G [00:03<00:25, 65.0MiB/s]
 12%|█▏        | 215M/1.87G [00:03<00:23, 69.1MiB/s]
 12%|█▏        | 223M/1.87G [00:03<00:22, 71.6MiB/s]
 12%|█▏        | 230M/1.87G [00:03<00:22, 73.6MiB/s]
 13%|█▎        | 238M/1.87G [00:03<00:21, 74.9MiB/s]
 13%|█▎        | 246M/1.87G [00:04<00:21, 74.3MiB/s]
 14%|█▎        | 253M/1.87G [00:04<00:21, 74.8MiB/s]
 14%|█▍        | 262M/1.87G [00:04<00:20, 76.6MiB/s]
 14%|█▍        | 269M/1.87G [00:04<00:20, 77.2MiB/s]
 15%|█▍        | 277M/1.87G [00:04<00:20, 78.2MiB/s]
 15%|█▌        | 285M/1.87G [00:04<00:20, 78.3MiB/s]
 16%|█▌        | 293M/1.87G [00:04<00:19, 79.2MiB/s]
 16%|█▌        | 301M/1.87G [00:04<00:19, 78.7MiB/s]
 17%|█▋        | 309M/1.87G [00:04<00:19, 79.0MiB/s]
 17%|█▋        | 317M/1.87G [00:04<00:21, 72.7MiB/s]
 17%|█▋        | 325M/1.87G [00:05<00:21, 70.6MiB/s]
 18%|█▊        | 333M/1.87G [00:05<00:20, 73.5MiB/s]
 18%|█▊        | 341M/1.87G [00:05<00:20, 75.9MiB/s]
 19%|█▊        | 349M/1.87G [00:05<00:20, 75.2MiB/s]
 19%|█▉        | 356M/1.87G [00:05<00:19, 75.8MiB/s]
 19%|█▉        | 364M/1.87G [00:05<00:19, 76.3MiB/s]
 20%|█▉        | 372M/1.87G [00:05<00:19, 76.6MiB/s]
 20%|██        | 380M/1.87G [00:05<00:19, 75.9MiB/s]
 21%|██        | 388M/1.87G [00:05<00:19, 77.6MiB/s]
 21%|██        | 396M/1.87G [00:05<00:18, 78.4MiB/s]
 22%|██▏       | 404M/1.87G [00:06<00:19, 76.7MiB/s]
 22%|██▏       | 411M/1.87G [00:06<00:19, 76.2MiB/s]
 22%|██▏       | 419M/1.87G [00:06<00:19, 75.9MiB/s]
 23%|██▎       | 427M/1.87G [00:06<00:39, 36.4MiB/s]
 23%|██▎       | 434M/1.87G [00:06<00:33, 42.4MiB/s]
 24%|██▎       | 441M/1.87G [00:06<00:29, 48.7MiB/s]
 24%|██▍       | 449M/1.87G [00:07<00:26, 54.0MiB/s]
 24%|██▍       | 455M/1.87G [00:07<00:24, 56.8MiB/s]
 25%|██▍       | 462M/1.87G [00:07<00:23, 59.3MiB/s]
 25%|██▌       | 470M/1.87G [00:07<00:22, 63.1MiB/s]
 26%|██▌       | 477M/1.87G [00:07<00:20, 66.3MiB/s]
 26%|██▌       | 485M/1.87G [00:07<00:20, 69.1MiB/s]
 26%|██▋       | 492M/1.87G [00:07<00:19, 71.1MiB/s]
 27%|██▋       | 500M/1.87G [00:07<00:18, 73.0MiB/s]
 27%|██▋       | 507M/1.87G [00:07<00:18, 73.5MiB/s]
 28%|██▊       | 516M/1.87G [00:07<00:17, 76.1MiB/s]
 28%|██▊       | 524M/1.87G [00:08<00:17, 77.5MiB/s]
 28%|██▊       | 532M/1.87G [00:08<00:17, 75.9MiB/s]
 29%|██▉       | 539M/1.87G [00:08<00:19, 67.4MiB/s]
 29%|██▉       | 546M/1.87G [00:08<00:21, 61.3MiB/s]
 30%|██▉       | 553M/1.87G [00:08<00:22, 57.2MiB/s]
 30%|██▉       | 558M/1.87G [00:08<00:23, 55.0MiB/s]
 30%|███       | 564M/1.87G [00:08<00:24, 52.7MiB/s]
 30%|███       | 569M/1.87G [00:08<00:26, 49.2MiB/s]
 31%|███       | 574M/1.87G [00:09<00:28, 46.1MiB/s]
 31%|███       | 579M/1.87G [00:09<00:30, 41.7MiB/s]
 31%|███       | 583M/1.87G [00:09<00:33, 38.5MiB/s]
 31%|███▏      | 587M/1.87G [00:09<00:33, 38.7MiB/s]
 32%|███▏      | 591M/1.87G [00:09<00:32, 38.9MiB/s]
 32%|███▏      | 595M/1.87G [00:09<00:32, 39.0MiB/s]
 32%|███▏      | 599M/1.87G [00:09<00:36, 34.8MiB/s]
 32%|███▏      | 603M/1.87G [00:09<00:36, 34.4MiB/s]
 32%|███▏      | 607M/1.87G [00:10<00:34, 36.6MiB/s]
 33%|███▎      | 614M/1.87G [00:10<00:26, 47.1MiB/s]
 33%|███▎      | 622M/1.87G [00:10<00:22, 54.2MiB/s]
 34%|███▎      | 628M/1.87G [00:10<00:21, 58.4MiB/s]
 34%|███▍      | 636M/1.87G [00:10<00:19, 63.8MiB/s]
 34%|███▍      | 644M/1.87G [00:10<00:18, 66.7MiB/s]
 35%|███▍      | 651M/1.87G [00:10<00:17, 69.9MiB/s]
 35%|███▌      | 659M/1.87G [00:10<00:16, 71.6MiB/s]
 36%|███▌      | 667M/1.87G [00:10<00:16, 73.6MiB/s]
 36%|███▌      | 675M/1.87G [00:10<00:15, 75.7MiB/s]
 37%|███▋      | 683M/1.87G [00:11<00:15, 77.2MiB/s]
 37%|███▋      | 691M/1.87G [00:11<00:15, 77.6MiB/s]
 37%|███▋      | 699M/1.87G [00:11<00:15, 77.9MiB/s]
 38%|███▊      | 706M/1.87G [00:11<00:14, 78.1MiB/s]
 38%|███▊      | 714M/1.87G [00:11<00:15, 76.8MiB/s]
 39%|███▊      | 722M/1.87G [00:11<00:14, 77.1MiB/s]
 39%|███▉      | 730M/1.87G [00:11<00:14, 77.9MiB/s]
 39%|███▉      | 738M/1.87G [00:11<00:14, 78.0MiB/s]
 40%|███▉      | 746M/1.87G [00:11<00:14, 79.0MiB/s]
 40%|████      | 754M/1.87G [00:11<00:13, 80.2MiB/s]
 41%|████      | 762M/1.87G [00:12<00:13, 80.3MiB/s]
 41%|████      | 770M/1.87G [00:12<00:14, 74.7MiB/s]
 42%|████▏     | 778M/1.87G [00:12<00:14, 73.4MiB/s]
 42%|████▏     | 785M/1.87G [00:12<00:14, 73.5MiB/s]
 42%|████▏     | 793M/1.87G [00:12<00:15, 70.5MiB/s]
 43%|████▎     | 800M/1.87G [00:12<00:16, 66.1MiB/s]
 43%|████▎     | 806M/1.87G [00:12<00:16, 62.8MiB/s]
 44%|████▎     | 813M/1.87G [00:12<00:17, 60.0MiB/s]
 44%|████▍     | 819M/1.87G [00:12<00:17, 59.9MiB/s]
 44%|████▍     | 825M/1.87G [00:13<00:17, 59.4MiB/s]
 44%|████▍     | 831M/1.87G [00:13<00:17, 59.5MiB/s]
 45%|████▍     | 837M/1.87G [00:13<00:17, 59.0MiB/s]
 45%|████▌     | 843M/1.87G [00:13<00:17, 59.7MiB/s]
 45%|████▌     | 849M/1.87G [00:13<00:23, 42.6MiB/s]
 46%|████▌     | 855M/1.87G [00:13<00:22, 45.7MiB/s]
 46%|████▌     | 860M/1.87G [00:13<00:20, 49.1MiB/s]
 46%|████▋     | 866M/1.87G [00:13<00:19, 51.4MiB/s]
 47%|████▋     | 873M/1.87G [00:13<00:18, 54.9MiB/s]
 47%|████▋     | 879M/1.87G [00:14<00:17, 56.0MiB/s]
 47%|████▋     | 885M/1.87G [00:14<00:17, 57.4MiB/s]
 48%|████▊     | 891M/1.87G [00:14<00:17, 57.5MiB/s]
 48%|████▊     | 896M/1.87G [00:14<00:16, 57.9MiB/s]
 48%|████▊     | 902M/1.87G [00:14<00:16, 58.0MiB/s]
 49%|████▊     | 908M/1.87G [00:14<00:16, 57.4MiB/s]
 49%|████▉     | 915M/1.87G [00:14<00:15, 60.1MiB/s]
 49%|████▉     | 921M/1.87G [00:14<00:17, 55.1MiB/s]
 50%|████▉     | 926M/1.87G [00:14<00:18, 50.3MiB/s]
 50%|████▉     | 932M/1.87G [00:15<00:17, 52.8MiB/s]
 50%|█████     | 938M/1.87G [00:15<00:17, 53.9MiB/s]
 51%|█████     | 944M/1.87G [00:15<00:17, 54.1MiB/s]
 51%|█████     | 949M/1.87G [00:15<00:16, 54.9MiB/s]
 51%|█████     | 955M/1.87G [00:15<00:17, 53.1MiB/s]
 51%|█████▏    | 960M/1.87G [00:15<00:17, 52.1MiB/s]
 52%|█████▏    | 965M/1.87G [00:15<00:17, 52.2MiB/s]
 52%|█████▏    | 971M/1.87G [00:15<00:17, 52.5MiB/s]
 52%|█████▏    | 976M/1.87G [00:15<00:16, 52.9MiB/s]
 53%|█████▎    | 982M/1.87G [00:15<00:16, 52.6MiB/s]
 53%|█████▎    | 989M/1.87G [00:16<00:14, 59.3MiB/s]
 53%|█████▎    | 997M/1.87G [00:16<00:13, 63.8MiB/s]
 54%|█████▍    | 1.00G/1.87G [00:16<00:12, 68.0MiB/s]
 54%|█████▍    | 1.01G/1.87G [00:16<00:12, 69.8MiB/s]
 55%|█████▍    | 1.02G/1.87G [00:16<00:11, 71.0MiB/s]
 55%|█████▍    | 1.03G/1.87G [00:16<00:11, 72.4MiB/s]
 55%|█████▌    | 1.03G/1.87G [00:16<00:11, 69.9MiB/s]
 56%|█████▌    | 1.04G/1.87G [00:16<00:12, 66.8MiB/s]
 56%|█████▌    | 1.05G/1.87G [00:16<00:11, 70.7MiB/s]
 57%|█████▋    | 1.06G/1.87G [00:17<00:11, 73.3MiB/s]
 57%|█████▋    | 1.06G/1.87G [00:17<00:10, 73.8MiB/s]
 57%|█████▋    | 1.07G/1.87G [00:17<00:10, 75.7MiB/s]
 58%|█████▊    | 1.08G/1.87G [00:17<00:10, 76.5MiB/s]
 58%|█████▊    | 1.09G/1.87G [00:17<00:10, 76.1MiB/s]
 59%|█████▊    | 1.10G/1.87G [00:17<00:10, 76.8MiB/s]
 59%|█████▉    | 1.10G/1.87G [00:17<00:10, 75.9MiB/s]
 59%|█████▉    | 1.11G/1.87G [00:17<00:10, 74.4MiB/s]
 60%|█████▉    | 1.12G/1.87G [00:17<00:10, 73.2MiB/s]
 60%|██████    | 1.13G/1.87G [00:17<00:09, 74.7MiB/s]
 61%|██████    | 1.13G/1.87G [00:18<00:09, 76.4MiB/s]
 61%|██████    | 1.14G/1.87G [00:18<00:09, 78.5MiB/s]
 62%|██████▏   | 1.15G/1.87G [00:18<00:09, 79.2MiB/s]
 62%|██████▏   | 1.16G/1.87G [00:18<00:08, 79.0MiB/s]
 62%|██████▏   | 1.17G/1.87G [00:18<00:08, 79.7MiB/s]
 63%|██████▎   | 1.17G/1.87G [00:18<00:08, 79.5MiB/s]
 63%|██████▎   | 1.18G/1.87G [00:18<00:08, 78.8MiB/s]
 64%|██████▍   | 1.19G/1.87G [00:18<00:08, 77.1MiB/s]
 64%|██████▍   | 1.20G/1.87G [00:18<00:08, 77.8MiB/s]
 65%|██████▍   | 1.21G/1.87G [00:18<00:08, 78.2MiB/s]
 65%|██████▌   | 1.21G/1.87G [00:19<00:08, 78.9MiB/s]
 65%|██████▌   | 1.22G/1.87G [00:19<00:08, 78.9MiB/s]
 66%|██████▌   | 1.23G/1.87G [00:19<00:08, 74.1MiB/s]
 66%|██████▋   | 1.24G/1.87G [00:19<00:08, 71.0MiB/s]
 67%|██████▋   | 1.25G/1.87G [00:19<00:08, 72.1MiB/s]
 67%|██████▋   | 1.25G/1.87G [00:19<00:08, 73.4MiB/s]
 68%|██████▊   | 1.26G/1.87G [00:19<00:08, 74.4MiB/s]
 68%|██████▊   | 1.27G/1.87G [00:19<00:08, 72.6MiB/s]
 68%|██████▊   | 1.28G/1.87G [00:19<00:08, 73.5MiB/s]
 69%|██████▊   | 1.28G/1.87G [00:20<00:07, 73.4MiB/s]
 69%|██████▉   | 1.29G/1.87G [00:20<00:07, 73.5MiB/s]
 69%|██████▉   | 1.30G/1.87G [00:20<00:07, 73.2MiB/s]
 70%|██████▉   | 1.31G/1.87G [00:20<00:07, 73.9MiB/s]
 70%|███████   | 1.31G/1.87G [00:20<00:07, 74.1MiB/s]
 71%|███████   | 1.32G/1.87G [00:20<00:07, 73.4MiB/s]
 71%|███████   | 1.33G/1.87G [00:20<00:07, 74.2MiB/s]
 72%|███████▏  | 1.34G/1.87G [00:20<00:07, 74.1MiB/s]
 72%|███████▏  | 1.34G/1.87G [00:20<00:07, 70.9MiB/s]
 72%|███████▏  | 1.35G/1.87G [00:20<00:07, 72.9MiB/s]
 73%|███████▎  | 1.36G/1.87G [00:21<00:06, 74.4MiB/s]
 73%|███████▎  | 1.37G/1.87G [00:21<00:06, 74.4MiB/s]
 74%|███████▎  | 1.37G/1.87G [00:21<00:06, 76.3MiB/s]
 74%|███████▍  | 1.38G/1.87G [00:21<00:06, 77.2MiB/s]
 74%|███████▍  | 1.39G/1.87G [00:21<00:06, 77.2MiB/s]
 75%|███████▍  | 1.40G/1.87G [00:21<00:06, 77.2MiB/s]
 75%|███████▌  | 1.41G/1.87G [00:21<00:06, 76.2MiB/s]
 76%|███████▌  | 1.41G/1.87G [00:21<00:05, 76.7MiB/s]
 76%|███████▌  | 1.42G/1.87G [00:21<00:06, 74.2MiB/s]
 76%|███████▋  | 1.43G/1.87G [00:21<00:05, 74.9MiB/s]
 77%|███████▋  | 1.44G/1.87G [00:22<00:05, 76.0MiB/s]
 77%|███████▋  | 1.44G/1.87G [00:22<00:05, 76.3MiB/s]
 78%|███████▊  | 1.45G/1.87G [00:22<00:05, 75.9MiB/s]
 78%|███████▊  | 1.46G/1.87G [00:22<00:05, 74.9MiB/s]
 79%|███████▊  | 1.47G/1.87G [00:22<00:05, 74.9MiB/s]
 79%|███████▉  | 1.47G/1.87G [00:22<00:05, 74.9MiB/s]
 79%|███████▉  | 1.48G/1.87G [00:22<00:05, 75.2MiB/s]
 80%|███████▉  | 1.49G/1.87G [00:22<00:05, 75.5MiB/s]
 80%|████████  | 1.50G/1.87G [00:22<00:04, 74.7MiB/s]
 81%|████████  | 1.50G/1.87G [00:22<00:04, 73.0MiB/s]
 81%|████████  | 1.51G/1.87G [00:23<00:04, 74.0MiB/s]
 81%|████████▏ | 1.52G/1.87G [00:23<00:04, 75.0MiB/s]
 82%|████████▏ | 1.53G/1.87G [00:23<00:04, 75.0MiB/s]
 82%|████████▏ | 1.54G/1.87G [00:23<00:04, 76.0MiB/s]
 83%|████████▎ | 1.54G/1.87G [00:23<00:04, 75.5MiB/s]
 83%|████████▎ | 1.55G/1.87G [00:23<00:04, 77.0MiB/s]
 83%|████████▎ | 1.56G/1.87G [00:23<00:03, 78.1MiB/s]
 84%|████████▍ | 1.57G/1.87G [00:23<00:03, 78.9MiB/s]
 84%|████████▍ | 1.58G/1.87G [00:23<00:03, 79.7MiB/s]
 85%|████████▍ | 1.58G/1.87G [00:23<00:03, 77.2MiB/s]
 85%|████████▌ | 1.59G/1.87G [00:24<00:03, 77.3MiB/s]
 86%|████████▌ | 1.60G/1.87G [00:24<00:03, 77.8MiB/s]
 86%|████████▌ | 1.61G/1.87G [00:24<00:03, 75.3MiB/s]
 86%|████████▋ | 1.61G/1.87G [00:24<00:03, 69.2MiB/s]
 87%|████████▋ | 1.62G/1.87G [00:24<00:04, 49.3MiB/s]
 87%|████████▋ | 1.63G/1.87G [00:24<00:04, 54.5MiB/s]
 88%|████████▊ | 1.64G/1.87G [00:24<00:03, 59.8MiB/s]
 88%|████████▊ | 1.64G/1.87G [00:24<00:03, 61.8MiB/s]
 88%|████████▊ | 1.65G/1.87G [00:25<00:03, 65.1MiB/s]
 89%|████████▉ | 1.66G/1.87G [00:25<00:03, 67.5MiB/s]
 89%|████████▉ | 1.66G/1.87G [00:25<00:02, 68.3MiB/s]
 90%|████████▉ | 1.67G/1.87G [00:25<00:02, 70.0MiB/s]
 90%|████████▉ | 1.68G/1.87G [00:25<00:02, 72.1MiB/s]
 90%|█████████ | 1.69G/1.87G [00:25<00:02, 73.3MiB/s]
 91%|█████████ | 1.70G/1.87G [00:25<00:02, 73.5MiB/s]
 91%|█████████ | 1.70G/1.87G [00:25<00:02, 74.3MiB/s]
 92%|█████████▏| 1.71G/1.87G [00:25<00:02, 72.9MiB/s]
 92%|█████████▏| 1.72G/1.87G [00:25<00:02, 72.0MiB/s]
 92%|█████████▏| 1.72G/1.87G [00:26<00:02, 63.0MiB/s]
 93%|█████████▎| 1.73G/1.87G [00:26<00:02, 60.1MiB/s]
 93%|█████████▎| 1.74G/1.87G [00:26<00:02, 58.9MiB/s]
 93%|█████████▎| 1.74G/1.87G [00:26<00:02, 58.0MiB/s]
 94%|█████████▎| 1.75G/1.87G [00:26<00:02, 57.7MiB/s]
 94%|█████████▍| 1.76G/1.87G [00:26<00:01, 57.4MiB/s]
 94%|█████████▍| 1.76G/1.87G [00:26<00:01, 58.5MiB/s]
 95%|█████████▍| 1.77G/1.87G [00:26<00:01, 60.2MiB/s]
 95%|█████████▍| 1.77G/1.87G [00:26<00:01, 62.0MiB/s]
 95%|█████████▌| 1.78G/1.87G [00:27<00:01, 56.5MiB/s]
 96%|█████████▌| 1.79G/1.87G [00:27<00:01, 48.1MiB/s]
 96%|█████████▌| 1.79G/1.87G [00:27<00:01, 50.2MiB/s]
 96%|█████████▌| 1.80G/1.87G [00:27<00:01, 51.1MiB/s]
 97%|█████████▋| 1.80G/1.87G [00:27<00:01, 52.0MiB/s]
 97%|█████████▋| 1.81G/1.87G [00:27<00:01, 37.3MiB/s]
 97%|█████████▋| 1.81G/1.87G [00:27<00:01, 42.3MiB/s]
 97%|█████████▋| 1.82G/1.87G [00:28<00:01, 47.0MiB/s]
 98%|█████████▊| 1.83G/1.87G [00:28<00:00, 49.9MiB/s]
 98%|█████████▊| 1.83G/1.87G [00:28<00:00, 51.4MiB/s]
 98%|█████████▊| 1.84G/1.87G [00:28<00:00, 55.0MiB/s]
 99%|█████████▉| 1.84G/1.87G [00:28<00:00, 57.8MiB/s]
 99%|█████████▉| 1.85G/1.87G [00:28<00:00, 58.8MiB/s]
 99%|█████████▉| 1.86G/1.87G [00:28<00:00, 58.5MiB/s]
100%|█████████▉| 1.86G/1.87G [00:28<00:00, 60.2MiB/s]

In [ ]:
training_dir = "/content/gdrive/MyDrive/data/dataset22050"

### Batch Size ###

* BATCH_SIZE is the amount of items being loaded into VRAM/memory at once.

* GRAD_ACCUM_STEPS is the amount of times we perform a forward pass with BATCH_SIZE amount of items before updating the parameters according to the SGD algorithm.

So a BATCH_SIZE of 2 and GRAD_ACCUM_STEPS of 32 would give an 'effective batch size' of 64 (i.e., 64 items considered per optimisation step).

The creators of XTTS-v2 recommend an effective batch size of 252 for proper training. (I found that reducing this to 126 gave me similar performance and faster fine-tuning, but we should probably listen to them.)

Your BATCH_SIZE will depend on how big your dataset items are and how much VRAM you have available. Make it as large as possible while ensuring that everything fits in VRAM and then make BATCH_SIZE*GRAD_ACCUM_STEPS==252.

In [ ]:

OPTIMIZER_WD_ONLY_ON_WEIGHTS = True
START_WITH_EVAL = True
BATCH_SIZE = 1
GRAD_ACUMM_STEPS = 1
LANGUAGE = "ar"

### Dataset Config

In [ ]:

model_args = GPTArgs(
    max_conditioning_length=242524,#the audio you will use for conditioning latents should be less than this
    min_conditioning_length=66168,#and more than this
    debug_loading_failures=True,#this will print output to console and help you find problems in your ds
    max_wav_length=530000,#set this to >= the longest audio in your dataset
    max_text_length=170,
    mel_norm_file=MEL_NORM_FILE,
    dvae_checkpoint=DVAE_CHECKPOINT,
    xtts_checkpoint=XTTS_CHECKPOINT,
    tokenizer_file=TOKENIZER_FILE,
    gpt_num_audio_tokens=1026,
    gpt_start_audio_token=1024,
    gpt_stop_audio_token=1025,
    gpt_use_masking_gt_prompt_approach=True,
    gpt_use_perceiver_resampler=True,
)

### Audio Config ###

The coqui TTS docs mention inspecting your data with the CheckSpectrograms.ipynb notebook to help decide on audio parameters. I think this is irrelevant for XTTS-v2, because it doesn't use the same audio config as some of the older coqui models and doesn't have the same parameters.

The default is 22050 for input and 24000 for output.

**the only reason my sample rate is lower is the dataset I chose has a sample rate of 16000. Assuming you are using your own data, sample_rate and dvae_sample_rate should match your data which should probably be 22050.**

In [ ]:
audio_config = XttsAudioConfig(sample_rate=22050, dvae_sample_rate=22050, output_sample_rate=24000)

### Speaker Reference ###

In [ ]:
SPEAKER_REFERENCE = "/content/gdrive/MyDrive/data/dataset22050/audio004-chunk65.wav"

### Trainer Config

In [ ]:
config = GPTTrainerConfig(
    run_eval=False,
    epochs = 15, # assuming you want to end training manually w/ keyboard interrupt
    output_path=OUT_PATH,
    model_args=model_args,
    run_name=RUN_NAME,
    project_name=PROJECT_NAME,
    run_description="""
        GPT XTTS training
        """,
    dashboard_logger=DASHBOARD_LOGGER,
    wandb_entity=None,
    logger_uri=LOGGER_URI,
    audio=audio_config,
    batch_size=BATCH_SIZE,
    batch_group_size=48,
    eval_batch_size=BATCH_SIZE,
    num_loader_workers=8, #consider decreasing if your jupyter env is crashing or similar
    eval_split_max_size=256,
    print_step=50,
    plot_step=100,
    log_model_step=1000,
    save_step=9999999999, #ALREADY SAVES EVERY EPOCHMaking this high on kaggle because Output dir is limited in size. I changed this to be size of training set/2 so I would effectively have a checkpoint every half epoch
    save_n_checkpoints=2,#if you want to store multiple checkpoint rather than just 1, increase this
    save_checkpoints=False,# Making this False on kaggle because Output dir is limited
    print_eval=False,
    optimizer="AdamW",
    optimizer_wd_only_on_weights=OPTIMIZER_WD_ONLY_ON_WEIGHTS,
    optimizer_params={"betas": [0.9, 0.96], "eps": 1e-8, "weight_decay": 1e-2},
    lr=5e-06,
    lr_scheduler="MultiStepLR",
    lr_scheduler_params={"milestones": [50000 * 18, 150000 * 18, 300000 * 18], "gamma": 0.5, "last_epoch": -1},
    test_sentences=[
        {
            "text": "في رفاهيه على جال هذيك هذاك الشي اللي بدا يصرى معها عجبها بزاف وشافت حياتها عمرها ما كانت تستنا ولا تتوقع انه يجي نهار تعيشها في حياتها",
            "speaker_wav": SPEAKER_REFERENCE,
            "language": LANGUAGE,
        },
    ],
)

# model = GPTTrainer.init_from_config(config)

### Load Dataset

In [ ]:
import torch
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import XttsAudioConfig, XttsArgs
from TTS.config.shared_configs import BaseDatasetConfig

torch.serialization.add_safe_globals([
    XttsConfig,
    XttsAudioConfig,
    BaseDatasetConfig,
    XttsArgs,  # ✅ New required class
])

In [ ]:
model = GPTTrainer.init_from_config(config)

>> DVAE weights restored from: /content/gdrive/MyDrive/models/EGTTS_v2.0_original_model_files/dvae.pth

In [ ]:
dataset_config = BaseDatasetConfig(
    formatter="ljspeech", meta_file_train="metadata.csv", language=LANGUAGE, path=training_dir
)
train_samples, eval_samples = load_tts_samples(dataset_config, eval_split=True, eval_split_size=0)

 | > Found 6910 files in /content/gdrive/.shortcut-targets-by-id/1-3wyUL1sMbtzmrrsYzXSSaj87srTsvTx/dataset22050

### Train! ###

**Note on warnings:**

The trainer will print out warnings if it encounters items in your dataset where the text exceeds 166 chars or the length of your audio exceeds max_wav_length (It will also have problems if you have data items that are < ~0.2s long, which you won't want anyway). You should remove these from your dataset or re-think how you're creating your dataset.

In [ ]:
import os

def clean_and_rename(samples):
    for sample in samples:
        original_path = sample['audio_file']

        # Fix the patha
        if original_path.endswith('.wav.wav'):
            fixed_path = original_path.replace('/wavs/', '/').replace('.wav.wav', '.wav')

            # Check if the incorrect file exists (for renaming)
            if os.path.exists(original_path):
                os.rename(original_path, fixed_path)
                print(f"Renamed: {original_path} -> {fixed_path}")
            elif os.path.exists(fixed_path):
                print(f"File already correct: {fixed_path}")
            else:
                print(f"File not found: {original_path} or {fixed_path}")

            # Update the sample dict
            sample['audio_file'] = fixed_path
            sample['audio_unique_name'] = '#' + fixed_path.replace(sample['root_path'], '').lstrip('/')
    return samples

# Apply the function
train_samples = clean_and_rename(train_samples)
eval_samples = clean_and_rename(eval_samples)

Streaming output truncated to the last 5000 lines.
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk119.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk70.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk25.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk232.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk24.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk11.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk436.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk83.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk360.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1098.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk132.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk289.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk373.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk261.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk336.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk318.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk334.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk401.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1388.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk265.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk304.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio012-chunk32.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk145.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk31.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk561.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk414.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1113.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk234.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk261.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk318.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk350.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk457.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1284.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk648.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk965.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk675.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk252.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk66.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk339.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio010-chunk156.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio007-chunk103.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk57.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk96.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk426.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk131.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk191.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk54.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio010-chunk94.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk334.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk87.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio012-chunk102.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk345.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk892.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk19.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk327.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk381.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk320.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio006-chunk284.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk552.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk117.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk259.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk158.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk405.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk912.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk9.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk236.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio020-chunk128.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk292.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk384.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk35.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk264.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk357.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk67.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk76.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk269.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk997.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk341.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio012-chunk97.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk111.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk95.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio009-chunk45.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk272.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk308.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk480.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk315.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk92.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk279.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio006-chunk203.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk426.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk214.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk192.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk874.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk486.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio001-chunk23.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk172.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk271.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk67.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk369.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1001.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk298.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio006-chunk179.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk174.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio020-chunk34.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk76.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio009-chunk68.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk809.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk12.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk212.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio012-chunk234.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk71.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk159.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk65.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk244.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1372.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio012-chunk147.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1247.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio010-chunk46.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk201.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk412.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1174.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio020-chunk46.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk208.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk327.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio020-chunk227.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk431.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk405.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk368.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk272.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio010-chunk166.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1280.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio009-chunk87.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk0.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio020-chunk135.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk62.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1086.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk253.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk493.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk74.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio010-chunk183.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk115.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk14.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk308.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk150.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk267.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk347.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio010-chunk39.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1122.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk337.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk261.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk448.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk51.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk250.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk339.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio012-chunk294.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk203.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk868.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk482.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk262.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk135.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1323.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1175.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk156.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1115.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk530.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk903.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio001-chunk96.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk96.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk122.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1125.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk316.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk43.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio009-chunk120.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk964.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio013-chunk26.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk61.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk103.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk199.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk641.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio010-chunk178.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk267.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk277.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk709.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk263.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk119.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk383.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk324.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk95.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk270.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk238.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk286.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk57.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk383.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio006-chunk149.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk79.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk342.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk32.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk421.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk107.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk335.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk35.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk62.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk609.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk881.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1160.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk200.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk332.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio011-chunk277.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1278.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk209.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk113.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk254.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk1342.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio001-chunk382.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk438.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk618.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio022-chunk146.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio018-chunk486.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk275.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk967.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk321.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk657.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio019-chunk256.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk108.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio008-chunk343.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio016-chunk81.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk161.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio021-chunk198.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio003-chunk192.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio017-chunk177.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio014-chunk522.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio002-chunk235.wav
File already correct: /content/gdrive/MyDrive/data/dataset22050/audio015-chunk10.wav

In [ ]:
train_samples

[{'text': 'الماستر الاول جاني النقاط تاعي ما كانتش عاليه بزاف وعجبت يعني العام بصح المعدل تاعي ما كانش عالي بزاف باش لقيت باش نلقى\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk32.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk32.wav'},
 {'text': 'عملاء المشروع رقم 10 واللي هو جلب عقود العمل للشركات اون فيت هذ سي سامبل تروح تحكم شركه راهي تخدم\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio022-chunk122.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio022-chunk122.wav'},
 {'text': 'صح انا كنت دائما نعتبر انه الدراسه كانت تحدي كنت\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio013-chunk217.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio013-chunk217.wav'},
 {'text': 'راك فاهم داكور واذا كان هو يكون عندك ليسورس تاعك بزاف ونصيحه للاخوه اللي راهم عندهم ورث ولا عندهم مدخرات اضافيه وحابين يدخلوا الاستثمار في مجال الشركات\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio017-chunk343.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio017-chunk343.wav'},
 {'text': 'وتقول تقول لي كي ندك عند باباك هذا ديري روحك تلعبي به\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk124.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk124.wav'},
 {'text': 'ونلبس هذيك الطابليه اللي مدتها لي خالتي تاع بنتها مقطعه ومرقعه مننا ومنا نروح\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk57.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk57.wav'},
 {'text': 'ليزبورتوني والخلصه باينه بلي راح تكون سوا كاش سوا سيبي ولا بصح كروحوا لانترناسيونال نحكيو على لي سيت وكذا كيفاش نقدر انايا نجيب\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio016-chunk190.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio016-chunk190.wav'},
 {'text': 'وكي سقسيت زملائي قالوا لي قالت يماها باللي محرومه من باباها ويروح\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk374.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk374.wav'},
 {'text': 'قلت له خليها عل هذك عقلها وتوكل على الله ام فانا درت هذاك انه كان مهم جدا انا باش\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk328.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk328.wav'},
 {'text': 'وتغير بنادم بك تغير له كاع حياته علاش ما\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio001-chunk358.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio001-chunk358.wav'},
 {'text': 'المنصب ديالك وتدور السياده انت ما دورتوش\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio019-chunk259.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio019-chunk259.wav'},
 {'text': 'تاعك تقدر تعلم الناس اطراف دي كونسلطسيون ولا كوتشينغ وين انت راك تبروبوزي الحرفه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio022-chunk104.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio022-chunk104.wav'},
 {'text': 'سنين انا قلتها في ثانيتين هو عاشها 10 سنين\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio001-chunk47.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio001-chunk47.wav'},
 {'text': 'لي باش يخير التمارين تاعه اكيد احنا مثلا نعطيك مثال على سبيل المثال احنا مبادره بدينا فيها هذه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio013-chunk74.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio013-chunk74.wav'},
 {'text': 'يديروا مره قاعده مع خوتي قلت ماما طولت واش راهي دير بديت نطل من التقبه تاع\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk147.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk147.wav'},
 {'text': 'خصنا عن كوراج يح يقرا عندي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio001-chunk179.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio001-chunk179.wav'},
 {'text': 'وللاسف لا تتوافق مع نمط البكالوريا ديما نحنا نوصيو التلاميذ\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio013-chunk62.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio013-chunk62.wav'},
 {'text': 'طبطبت هكذا كانت الظلمه نشفه انا كان باك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk649.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk649.wav'},
 {'text': 'كان في النهار يتبلى الف طفله تسما كابابل لوجهي ماشي شافي عليه بصح انا كنت صغيره كنت متخايله وتعرفوا وزيد الشيطان يزين لك هذ الحاجات خاصه في هذا السن\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio010-chunk24.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio010-chunk24.wav'},
 {'text': 'المرحله تاع التيست انه اكزاكتومون دونك وشنو عنده ليكيب اللي مخصوصين به هو تسما هو\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk602.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk602.wav'},
 {'text': 'دونك 48 ولايه ملايين الاشخاص هو يخدم مع سون كا يعني مرحله تاع التيست تقدر تقول فوضتها له\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk600.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk600.wav'},
 {'text': 'احنا درك نبداو فيه ان شاء الله خلينا نكمل في الوينين بروداكت كيفاه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk547.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk547.wav'},
 {'text': 'الكبرى الناس هاديين خاصهين ومتحافظين وكان من المستحسن جدا انا كنت يعني حارس انه باش يكون خاصه مناصرين يطلقوا خاصه من الجنوب\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk596.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk596.wav'},
 {'text': 'المواد مش فقط الفيزياء بما فيها نعم اكيد\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio013-chunk134.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio013-chunk134.wav'},
 {'text': 'ما فهمتش انايا مقابله ما بين انت ش جابك هنايا مباشره ش دخلك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk358.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk358.wav'},
 {'text': 'واش دير تعاود تولي في السيركيلاسيون هذيك بن عكنون وكذا باش تجيب مفتاح تمده لمرتك ولا لصاحبك ولا كارط نسيته ولا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio022-chunk61.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio022-chunk61.wav'},
 {'text': 'حلم هذا حلمي هذا مش ممكن يتحقق في في سنه او سنتين سيت فيزيون راهي رؤيه بعيده\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk303.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk303.wav'},
 {'text': 'الحاجه جديده شكيب راه موجد صوالح خلوهم في السر ان شاء الله ا صحيت\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio002-chunk333.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio002-chunk333.wav'},
 {'text': 'مفتوحه يفهموا خياليه وكانت كبيره دونك حنايا نقص المنافسه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk164.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk164.wav'},
 {'text': 'قلتله مي سمحلي كيفاشطوك ولا برين واشين ب وين فيب داير في بالك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio016-chunk309.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio016-chunk309.wav'},
 {'text': 'تحاوزوا يعني ما كانش عايش معنا ويما كل يوم كي تضربني\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk114.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk114.wav'},
 {'text': 'ا يلقى منتج بالك الشقه باش جابه وممكن يسرقوه له مش نهضروا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk823.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk823.wav'},
 {'text': 'بدون ذكر الاسماء دونك حنايا هنا بدينا تعرفوا على بعضنا وكل واحد فينا حسبت له هو الواعر من بعد يلقى واحد لا خير منه وهما ما يقر في احتكاك يا احتكاك كبير داروهنا شونس\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk235.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk235.wav'},
 {'text': 'يتخسر كلش ما عندكش اسيرونس تاع تاع الماكازان تاعك يسيح عليك كلش تخسر كلش دونك تقدر با اكزومبل اكشركه مع واحد دير\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk354.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk354.wav'},
 {'text': 'هاك راحوك على ديارهم وعاشوا حياه طبيعيه وباينه رجل الامن فيهم اللي امن هذو الوقائع والاحداث اللي صراو وفيهم اللي لا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio007-chunk94.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio007-chunk94.wav'},
 {'text': 'كانوا يفورميونا كانوا يفورميونا كيفاش نصوروا المنتجات كيفاه نخدموا كانت الكرياتيف سيتي لي فوطو\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk225.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk225.wav'},
 {'text': 'شغل عندي غير تاع استقصاء شويه جدليه شويه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio012-chunk58.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio012-chunk58.wav'},
 {'text': 'دونك تقدر تسيونتي ليزوديونس ديالك يسيونتيهم لك فيسبوك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk1033.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk1033.wav'},
 {'text': 'من عقليه بزنسي الى عقليه اونطربونور اللي يفتح عده\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk5.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk5.wav'},
 {'text': 'في الديجيتال ماركيتينغ يبدا اذا بالنسبه ل لي زوج يقدروا يبداو بقوه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio017-chunk277.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio017-chunk277.wav'},
 {'text': 'بصح ما نقولوش راك حب ازوس بصح دال\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk309.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk309.wav'},
 {'text': 'احرج موقف على وجه الارض كارثه تخيلوا تخيلوا هو يهضر مع بنته في التليفون ويدلع فيها لانه اسمها كما اسم هذيه وهي تجاوب فيه ا يا اختي حشوت في بلاصتك من الاخر\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio009-chunk94.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio009-chunk94.wav'},
 {'text': 'الباك دونك انا كان هذا البي تاعي في الاول من بعد عجزت له ما قدرتلوش ماشي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk213.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk213.wav'},
 {'text': 'لك فديما نعاودوا نقولوا ما تقولش اني فهمت الا بعد ما تكون\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio013-chunk114.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio013-chunk114.wav'},
 {'text': 'انا نحب اونطرينور في السبور نحبس\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk424.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk424.wav'},
 {'text': 'لا كذبوهم وقالوا بلي السيد هبل وراه يتخيل بصح صاحب علي كمال صاحب نتم هذاك رجع لنفس هذاك المكان اللي قالوا عليه علي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio007-chunk95.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio007-chunk95.wav'},
 {'text': 'تما يصنط اسباي على يصرا في سناب شات\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk831.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk831.wav'},
 {'text': 'شدي زط نسخ ان نكذب على روحي باش ننسى\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio001-chunk211.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio001-chunk211.wav'},
 {'text': 'يقش يقولك قرا وفهم كش تعتب فهمني ديفي باش تكمل الكتاب ش غير حاجه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio001-chunk229.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio001-chunk229.wav'},
 {'text': 'كان لابيغسون هذيك تم حساب الناس هذوك تفلسفوا شويه نورمال تفلسفوا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk427.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk427.wav'},
 {'text': 'هذا الموضوع را ديجا اصلا ياسين راك مديتوبيك للطلبه تاوعنا اللي في الدومين\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk387.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk387.wav'},
 {'text': 'فيها ما رانا في كل العالم ما عندناش مشاريع\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk192.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk192.wav'},
 {'text': 'حسيته كي تكون عندك واحد الثقه هذيك مالغري تبكي تخاف هكا من بعد تفكر باللي كلش بيد ربي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk93.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk93.wav'},
 {'text': 'هو ايجاد العملاء المحتملين في دبي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio022-chunk239.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio022-chunk239.wav'},
 {'text': 'شخص كامل داخلين مكتوب بيع وشراء في\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk157.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk157.wav'},
 {'text': 'حاملها هتحدثت معه على هذا الامر اول مره يدخل الجزائر وحامل كاس افريقيا لما خرجت الحافله من\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk255.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk255.wav'},
 {'text': 'اذا صحك الكلام خارج من قلبها ولاك شغل\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio006-chunk264.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio006-chunk264.wav'},
 {'text': 'لكن عندي سؤال برك نرجع لك للسيت ويب قلت بلي السيت ويب كي درت الحمله الاعلانيه ما جابتليش نتيجه ما وين كنت في الماركت بليس تاع\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk307.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk307.wav'},
 {'text': 'دونك هذه هي وقصه تاعي امل دك لو في ك نحكي لهم هكايا دونك حبيتون تتشجعوا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk82.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk82.wav'},
 {'text': 'مشاريع عندنا مشاريع من من روح من ماليزيا في الفليبين في الهايدرو عندنا في جنوب افريقيا في مصر في الاردن\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk184.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk184.wav'},

In [ ]:
import torchaudio
for sample in train_samples:
    try:
        waveform, sr = torchaudio.load(sample["audio_file"])
        if waveform.abs().max() == 0:
            print("Silent file:", sample["audio_file"])
    except Exception as e:
        print("Error loading:", sample["audio_file"], e)

In [ ]:
trainer = Trainer(
    TrainerArgs(
        restore_path=None,
        skip_train_epoch=False,
        start_with_eval=START_WITH_EVAL,
        grad_accum_steps=GRAD_ACUMM_STEPS,
    ),
    config,
    output_path=OUT_PATH,
    model=model,
    train_samples=train_samples,
    eval_samples=eval_samples,
)

 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 2
 | > Num. of Torch Threads: 1
 | > Torch seed: 1
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
wandb: Currently logged in as: ba-alasmar (ba-alasmar-nit) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

 > Model has 518442047 parameters

========Ignoring artifact: colab_kernel_launcher.py /usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py========

In [ ]:
trainer.fit()

 > EPOCH: 0/15
 --> /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000
/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(

 > TRAINING (2025-05-17 07:27:43)

 > Sampling by language: dict_keys(['ar'])

   --> TIME: 2025-05-17 07:27:51 -- STEP: 0/6841 -- GLOBAL_STEP: 0
     | > loss_text_ce: 0.038067929446697235  (0.038067929446697235)
     | > loss_mel_ce: 6.255189418792725  (6.255189418792725)
     | > loss: 6.293257236480713  (6.293257236480713)
     | > grad_norm: 0  (0)
     | > current_lr: 5e-06
     | > step_time: 0.9837  (0.983717679977417)
     | > loader_time: 7.4155  (7.415520191192627)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000========

   --> TIME: 2025-05-17 07:28:13 -- STEP: 50/6841 -- GLOBAL_STEP: 50
     | > loss_text_ce: 0.039510346949100494  (0.03794555708765983)
     | > loss_mel_ce: 4.370471477508545  (4.82191523551941)
     | > loss: 4.409981727600098  (4.85986078262329)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.165  (0.17918388366699214)
     | > loader_time: 0.0172  (0.020978631973266607)


   --> TIME: 2025-05-17 07:28:35 -- STEP: 100/6841 -- GLOBAL_STEP: 100
     | > loss_text_ce: 0.03626270592212677  (0.03775879783555866)
     | > loss_mel_ce: 5.54624605178833  (4.69530585050583)
     | > loss: 5.582508563995361  (4.733064644336697)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1497  (0.17944274187088008)
     | > loader_time: 0.0166  (0.019799559116363528)


   --> TIME: 2025-05-17 07:28:56 -- STEP: 150/6841 -- GLOBAL_STEP: 150
     | > loss_text_ce: 0.035855840891599655  (0.037250470916430155)
     | > loss_mel_ce: 4.049535274505615  (nan)
     | > loss: 4.085391044616699  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1607  (0.1764585288365682)
     | > loader_time: 0.013  (0.018362566630045565)


   --> TIME: 2025-05-17 07:29:19 -- STEP: 200/6841 -- GLOBAL_STEP: 200
     | > loss_text_ce: 0.03422471508383751  (0.036956625683233144)
     | > loss_mel_ce: 4.625871658325195  (nan)
     | > loss: 4.660096168518066  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1834  (0.18664156198501586)
     | > loader_time: 0.0142  (0.018343051671981792)


   --> TIME: 2025-05-17 07:29:42 -- STEP: 250/6841 -- GLOBAL_STEP: 250
     | > loss_text_ce: 0.030384765937924385  (0.03665371594578028)
     | > loss_mel_ce: 4.488492488861084  (nan)
     | > loss: 4.518877029418945  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2568  (0.1878101692199707)
     | > loader_time: 0.0225  (0.017813797950744614)


   --> TIME: 2025-05-17 07:30:05 -- STEP: 300/6841 -- GLOBAL_STEP: 300
     | > loss_text_ce: 0.03827492892742157  (0.03638432016596199)
     | > loss_mel_ce: 4.247073173522949  (nan)
     | > loss: 4.285347938537598  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2311  (0.18814374208450318)
     | > loader_time: 0.0196  (0.017264142036437977)


   --> TIME: 2025-05-17 07:30:27 -- STEP: 350/6841 -- GLOBAL_STEP: 350
     | > loss_text_ce: 0.0355747826397419  (0.03610147004148791)
     | > loss_mel_ce: 4.289303302764893  (nan)
     | > loss: 4.324878215789795  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2065  (0.18840174470629012)
     | > loader_time: 0.0098  (0.016825845582144578)


   --> TIME: 2025-05-17 07:30:49 -- STEP: 400/6841 -- GLOBAL_STEP: 400
     | > loss_text_ce: 0.03429471701383591  (0.036012337664142254)
     | > loss_mel_ce: 3.997354030609131  (nan)
     | > loss: 4.031648635864258  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1349  (0.1881844675540924)
     | > loader_time: 0.0116  (0.016333311200141868)


   --> TIME: 2025-05-17 07:31:12 -- STEP: 450/6841 -- GLOBAL_STEP: 450
     | > loss_text_ce: 0.03756494075059891  (0.035888408455583755)
     | > loss_mel_ce: 5.374093532562256  (nan)
     | > loss: 5.41165828704834  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1473  (0.18891593986087374)
     | > loader_time: 0.0108  (0.01602173275417747)


   --> TIME: 2025-05-17 07:31:34 -- STEP: 500/6841 -- GLOBAL_STEP: 500
     | > loss_text_ce: 0.0342528373003006  (0.03575134435668585)
     | > loss_mel_ce: 4.3059611320495605  (nan)
     | > loss: 4.340213775634766  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1919  (0.1880090970993042)
     | > loader_time: 0.0084  (0.01568349361419674)


   --> TIME: 2025-05-17 07:31:56 -- STEP: 550/6841 -- GLOBAL_STEP: 550
     | > loss_text_ce: 0.036635614931583405  (0.03567613886838607)
     | > loss_mel_ce: 3.942878007888794  (nan)
     | > loss: 3.979513645172119  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2773  (0.18800870418548588)
     | > loader_time: 0.0104  (0.015463434132662648)


   --> TIME: 2025-05-17 07:32:19 -- STEP: 600/6841 -- GLOBAL_STEP: 600
     | > loss_text_ce: 0.0326104573905468  (0.035630857277040684)
     | > loss_mel_ce: 4.147754669189453  (nan)
     | > loss: 4.180365085601807  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.323  (0.18814891537030534)
     | > loader_time: 0.0236  (0.015121283133824631)


   --> TIME: 2025-05-17 07:32:42 -- STEP: 650/6841 -- GLOBAL_STEP: 650
     | > loss_text_ce: 0.026700688526034355  (0.03557434311279884)
     | > loss_mel_ce: 3.8583388328552246  (nan)
     | > loss: 3.8850395679473877  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1778  (0.1884632781835703)
     | > loader_time: 0.0096  (0.014979819151071369)


   --> TIME: 2025-05-17 07:33:05 -- STEP: 700/6841 -- GLOBAL_STEP: 700
     | > loss_text_ce: 0.03615960106253624  (0.03548651304628168)
     | > loss_mel_ce: 4.729017734527588  (nan)
     | > loss: 4.765177249908447  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3354  (0.18918847697121766)
     | > loader_time: 0.0231  (0.014775476455688446)


   --> TIME: 2025-05-17 07:33:27 -- STEP: 750/6841 -- GLOBAL_STEP: 750
     | > loss_text_ce: 0.027705729007720947  (0.03536594878633816)
     | > loss_mel_ce: 4.146670818328857  (nan)
     | > loss: 4.174376487731934  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1254  (0.18940579605102548)
     | > loader_time: 0.0099  (0.014624637285868299)


   --> TIME: 2025-05-17 07:33:49 -- STEP: 800/6841 -- GLOBAL_STEP: 800
     | > loss_text_ce: 0.033706184476614  (0.03529205769300463)
     | > loss_mel_ce: 3.7542338371276855  (nan)
     | > loss: 3.78794002532959  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.178  (0.18919137120246896)
     | > loader_time: 0.0224  (0.014512746930122349)


   --> TIME: 2025-05-17 07:34:11 -- STEP: 850/6841 -- GLOBAL_STEP: 850
     | > loss_text_ce: 0.03624496981501579  (0.03523953899960309)
     | > loss_mel_ce: 3.6891071796417236  (nan)
     | > loss: 3.7253520488739014  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1268  (0.1886861268211814)
     | > loader_time: 0.0088  (0.014340648651123021)


   --> TIME: 2025-05-17 07:34:33 -- STEP: 900/6841 -- GLOBAL_STEP: 900
     | > loss_text_ce: 0.032455071806907654  (0.03516233839922481)
     | > loss_mel_ce: 4.062211990356445  (nan)
     | > loss: 4.094666957855225  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.264  (0.18865282482571077)
     | > loader_time: 0.009  (0.014213450749715145)


   --> TIME: 2025-05-17 07:34:56 -- STEP: 950/6841 -- GLOBAL_STEP: 950
     | > loss_text_ce: 0.03439869359135628  (0.03510034644486088)
     | > loss_mel_ce: 4.02274751663208  (nan)
     | > loss: 4.057146072387695  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1955  (0.1889692620227212)
     | > loader_time: 0.0138  (0.014062141870197475)


   --> TIME: 2025-05-17 07:35:19 -- STEP: 1000/6841 -- GLOBAL_STEP: 1000
     | > loss_text_ce: 0.03512062504887581  (0.03505983745120466)
     | > loss_mel_ce: 4.154532432556152  (nan)
     | > loss: 4.189652919769287  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1691  (0.18918271088600164)
     | > loader_time: 0.0084  (0.013962645530700661)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000========

   --> TIME: 2025-05-17 07:35:40 -- STEP: 1050/6841 -- GLOBAL_STEP: 1050
     | > loss_text_ce: 0.03552448749542236  (0.03502988612367993)
     | > loss_mel_ce: 4.253939628601074  (nan)
     | > loss: 4.289463996887207  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.149  (0.18867802869705932)
     | > loader_time: 0.0073  (0.013779914946783134)


   --> TIME: 2025-05-17 07:36:03 -- STEP: 1100/6841 -- GLOBAL_STEP: 1100
     | > loss_text_ce: 0.032954540103673935  (0.034960608981888394)
     | > loss_mel_ce: 4.279047966003418  (nan)
     | > loss: 4.312002658843994  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2206  (0.1889902279593729)
     | > loader_time: 0.0098  (0.013679254705255663)


   --> TIME: 2025-05-17 07:36:26 -- STEP: 1150/6841 -- GLOBAL_STEP: 1150
     | > loss_text_ce: 0.03408007696270943  (0.03490278997337039)
     | > loss_mel_ce: 4.1787614822387695  (nan)
     | > loss: 4.212841510772705  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2252  (0.1889334601941317)
     | > loader_time: 0.0184  (0.01359673023223875)


   --> TIME: 2025-05-17 07:36:47 -- STEP: 1200/6841 -- GLOBAL_STEP: 1200
     | > loss_text_ce: 0.03228775039315224  (0.034878136782596485)
     | > loss_mel_ce: 4.237914085388184  (nan)
     | > loss: 4.270201683044434  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2552  (0.18837385336558032)
     | > loader_time: 0.0117  (0.01350856661796568)


   --> TIME: 2025-05-17 07:37:10 -- STEP: 1250/6841 -- GLOBAL_STEP: 1250
     | > loss_text_ce: 0.03758835047483444  (0.034809818157553664)
     | > loss_mel_ce: 3.847076654434204  (nan)
     | > loss: 3.884665012359619  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2281  (0.1884025302886964)
     | > loader_time: 0.0243  (0.013474941062927228)


   --> TIME: 2025-05-17 07:37:32 -- STEP: 1300/6841 -- GLOBAL_STEP: 1300
     | > loss_text_ce: 0.03829677402973175  (0.03475283119970792)
     | > loss_mel_ce: 3.7702856063842773  (nan)
     | > loss: 3.808582305908203  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1807  (0.18847089125559888)
     | > loader_time: 0.0088  (0.013417950226710376)


   --> TIME: 2025-05-17 07:37:55 -- STEP: 1350/6841 -- GLOBAL_STEP: 1350
     | > loss_text_ce: 0.03090393915772438  (0.034718065140423984)
     | > loss_mel_ce: 4.0561933517456055  (nan)
     | > loss: 4.08709716796875  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2189  (0.18881355992069965)
     | > loader_time: 0.0114  (0.013343999650743257)


   --> TIME: 2025-05-17 07:38:18 -- STEP: 1400/6841 -- GLOBAL_STEP: 1400
     | > loss_text_ce: 0.0353267677128315  (0.03470236861546129)
     | > loss_mel_ce: 4.091354846954346  (nan)
     | > loss: 4.126681804656982  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1797  (0.1893097317218782)
     | > loader_time: 0.0131  (0.013285177605492714)


   --> TIME: 2025-05-17 07:38:41 -- STEP: 1450/6841 -- GLOBAL_STEP: 1450
     | > loss_text_ce: 0.03678121790289879  (0.03465793446990951)
     | > loss_mel_ce: 1.3918145895004272  (nan)
     | > loss: 1.428595781326294  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1355  (0.18942106460702846)
     | > loader_time: 0.0086  (0.013247100073715722)


   --> TIME: 2025-05-17 07:39:03 -- STEP: 1500/6841 -- GLOBAL_STEP: 1500
     | > loss_text_ce: 0.031477831304073334  (0.034614511766781424)
     | > loss_mel_ce: 3.5234227180480957  (nan)
     | > loss: 3.554900646209717  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1862  (0.18928780428568537)
     | > loader_time: 0.0087  (0.013183110872904446)


   --> TIME: 2025-05-17 07:39:25 -- STEP: 1550/6841 -- GLOBAL_STEP: 1550
     | > loss_text_ce: 0.030652692541480064  (0.03457925516270819)
     | > loss_mel_ce: 3.9764881134033203  (nan)
     | > loss: 4.007140636444092  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.148  (0.18887631647048472)
     | > loader_time: 0.0088  (0.013099462447627884)


   --> TIME: 2025-05-17 07:39:47 -- STEP: 1600/6841 -- GLOBAL_STEP: 1600
     | > loss_text_ce: 0.03119591251015663  (0.03455480468110178)
     | > loss_mel_ce: 4.3576178550720215  (nan)
     | > loss: 4.3888139724731445  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.201  (0.18890286758542074)
     | > loader_time: 0.0117  (0.013026292175054537)


   --> TIME: 2025-05-17 07:40:10 -- STEP: 1650/6841 -- GLOBAL_STEP: 1650
     | > loss_text_ce: 0.03244035318493843  (0.03453306803423342)
     | > loss_mel_ce: 3.8170604705810547  (nan)
     | > loss: 3.849500894546509  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2676  (0.18908359585386347)
     | > loader_time: 0.0099  (0.012962521061752769)


   --> TIME: 2025-05-17 07:40:33 -- STEP: 1700/6841 -- GLOBAL_STEP: 1700
     | > loss_text_ce: 0.032152578234672546  (0.03451856878531326)
     | > loss_mel_ce: 3.795243740081787  (nan)
     | > loss: 3.8273963928222656  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1319  (0.18950404026929082)
     | > loader_time: 0.0087  (0.012931102023405175)


   --> TIME: 2025-05-17 07:40:55 -- STEP: 1750/6841 -- GLOBAL_STEP: 1750
     | > loss_text_ce: 0.03545135259628296  (0.03447933267908435)
     | > loss_mel_ce: 3.8024098873138428  (nan)
     | > loss: 3.8378612995147705  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1385  (0.1891875608989172)
     | > loader_time: 0.0082  (0.012881540843418655)


   --> TIME: 2025-05-17 07:41:18 -- STEP: 1800/6841 -- GLOBAL_STEP: 1800
     | > loss_text_ce: 0.028182389214634895  (0.034455951917916505)
     | > loss_mel_ce: 3.7713208198547363  (nan)
     | > loss: 3.7995033264160156  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1525  (0.18950082249111613)
     | > loader_time: 0.0096  (0.012843049367268869)


   --> TIME: 2025-05-17 07:41:39 -- STEP: 1850/6841 -- GLOBAL_STEP: 1850
     | > loss_text_ce: 0.03135980665683746  (0.03443078111253071)
     | > loss_mel_ce: 4.242548942565918  (nan)
     | > loss: 4.273908615112305  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1937  (0.18919015136924963)
     | > loader_time: 0.0198  (0.012802303803933622)


   --> TIME: 2025-05-17 07:42:02 -- STEP: 1900/6841 -- GLOBAL_STEP: 1900
     | > loss_text_ce: 0.030111273750662804  (0.0344046344235539)
     | > loss_mel_ce: 3.9628870487213135  (nan)
     | > loss: 3.9929983615875244  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2365  (0.189399308530908)
     | > loader_time: 0.0099  (0.012801735777603941)


   --> TIME: 2025-05-17 07:42:24 -- STEP: 1950/6841 -- GLOBAL_STEP: 1950
     | > loss_text_ce: 0.03296225145459175  (0.03438324952259273)
     | > loss_mel_ce: 4.392435550689697  (nan)
     | > loss: 4.425397872924805  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2297  (0.18943180683331623)
     | > loader_time: 0.0088  (0.012754649382371157)


   --> TIME: 2025-05-17 07:42:47 -- STEP: 2000/6841 -- GLOBAL_STEP: 2000
     | > loss_text_ce: 0.03226865828037262  (0.03435738364048298)
     | > loss_mel_ce: 3.622502326965332  (nan)
     | > loss: 3.654771089553833  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1303  (0.18940997529029857)
     | > loader_time: 0.0103  (0.012714593291282644)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000========

   --> TIME: 2025-05-17 07:43:10 -- STEP: 2050/6841 -- GLOBAL_STEP: 2050
     | > loss_text_ce: 0.036594681441783905  (0.034346526241520514)
     | > loss_mel_ce: 4.314409255981445  (nan)
     | > loss: 4.351004123687744  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1739  (0.18958829437814118)
     | > loader_time: 0.0086  (0.012704580818734507)


   --> TIME: 2025-05-17 07:43:33 -- STEP: 2100/6841 -- GLOBAL_STEP: 2100
     | > loss_text_ce: 0.028479039669036865  (0.034320755614233825)
     | > loss_mel_ce: 3.3435168266296387  (nan)
     | > loss: 3.3719959259033203  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1643  (0.18970240445364106)
     | > loader_time: 0.0091  (0.012656230245317724)


   --> TIME: 2025-05-17 07:43:55 -- STEP: 2150/6841 -- GLOBAL_STEP: 2150
     | > loss_text_ce: 0.03398380056023598  (0.034306164564954646)
     | > loss_mel_ce: 4.29138708114624  (nan)
     | > loss: 4.325370788574219  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2205  (0.1896682424323505)
     | > loader_time: 0.0095  (0.012648123696792949)


   --> TIME: 2025-05-17 07:44:17 -- STEP: 2200/6841 -- GLOBAL_STEP: 2200
     | > loss_text_ce: 0.028858130797743797  (0.03426639106971293)
     | > loss_mel_ce: 4.227064609527588  (nan)
     | > loss: 4.255922794342041  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2714  (0.18961708827452234)
     | > loader_time: 0.0229  (0.012592367909171356)


   --> TIME: 2025-05-17 07:44:39 -- STEP: 2250/6841 -- GLOBAL_STEP: 2250
     | > loss_text_ce: 0.029364263638854027  (0.03422612260033684)
     | > loss_mel_ce: 4.975519180297852  (nan)
     | > loss: 5.004883289337158  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1742  (0.1895042668448555)
     | > loader_time: 0.0082  (0.012567443423800983)


   --> TIME: 2025-05-17 07:45:00 -- STEP: 2300/6841 -- GLOBAL_STEP: 2300
     | > loss_text_ce: 0.035211753100156784  (0.03420690609061195)
     | > loss_mel_ce: 4.230128765106201  (nan)
     | > loss: 4.265340328216553  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1796  (0.18917809672977617)
     | > loader_time: 0.031  (0.012525685144507352)


   --> TIME: 2025-05-17 07:45:23 -- STEP: 2350/6841 -- GLOBAL_STEP: 2350
     | > loss_text_ce: 0.030894961208105087  (0.03417528483699607)
     | > loss_mel_ce: 4.538681507110596  (nan)
     | > loss: 4.569576263427734  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.141  (0.1891676587246835)
     | > loader_time: 0.0078  (0.012508426219859014)


   --> TIME: 2025-05-17 07:45:45 -- STEP: 2400/6841 -- GLOBAL_STEP: 2400
     | > loss_text_ce: 0.02719784900546074  (0.03415370088225849)
     | > loss_mel_ce: 4.462606430053711  (nan)
     | > loss: 4.489804267883301  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1506  (0.1892240023612978)
     | > loader_time: 0.0081  (0.01248744398355484)


   --> TIME: 2025-05-17 07:46:08 -- STEP: 2450/6841 -- GLOBAL_STEP: 2450
     | > loss_text_ce: 0.03258271515369415  (0.034131473479222275)
     | > loss_mel_ce: 4.362471580505371  (nan)
     | > loss: 4.395054340362549  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1712  (0.18923276161660976)
     | > loader_time: 0.0103  (0.012446442136959154)


   --> TIME: 2025-05-17 07:46:29 -- STEP: 2500/6841 -- GLOBAL_STEP: 2500
     | > loss_text_ce: 0.03444323316216469  (0.03410337540209295)
     | > loss_mel_ce: 4.400000095367432  (nan)
     | > loss: 4.434443473815918  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2225  (0.18906408443450956)
     | > loader_time: 0.0191  (0.0124359133720398)


   --> TIME: 2025-05-17 07:46:51 -- STEP: 2550/6841 -- GLOBAL_STEP: 2550
     | > loss_text_ce: 0.034261953085660934  (0.03408146825783395)
     | > loss_mel_ce: 4.78883695602417  (nan)
     | > loss: 4.823099136352539  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.131  (0.18902076749240682)
     | > loader_time: 0.0081  (0.01240945002611946)


   --> TIME: 2025-05-17 07:47:13 -- STEP: 2600/6841 -- GLOBAL_STEP: 2600
     | > loss_text_ce: 0.03645307198166847  (0.034055635340941665)
     | > loss_mel_ce: 4.080101490020752  (nan)
     | > loss: 4.1165547370910645  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.126  (0.18887882471084624)
     | > loader_time: 0.0126  (0.01238189027859615)


   --> TIME: 2025-05-17 07:47:36 -- STEP: 2650/6841 -- GLOBAL_STEP: 2650
     | > loss_text_ce: 0.03281126543879509  (0.034047240787097914)
     | > loss_mel_ce: 3.8900954723358154  (nan)
     | > loss: 3.9229066371917725  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1928  (0.1889776937016905)
     | > loader_time: 0.0079  (0.0123503756073286)


   --> TIME: 2025-05-17 07:47:59 -- STEP: 2700/6841 -- GLOBAL_STEP: 2700
     | > loss_text_ce: 0.0322917215526104  (0.03402699756608523)
     | > loss_mel_ce: 4.08207893371582  (nan)
     | > loss: 4.114370822906494  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1273  (0.18906807272522577)
     | > loader_time: 0.008  (0.012339279651641851)


   --> TIME: 2025-05-17 07:48:21 -- STEP: 2750/6841 -- GLOBAL_STEP: 2750
     | > loss_text_ce: 0.031407490372657776  (0.034000177169388066)
     | > loss_mel_ce: 4.480737686157227  (nan)
     | > loss: 4.512145042419434  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2732  (0.18893975318561942)
     | > loader_time: 0.0239  (0.012312828844243836)


   --> TIME: 2025-05-17 07:48:43 -- STEP: 2800/6841 -- GLOBAL_STEP: 2800
     | > loss_text_ce: 0.03750475496053696  (0.033974552924212684)
     | > loss_mel_ce: 4.618882656097412  (nan)
     | > loss: 4.6563873291015625  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1357  (0.1888265346629283)
     | > loader_time: 0.0112  (0.01230257894311633)


   --> TIME: 2025-05-17 07:49:04 -- STEP: 2850/6841 -- GLOBAL_STEP: 2850
     | > loss_text_ce: 0.036223992705345154  (0.03395399693530386)
     | > loss_mel_ce: 4.682978630065918  (nan)
     | > loss: 4.719202518463135  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2559  (0.18860515761793745)
     | > loader_time: 0.0101  (0.012277623477735023)


   --> TIME: 2025-05-17 07:49:27 -- STEP: 2900/6841 -- GLOBAL_STEP: 2900
     | > loss_text_ce: 0.02990671806037426  (0.0339381036753285)
     | > loss_mel_ce: 4.072134494781494  (nan)
     | > loss: 4.102041244506836  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.174  (0.18884295504668702)
     | > loader_time: 0.009  (0.012278586173879695)


   --> TIME: 2025-05-17 07:49:49 -- STEP: 2950/6841 -- GLOBAL_STEP: 2950
     | > loss_text_ce: 0.02965610660612583  (0.033915394815474266)
     | > loss_mel_ce: 4.875185966491699  (nan)
     | > loss: 4.904841899871826  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1661  (0.1887709242610612)
     | > loader_time: 0.011  (0.012255843291848397)


   --> TIME: 2025-05-17 07:50:11 -- STEP: 3000/6841 -- GLOBAL_STEP: 3000
     | > loss_text_ce: 0.03282004967331886  (0.03389762206499781)
     | > loss_mel_ce: 4.13195276260376  (nan)
     | > loss: 4.164772987365723  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1486  (0.18868297163645464)
     | > loader_time: 0.0096  (0.012240579684575403)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000========

   --> TIME: 2025-05-17 07:50:33 -- STEP: 3050/6841 -- GLOBAL_STEP: 3050
     | > loss_text_ce: 0.026761429384350777  (0.03387641503613018)
     | > loss_mel_ce: 3.7062127590179443  (nan)
     | > loss: 3.7329742908477783  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1936  (0.1885805589644639)
     | > loader_time: 0.0102  (0.012234595173695052)


   --> TIME: 2025-05-17 07:50:55 -- STEP: 3100/6841 -- GLOBAL_STEP: 3100
     | > loss_text_ce: 0.034083493053913116  (0.033853383584008155)
     | > loss_mel_ce: 3.6821372509002686  (nan)
     | > loss: 3.7162208557128906  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1442  (0.1885121333214548)
     | > loader_time: 0.0084  (0.012208865227237829)


   --> TIME: 2025-05-17 07:51:18 -- STEP: 3150/6841 -- GLOBAL_STEP: 3150
     | > loss_text_ce: 0.03322644904255867  (0.033841812890318686)
     | > loss_mel_ce: 4.794926643371582  (nan)
     | > loss: 4.828153133392334  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1763  (0.18867040740119123)
     | > loader_time: 0.0089  (0.012197777051774286)


   --> TIME: 2025-05-17 07:51:41 -- STEP: 3200/6841 -- GLOBAL_STEP: 3200
     | > loss_text_ce: 0.035015419125556946  (0.033820516965352036)
     | > loss_mel_ce: 3.6280059814453125  (nan)
     | > loss: 3.6630213260650635  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2038  (0.18879037089645898)
     | > loader_time: 0.0115  (0.01218865886330605)


   --> TIME: 2025-05-17 07:52:04 -- STEP: 3250/6841 -- GLOBAL_STEP: 3250
     | > loss_text_ce: 0.033005788922309875  (0.0338104050039099)
     | > loss_mel_ce: 3.7360405921936035  (nan)
     | > loss: 3.7690463066101074  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1854  (0.1889927867009093)
     | > loader_time: 0.0105  (0.012195491937490614)


   --> TIME: 2025-05-17 07:52:27 -- STEP: 3300/6841 -- GLOBAL_STEP: 3300
     | > loss_text_ce: 0.0328420028090477  (0.03379049862029429)
     | > loss_mel_ce: 4.995340347290039  (nan)
     | > loss: 5.028182506561279  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.223  (0.1889890298698891)
     | > loader_time: 0.0099  (0.012176230098261982)


   --> TIME: 2025-05-17 07:52:49 -- STEP: 3350/6841 -- GLOBAL_STEP: 3350
     | > loss_text_ce: 0.03587283194065094  (0.03377839264251407)
     | > loss_mel_ce: 3.920628309249878  (nan)
     | > loss: 3.9565012454986572  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1474  (0.18894984038908125)
     | > loader_time: 0.0088  (0.012168774106609291)


   --> TIME: 2025-05-17 07:53:12 -- STEP: 3400/6841 -- GLOBAL_STEP: 3400
     | > loss_text_ce: 0.03312499821186066  (0.033757763097391424)
     | > loss_mel_ce: 3.6554529666900635  (nan)
     | > loss: 3.688577890396118  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1421  (0.18905935953645178)
     | > loader_time: 0.0086  (0.012170621928046736)


   --> TIME: 2025-05-17 07:53:34 -- STEP: 3450/6841 -- GLOBAL_STEP: 3450
     | > loss_text_ce: 0.03244375064969063  (0.03372997840515513)
     | > loss_mel_ce: 3.584073305130005  (nan)
     | > loss: 3.6165170669555664  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1451  (0.18913252173990477)
     | > loader_time: 0.0106  (0.012152345353278565)


   --> TIME: 2025-05-17 07:53:57 -- STEP: 3500/6841 -- GLOBAL_STEP: 3500
     | > loss_text_ce: 0.034029386937618256  (0.033720400222178024)
     | > loss_mel_ce: 4.185024261474609  (nan)
     | > loss: 4.219053745269775  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2299  (0.1891455366270886)
     | > loader_time: 0.0091  (0.012149254458291195)


   --> TIME: 2025-05-17 07:54:19 -- STEP: 3550/6841 -- GLOBAL_STEP: 3550
     | > loss_text_ce: 0.0319618321955204  (0.03370373678301841)
     | > loss_mel_ce: 4.177352428436279  (nan)
     | > loss: 4.209314346313477  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2173  (0.1890974017264141)
     | > loader_time: 0.0135  (0.012121016206875657)


   --> TIME: 2025-05-17 07:54:41 -- STEP: 3600/6841 -- GLOBAL_STEP: 3600
     | > loss_text_ce: 0.035978611558675766  (0.03368568834124341)
     | > loss_mel_ce: 3.8664355278015137  (nan)
     | > loss: 3.902414083480835  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1249  (0.1891230552064051)
     | > loader_time: 0.0081  (0.01212012178368039)


   --> TIME: 2025-05-17 07:55:04 -- STEP: 3650/6841 -- GLOBAL_STEP: 3650
     | > loss_text_ce: 0.03001522459089756  (0.033671790401719214)
     | > loss_mel_ce: 3.678842306137085  (nan)
     | > loss: 3.708857536315918  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2005  (0.18925723820516538)
     | > loader_time: 0.0074  (0.012106341270551293)


   --> TIME: 2025-05-17 07:55:25 -- STEP: 3700/6841 -- GLOBAL_STEP: 3700
     | > loss_text_ce: 0.028607472777366638  (0.03365372002074446)
     | > loss_mel_ce: 4.172214508056641  (nan)
     | > loss: 4.200821876525879  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1285  (0.18898996585124278)
     | > loader_time: 0.0085  (0.012089084419044292)


   --> TIME: 2025-05-17 07:55:47 -- STEP: 3750/6841 -- GLOBAL_STEP: 3750
     | > loss_text_ce: 0.0343792662024498  (0.033644454671442545)
     | > loss_mel_ce: 3.725512742996216  (nan)
     | > loss: 3.759891986846924  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1442  (0.18888132082621287)
     | > loader_time: 0.009  (0.012073427391052249)


   --> TIME: 2025-05-17 07:56:10 -- STEP: 3800/6841 -- GLOBAL_STEP: 3800
     | > loss_text_ce: 0.03633658215403557  (0.033632064989620965)
     | > loss_mel_ce: 4.339609146118164  (nan)
     | > loss: 4.375945568084717  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1794  (0.18906283660938894)
     | > loader_time: 0.0095  (0.012068399567353102)


   --> TIME: 2025-05-17 07:56:33 -- STEP: 3850/6841 -- GLOBAL_STEP: 3850
     | > loss_text_ce: 0.019504958763718605  (0.03362042160777307)
     | > loss_mel_ce: 4.178371906280518  (nan)
     | > loss: 4.197876930236816  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.13  (0.18911609340023713)
     | > loader_time: 0.008  (0.012066633670361015)


   --> TIME: 2025-05-17 07:56:54 -- STEP: 3900/6841 -- GLOBAL_STEP: 3900
     | > loss_text_ce: 0.030193964019417763  (0.033605571191949)
     | > loss_mel_ce: 4.094069957733154  (nan)
     | > loss: 4.124263763427734  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1248  (0.18900902442443093)
     | > loader_time: 0.0088  (0.012050420320951025)


   --> TIME: 2025-05-17 07:57:17 -- STEP: 3950/6841 -- GLOBAL_STEP: 3950
     | > loss_text_ce: 0.03576449304819107  (0.033602291454054176)
     | > loss_mel_ce: 3.9493308067321777  (nan)
     | > loss: 3.985095262527466  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.211  (0.18904490682143227)
     | > loader_time: 0.0095  (0.012053195917153665)


   --> TIME: 2025-05-17 07:57:39 -- STEP: 4000/6841 -- GLOBAL_STEP: 4000
     | > loss_text_ce: 0.028799762949347496  (0.03357914468972017)
     | > loss_mel_ce: 3.7413856983184814  (nan)
     | > loss: 3.7701854705810547  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2099  (0.18905550676584273)
     | > loader_time: 0.0084  (0.012031808674335483)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000========

   --> TIME: 2025-05-17 07:58:02 -- STEP: 4050/6841 -- GLOBAL_STEP: 4050
     | > loss_text_ce: 0.03321122005581856  (0.03356532114523433)
     | > loss_mel_ce: 4.120960235595703  (nan)
     | > loss: 4.154171466827393  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1443  (0.18908588921582287)
     | > loader_time: 0.0084  (0.012039103213651684)


   --> TIME: 2025-05-17 07:58:24 -- STEP: 4100/6841 -- GLOBAL_STEP: 4100
     | > loss_text_ce: 0.03420577943325043  (0.03355824916010227)
     | > loss_mel_ce: 4.133420467376709  (nan)
     | > loss: 4.16762638092041  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2191  (0.18908753127586578)
     | > loader_time: 0.0314  (0.012042781667011544)


   --> TIME: 2025-05-17 07:58:46 -- STEP: 4150/6841 -- GLOBAL_STEP: 4150
     | > loss_text_ce: 0.030863381922245026  (0.033543715092342344)
     | > loss_mel_ce: 3.342435598373413  (nan)
     | > loss: 3.3732988834381104  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1274  (0.18899545296129003)
     | > loader_time: 0.0078  (0.012024404054664707)


   --> TIME: 2025-05-17 07:59:08 -- STEP: 4200/6841 -- GLOBAL_STEP: 4200
     | > loss_text_ce: 0.03296923264861107  (0.03352531037914259)
     | > loss_mel_ce: 4.147176265716553  (nan)
     | > loss: 4.180145263671875  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2636  (0.18903438857623536)
     | > loader_time: 0.0082  (0.012009471257527672)


   --> TIME: 2025-05-17 07:59:31 -- STEP: 4250/6841 -- GLOBAL_STEP: 4250
     | > loss_text_ce: 0.03325262293219566  (0.03352295491055533)
     | > loss_mel_ce: 3.8863022327423096  (nan)
     | > loss: 3.9195549488067627  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1503  (0.18902050568075768)
     | > loader_time: 0.0094  (0.012014911090626435)


   --> TIME: 2025-05-17 07:59:53 -- STEP: 4300/6841 -- GLOBAL_STEP: 4300
     | > loss_text_ce: 0.03565222769975662  (0.03350760935914034)
     | > loss_mel_ce: 4.7743120193481445  (nan)
     | > loss: 4.809964179992676  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.323  (0.18899872402812185)
     | > loader_time: 0.0162  (0.012018710125324336)


   --> TIME: 2025-05-17 08:00:15 -- STEP: 4350/6841 -- GLOBAL_STEP: 4350
     | > loss_text_ce: 0.03359060361981392  (0.03348867662850471)
     | > loss_mel_ce: 4.072320461273193  (nan)
     | > loss: 4.1059112548828125  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3074  (0.18903583208719918)
     | > loader_time: 0.0095  (0.011999145321462347)


   --> TIME: 2025-05-17 08:00:38 -- STEP: 4400/6841 -- GLOBAL_STEP: 4400
     | > loss_text_ce: 0.03277004510164261  (0.03346965025771751)
     | > loss_mel_ce: 3.6443192958831787  (nan)
     | > loss: 3.6770894527435303  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1421  (0.18912031363357232)
     | > loader_time: 0.0102  (0.011988011598587039)


   --> TIME: 2025-05-17 08:01:00 -- STEP: 4450/6841 -- GLOBAL_STEP: 4450
     | > loss_text_ce: 0.025820180773735046  (0.03344785866903124)
     | > loss_mel_ce: 4.528702259063721  (nan)
     | > loss: 4.554522514343262  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1407  (0.1890051481161228)
     | > loader_time: 0.0082  (0.011978921997413211)

error loading /content/gdrive/MyDrive/data/dataset22050/audio018-chunk1.wav (<class 'AssertionError'>, AssertionError('UNK token found in sociét \u200fsolution solaire\n -> [ar]sociét solution solaire'), <traceback object at 0x7d4d1580c9c0>)

   --> TIME: 2025-05-17 08:01:23 -- STEP: 4500/6841 -- GLOBAL_STEP: 4500
     | > loss_text_ce: 0.030558457598090172  (0.0334282848702537)
     | > loss_mel_ce: 3.3503623008728027  (nan)
     | > loss: 3.380920648574829  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1701  (0.18912683147854306)
     | > loader_time: 0.0086  (0.011982165760464139)


   --> TIME: 2025-05-17 08:01:44 -- STEP: 4550/6841 -- GLOBAL_STEP: 4550
     | > loss_text_ce: 0.03373276814818382  (0.03341199283784896)
     | > loss_mel_ce: 3.256610870361328  (nan)
     | > loss: 3.2903435230255127  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1588  (0.1890603565383747)
     | > loader_time: 0.0092  (0.011976811283237332)


   --> TIME: 2025-05-17 08:02:07 -- STEP: 4600/6841 -- GLOBAL_STEP: 4600
     | > loss_text_ce: 0.03292711079120636  (0.0334018612551787)
     | > loss_mel_ce: 5.251677513122559  (nan)
     | > loss: 5.284604549407959  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3174  (0.1891654900882559)
     | > loader_time: 0.0101  (0.011971969759982557)

error loading /content/gdrive/MyDrive/data/dataset22050/audio015-chunk188.wav (<class 'AssertionError'>, AssertionError('UNK token found in \u200fendعمين وكيجي تريكروتي واحد وشنو هما زعما المعايير اللي تشوفهم وكيفاش تتعامل مع\n -> [ar]endعمين وكيجي تريكروتي واحد وشنو هما زعما المعايير اللي تشوفهم وكيفاش تتعامل مع'), <traceback object at 0x7d4d159b3c40>)

   --> TIME: 2025-05-17 08:02:31 -- STEP: 4650/6841 -- GLOBAL_STEP: 4650
     | > loss_text_ce: 0.035876695066690445  (0.03339293264934138)
     | > loss_mel_ce: 3.646162271499634  (nan)
     | > loss: 3.6820390224456787  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3016  (0.18933531289459585)
     | > loader_time: 0.013  (0.011960969894163068)


   --> TIME: 2025-05-17 08:02:54 -- STEP: 4700/6841 -- GLOBAL_STEP: 4700
     | > loss_text_ce: 0.031106945127248764  (0.0333806658678867)
     | > loss_mel_ce: 4.064615249633789  (nan)
     | > loss: 4.095722198486328  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.21  (0.18946102421334474)
     | > loader_time: 0.0098  (0.011952768893952062)


   --> TIME: 2025-05-17 08:03:17 -- STEP: 4750/6841 -- GLOBAL_STEP: 4750
     | > loss_text_ce: 0.0353623665869236  (0.0333696488283183)
     | > loss_mel_ce: 4.942680358886719  (nan)
     | > loss: 4.9780426025390625  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2546  (0.1896224544926696)
     | > loader_time: 0.0095  (0.011948641626458423)


   --> TIME: 2025-05-17 08:03:40 -- STEP: 4800/6841 -- GLOBAL_STEP: 4800
     | > loss_text_ce: 0.036429956555366516  (0.03335546373855328)
     | > loss_mel_ce: 4.028136253356934  (nan)
     | > loss: 4.064566135406494  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1462  (0.18971821948885942)
     | > loader_time: 0.0119  (0.011935454110304515)


   --> TIME: 2025-05-17 08:04:02 -- STEP: 4850/6841 -- GLOBAL_STEP: 4850
     | > loss_text_ce: 0.03143938630819321  (0.03334632081507719)
     | > loss_mel_ce: 3.538987874984741  (nan)
     | > loss: 3.570427179336548  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1706  (0.18972411342502896)
     | > loader_time: 0.0081  (0.011919109895057286)


   --> TIME: 2025-05-17 08:04:25 -- STEP: 4900/6841 -- GLOBAL_STEP: 4900
     | > loss_text_ce: 0.030283581465482712  (0.03333876941086995)
     | > loss_mel_ce: 4.632151126861572  (nan)
     | > loss: 4.6624345779418945  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2142  (0.18978308152179366)
     | > loader_time: 0.0093  (0.011926397742057337)


   --> TIME: 2025-05-17 08:04:47 -- STEP: 4950/6841 -- GLOBAL_STEP: 4950
     | > loss_text_ce: 0.03464941680431366  (0.033328260729333994)
     | > loss_mel_ce: 3.830775737762451  (nan)
     | > loss: 3.8654251098632812  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1419  (0.18976332992014297)
     | > loader_time: 0.0067  (0.011910368408819646)


   --> TIME: 2025-05-17 08:05:10 -- STEP: 5000/6841 -- GLOBAL_STEP: 5000
     | > loss_text_ce: 0.03816532343626022  (0.03331722049042582)
     | > loss_mel_ce: 3.4470674991607666  (nan)
     | > loss: 3.4852328300476074  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1495  (0.18981026515960728)
     | > loader_time: 0.0093  (0.011913787508010866)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000========

   --> TIME: 2025-05-17 08:05:32 -- STEP: 5050/6841 -- GLOBAL_STEP: 5050
     | > loss_text_ce: 0.03440452367067337  (0.03330845540444743)
     | > loss_mel_ce: 0.8833404779434204  (nan)
     | > loss: 0.9177449941635132  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2614  (0.18989947323751954)
     | > loader_time: 0.0109  (0.011905660770907262)


   --> TIME: 2025-05-17 08:05:54 -- STEP: 5100/6841 -- GLOBAL_STEP: 5100
     | > loss_text_ce: 0.02960917353630066  (0.03330085200458472)
     | > loss_mel_ce: 4.913956642150879  (nan)
     | > loss: 4.943565845489502  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1891  (0.1898918646457151)
     | > loader_time: 0.0115  (0.011909314931607708)


   --> TIME: 2025-05-17 08:06:18 -- STEP: 5150/6841 -- GLOBAL_STEP: 5150
     | > loss_text_ce: 0.032879143953323364  (0.03329099250649941)
     | > loss_mel_ce: 4.731638431549072  (nan)
     | > loss: 4.764517784118652  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2151  (0.1900140306787586)
     | > loader_time: 0.0261  (0.011909452086513471)


   --> TIME: 2025-05-17 08:06:40 -- STEP: 5200/6841 -- GLOBAL_STEP: 5200
     | > loss_text_ce: 0.03159533441066742  (0.033285207440360204)
     | > loss_mel_ce: 4.521520137786865  (nan)
     | > loss: 4.553115367889404  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2069  (0.18997206949270712)
     | > loader_time: 0.0092  (0.011906815858987651)


   --> TIME: 2025-05-17 08:07:02 -- STEP: 5250/6841 -- GLOBAL_STEP: 5250
     | > loss_text_ce: 0.028906239196658134  (0.03327256577249081)
     | > loss_mel_ce: 3.774305582046509  (nan)
     | > loss: 3.8032119274139404  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2157  (0.1899397756939846)
     | > loader_time: 0.0152  (0.01190048308599562)


   --> TIME: 2025-05-17 08:07:24 -- STEP: 5300/6841 -- GLOBAL_STEP: 5300
     | > loss_text_ce: 0.033466506749391556  (0.03326328934855615)
     | > loss_mel_ce: 3.697894811630249  (nan)
     | > loss: 3.7313613891601562  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1685  (0.18985811386468307)
     | > loader_time: 0.008  (0.01189024016542254)


   --> TIME: 2025-05-17 08:07:46 -- STEP: 5350/6841 -- GLOBAL_STEP: 5350
     | > loss_text_ce: 0.03233933448791504  (0.03325269233609468)
     | > loss_mel_ce: 4.006101608276367  (nan)
     | > loss: 4.038440704345703  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2785  (0.18987731269586905)
     | > loader_time: 0.0124  (0.011895747184753417)


   --> TIME: 2025-05-17 08:08:08 -- STEP: 5400/6841 -- GLOBAL_STEP: 5400
     | > loss_text_ce: 0.028914829716086388  (0.0332369740096921)
     | > loss_mel_ce: 3.942125082015991  (nan)
     | > loss: 3.9710400104522705  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1305  (0.18979294516422174)
     | > loader_time: 0.0085  (0.0118911768771984)


   --> TIME: 2025-05-17 08:08:30 -- STEP: 5450/6841 -- GLOBAL_STEP: 5450
     | > loss_text_ce: 0.03081383928656578  (0.033231617931037294)
     | > loss_mel_ce: 2.891937255859375  (nan)
     | > loss: 2.9227511882781982  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1464  (0.18977421143733075)
     | > loader_time: 0.0087  (0.011893409938987248)


   --> TIME: 2025-05-17 08:08:53 -- STEP: 5500/6841 -- GLOBAL_STEP: 5500
     | > loss_text_ce: 0.028865044936537743  (0.0332236820130863)
     | > loss_mel_ce: 4.499434947967529  (nan)
     | > loss: 4.528299808502197  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1387  (0.18983278023112946)
     | > loader_time: 0.0079  (0.011880360950123185)

error loading /content/gdrive/MyDrive/data/dataset22050/audio018-chunk1.wav (<class 'AssertionError'>, AssertionError('UNK token found in sociét \u200fsolution solaire\n -> [ar]sociét solution solaire'), <traceback object at 0x7d4d157bd840>)

   --> TIME: 2025-05-17 08:09:15 -- STEP: 5550/6841 -- GLOBAL_STEP: 5550
     | > loss_text_ce: 0.0387418270111084  (0.03321819150132369)
     | > loss_mel_ce: 3.615011215209961  (nan)
     | > loss: 3.6537530422210693  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2647  (0.18977873183585542)
     | > loader_time: 0.0087  (0.011886677398337979)


   --> TIME: 2025-05-17 08:09:36 -- STEP: 5600/6841 -- GLOBAL_STEP: 5600
     | > loss_text_ce: 0.029210058972239494  (0.033206756102652946)
     | > loss_mel_ce: 3.489591360092163  (nan)
     | > loss: 3.51880145072937  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1543  (0.18966066654239422)
     | > loader_time: 0.0093  (0.011871521600655152)


   --> TIME: 2025-05-17 08:09:58 -- STEP: 5650/6841 -- GLOBAL_STEP: 5650
     | > loss_text_ce: 0.03015930764377117  (0.033197811276248046)
     | > loss_mel_ce: 3.438607931137085  (nan)
     | > loss: 3.4687671661376953  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1403  (0.18960735076296686)
     | > loader_time: 0.0109  (0.011883057493024173)


   --> TIME: 2025-05-17 08:10:21 -- STEP: 5700/6841 -- GLOBAL_STEP: 5700
     | > loss_text_ce: 0.034727104008197784  (0.033187272299342506)
     | > loss_mel_ce: 3.690648078918457  (nan)
     | > loss: 3.725375175476074  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2778  (0.18969873307044086)
     | > loader_time: 0.0345  (0.011881303829059272)


   --> TIME: 2025-05-17 08:10:44 -- STEP: 5750/6841 -- GLOBAL_STEP: 5750
     | > loss_text_ce: 0.032218024134635925  (0.03317995855989664)
     | > loss_mel_ce: 4.11381721496582  (nan)
     | > loss: 4.146035194396973  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3248  (0.18968322447071945)
     | > loader_time: 0.0133  (0.011881409935329277)


   --> TIME: 2025-05-17 08:11:06 -- STEP: 5800/6841 -- GLOBAL_STEP: 5800
     | > loss_text_ce: 0.02871071919798851  (0.0331709947318224)
     | > loss_mel_ce: 4.191411972045898  (nan)
     | > loss: 4.220122814178467  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1949  (0.18970899549023898)
     | > loader_time: 0.0128  (0.011876132364930783)


   --> TIME: 2025-05-17 08:11:29 -- STEP: 5850/6841 -- GLOBAL_STEP: 5850
     | > loss_text_ce: 0.03343649208545685  (0.033164459427134085)
     | > loss_mel_ce: 3.803314685821533  (nan)
     | > loss: 3.8367512226104736  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2108  (0.18971432804042496)
     | > loader_time: 0.0082  (0.01186914122002757)


   --> TIME: 2025-05-17 08:11:51 -- STEP: 5900/6841 -- GLOBAL_STEP: 5900
     | > loss_text_ce: 0.03499247133731842  (0.03315995623657509)
     | > loss_mel_ce: 3.937354564666748  (nan)
     | > loss: 3.9723470211029053  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1847  (0.18979452242285558)
     | > loader_time: 0.0095  (0.011864950697300803)


   --> TIME: 2025-05-17 08:12:14 -- STEP: 5950/6841 -- GLOBAL_STEP: 5950
     | > loss_text_ce: 0.029191216453909874  (0.033149206191927405)
     | > loss_mel_ce: 4.2182722091674805  (nan)
     | > loss: 4.247463226318359  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2726  (0.18980948840870615)
     | > loader_time: 0.0094  (0.011852594343554077)


   --> TIME: 2025-05-17 08:12:36 -- STEP: 6000/6841 -- GLOBAL_STEP: 6000
     | > loss_text_ce: 0.03176020830869675  (0.03314256871491666)
     | > loss_mel_ce: 2.673125982284546  (nan)
     | > loss: 2.7048861980438232  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1592  (0.18987409806251565)
     | > loader_time: 0.0101  (0.011851720770200098)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000========

   --> TIME: 2025-05-17 08:12:59 -- STEP: 6050/6841 -- GLOBAL_STEP: 6050
     | > loss_text_ce: 0.02988494746387005  (0.0331337866550388)
     | > loss_mel_ce: 3.5177924633026123  (nan)
     | > loss: 3.547677516937256  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1917  (0.189886901437744)
     | > loader_time: 0.014  (0.011844144813285391)


   --> TIME: 2025-05-17 08:13:22 -- STEP: 6100/6841 -- GLOBAL_STEP: 6100
     | > loss_text_ce: 0.029798252508044243  (0.03312297447477693)
     | > loss_mel_ce: 3.45151948928833  (nan)
     | > loss: 3.4813177585601807  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.131  (0.18997769750532595)
     | > loader_time: 0.0081  (0.011843033735869365)


   --> TIME: 2025-05-17 08:13:45 -- STEP: 6150/6841 -- GLOBAL_STEP: 6150
     | > loss_text_ce: 0.022588102146983147  (0.03310943317304293)
     | > loss_mel_ce: 3.2135818004608154  (nan)
     | > loss: 3.2361698150634766  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2195  (0.19002699464317296)
     | > loader_time: 0.0268  (0.011844936657727253)


   --> TIME: 2025-05-17 08:14:08 -- STEP: 6200/6841 -- GLOBAL_STEP: 6200
     | > loss_text_ce: 0.030806180089712143  (0.03309754757751376)
     | > loss_mel_ce: 3.966994285583496  (nan)
     | > loss: 3.997800350189209  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2236  (0.190101159541838)
     | > loader_time: 0.0106  (0.01184183828292355)


   --> TIME: 2025-05-17 08:14:30 -- STEP: 6250/6841 -- GLOBAL_STEP: 6250
     | > loss_text_ce: 0.0302850604057312  (0.0330927535396814)
     | > loss_mel_ce: 2.7767422199249268  (nan)
     | > loss: 2.8070273399353027  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1351  (0.19012742259979284)
     | > loader_time: 0.0208  (0.011838310127258306)


   --> TIME: 2025-05-17 08:14:52 -- STEP: 6300/6841 -- GLOBAL_STEP: 6300
     | > loss_text_ce: 0.036672379821538925  (0.033090877134116375)
     | > loss_mel_ce: 4.05825662612915  (nan)
     | > loss: 4.094929218292236  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2264  (0.1900745488726907)
     | > loader_time: 0.0126  (0.011830824405427967)


   --> TIME: 2025-05-17 08:15:14 -- STEP: 6350/6841 -- GLOBAL_STEP: 6350
     | > loss_text_ce: 0.036666467785835266  (0.03308473975932969)
     | > loss_mel_ce: 4.367794513702393  (nan)
     | > loss: 4.404460906982422  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1816  (0.19006031670908324)
     | > loader_time: 0.0139  (0.01183043979284332)


   --> TIME: 2025-05-17 08:15:37 -- STEP: 6400/6841 -- GLOBAL_STEP: 6400
     | > loss_text_ce: 0.027287911623716354  (0.033078647303336706)
     | > loss_mel_ce: 4.121399402618408  (nan)
     | > loss: 4.148687362670898  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1579  (0.19010830923914945)
     | > loader_time: 0.0086  (0.011824185140430932)


   --> TIME: 2025-05-17 08:15:59 -- STEP: 6450/6841 -- GLOBAL_STEP: 6450
     | > loss_text_ce: 0.03520914912223816  (0.03307126462603949)
     | > loss_mel_ce: nan  (nan)
     | > loss: nan  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.181  (0.19010153264038357)
     | > loader_time: 0.0089  (0.011816521615020992)


   --> TIME: 2025-05-17 08:16:23 -- STEP: 6500/6841 -- GLOBAL_STEP: 6500
     | > loss_text_ce: 0.03302181139588356  (0.03305750460005717)
     | > loss_mel_ce: 3.427633762359619  (nan)
     | > loss: 3.460655689239502  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1382  (0.19026868805518551)
     | > loader_time: 0.0082  (0.01182103168047392)


   --> TIME: 2025-05-17 08:16:46 -- STEP: 6550/6841 -- GLOBAL_STEP: 6550
     | > loss_text_ce: 0.02783062867820263  (0.03304734938102593)
     | > loss_mel_ce: 4.241848468780518  (nan)
     | > loss: 4.269679069519043  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1778  (0.19028019453733055)
     | > loader_time: 0.0105  (0.011814748858677527)


   --> TIME: 2025-05-17 08:17:08 -- STEP: 6600/6841 -- GLOBAL_STEP: 6600
     | > loss_text_ce: 0.02772217057645321  (0.03303925691595806)
     | > loss_mel_ce: 4.016603469848633  (nan)
     | > loss: 4.044325828552246  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1727  (0.19026587890856228)
     | > loader_time: 0.0096  (0.0118250462141904)

error loading /content/gdrive/MyDrive/data/dataset22050/audio001-chunk416.wav (<class 'AssertionError'>, AssertionError('UNK token found in \u200ff g it was good f\n -> [ar]f g it was good f'), <traceback object at 0x7d4d157bd240>)

   --> TIME: 2025-05-17 08:17:31 -- STEP: 6650/6841 -- GLOBAL_STEP: 6650
     | > loss_text_ce: 0.03128884732723236  (0.033025847372871994)
     | > loss_mel_ce: 3.036968231201172  (nan)
     | > loss: 3.0682570934295654  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1488  (0.19037754216588565)
     | > loader_time: 0.01  (0.011827259458097305)


   --> TIME: 2025-05-17 08:17:52 -- STEP: 6700/6841 -- GLOBAL_STEP: 6700
     | > loss_text_ce: 0.028129301965236664  (0.03301809676464144)
     | > loss_mel_ce: 3.4550302028656006  (nan)
     | > loss: 3.4831595420837402  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1336  (0.19032424428569772)
     | > loader_time: 0.008  (0.011820135828274403)


   --> TIME: 2025-05-17 08:18:14 -- STEP: 6750/6841 -- GLOBAL_STEP: 6750
     | > loss_text_ce: 0.0328197106719017  (0.0330097917925428)
     | > loss_mel_ce: 4.043896675109863  (nan)
     | > loss: 4.076716423034668  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2898  (0.1902957206655435)
     | > loader_time: 0.0195  (0.011818425355134192)


   --> TIME: 2025-05-17 08:18:37 -- STEP: 6800/6841 -- GLOBAL_STEP: 6800
     | > loss_text_ce: 0.030532648786902428  (0.032999965040396595)
     | > loss_mel_ce: 3.922536849975586  (nan)
     | > loss: 3.9530694484710693  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1752  (0.1903233380878676)
     | > loader_time: 0.0097  (0.011815330070607807)

 ! Run is removed from /content/gdrive/MyDrive/models/finetuned_egtts_v2-May-17-2025_07+27AM-0000000
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/trainer/trainer.py", line 1833, in fit
    self._fit()
  File "/usr/local/lib/python3.11/dist-packages/trainer/trainer.py", line 1789, in _fit
    self.test_run()
  File "/usr/local/lib/python3.11/dist-packages/trainer/trainer.py", line 1698, in test_run
    test_outputs = self.model.test_run(self.training_assets)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/layers/xtts/trainer/gpt_trainer.py", line 235, in test_run
    wav = self.xtts.synthesize(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 419, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 480, in full_inference
    (gpt_cond_latent, speaker_embedding) = self.get_conditioning_latents(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 357, in get_conditioning_latents
    audio = load_audio(file_path, load_sr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 73, in load_audio
    audio, lsr = torchaudio.load(audiopath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torchaudio/_backend/utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torchaudio/_backend/ffmpeg.py", line 297, in load
    return load_audio(uri, frame_offset, num_frames, normalize, channels_first, format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torchaudio/_backend/ffmpeg.py", line 88, in load_audio
    s = torchaudio.io.StreamReader(src, format, None, buffer_size)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torio/io/_streaming_media_decoder.py", line 526, in __init__
    self._be = ffmpeg_ext.StreamingMediaDecoder(os.path.normpath(src), format, option)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to open the input "/content/gdrive/MyDrive/dataset22050/audio004-chunk65.wav" (No such file or directory).
Exception raised from get_input_format_context at /__w/audio/audio/pytorch/audio/src/libtorio/ffmpeg/stream_reader/stream_reader.cpp:42 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7d4e4f76c1b6 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7d4e4f715a76 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x42034 (0x7d4d7b9d0034 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)
frame #3: torio::io::StreamingMediaDecoder::StreamingMediaDecoder(std::string const&, std::optional<std::string> const&, std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x14 (0x7d4d7b9d2a34 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)
frame #4: <unknown function> + 0x3bfee (0x7d4d652f2fee in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)
frame #5: <unknown function> + 0x330c7 (0x7d4d652ea0c7 in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)
frame #6: /usr/bin/python3() [0x55560b]
frame #7: _PyObject_MakeTpCall + 0x27c (0x52f6dc in /usr/bin/python3)
frame #8: /usr/bin/python3() [0x5853fd]
frame #9: /usr/bin/python3() [0x56e2a9]
frame #10: /usr/bin/python3() [0x52fac0]
frame #11: <unknown function> + 0xfc6b (0x7d4d7ba15c6b in /usr/local/lib/python3.11/dist-packages/torchaudio/lib/_torchaudio.so)
frame #12: _PyObject_MakeTpCall + 0x27c (0x52f6dc in /usr/bin/python3)
frame #13: _PyEval_EvalFrameDefault + 0x6bf (0x53d86f in /usr/bin/python3)
frame #14: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #15: /usr/bin/python3() [0x56df36]
frame #16: _PyObject_MakeTpCall + 0x23b (0x52f69b in /usr/bin/python3)
frame #17: _PyEval_EvalFrameDefault + 0x6bf (0x53d86f in /usr/bin/python3)
frame #18: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #19: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #20: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #21: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #22: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #23: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #24: /usr/bin/python3() [0x585b17]
frame #25: /usr/bin/python3() [0x5852fe]
frame #26: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #27: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #28: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #29: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #30: /usr/bin/python3() [0x613a24]
frame #31: PyEval_EvalCode + 0x97 (0x613087 in /usr/bin/python3)
frame #32: /usr/bin/python3() [0x62cde3]
frame #33: _PyEval_EvalFrameDefault + 0x3801 (0x5409b1 in /usr/bin/python3)
frame #34: /usr/bin/python3() [0x6288d0]
frame #35: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #36: /usr/bin/python3() [0x6288d0]
frame #37: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #38: /usr/bin/python3() [0x6288d0]
frame #39: /usr/bin/python3() [0x62ae9c]
frame #40: _PyEval_EvalFrameDefault + 0x3a8a (0x540c3a in /usr/bin/python3)
frame #41: /usr/bin/python3() [0x585b17]
frame #42: /usr/bin/python3() [0x5852fe]
frame #43: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #44: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #45: /usr/bin/python3() [0x6288d0]
frame #46: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #47: /usr/bin/python3() [0x6288d0]
frame #48: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #49: /usr/bin/python3() [0x6288d0]
frame #50: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #51: /usr/bin/python3() [0x6288d0]
frame #52: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #53: /usr/bin/python3() [0x6288d0]
frame #54: <unknown function> + 0x745f (0x7d4e9cfee45f in /usr/lib/python3.11/lib-dynload/_asyncio.cpython-311-x86_64-linux-gnu.so)
frame #55: /usr/bin/python3() [0x553a8f]
frame #56: /usr/bin/python3() [0x4d0cb0]
frame #57: /usr/bin/python3() [0x4e95e3]
frame #58: /usr/bin/python3() [0x54b2cb]
frame #59: _PyEval_EvalFrameDefault + 0x9668 (0x546818 in /usr/bin/python3)
frame #60: /usr/bin/python3() [0x613a24]
frame #61: PyEval_EvalCode + 0x97 (0x613087 in /usr/bin/python3)
frame #62: /usr/bin/python3() [0x62cde3]

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

 | > Synthesizing test sentences.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/trainer/trainer.py", line 1833, in fit
    self._fit()
  File "/usr/local/lib/python3.11/dist-packages/trainer/trainer.py", line 1789, in _fit
    self.test_run()
  File "/usr/local/lib/python3.11/dist-packages/trainer/trainer.py", line 1698, in test_run
    test_outputs = self.model.test_run(self.training_assets)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/layers/xtts/trainer/gpt_trainer.py", line 235, in test_run
    wav = self.xtts.synthesize(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 419, in synthesize
    return self.full_inference(text, speaker_wav, language, **settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 480, in full_inference
    (gpt_cond_latent, speaker_embedding) = self.get_conditioning_latents(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 357, in get_conditioning_latents
    audio = load_audio(file_path, load_sr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/TTS/tts/models/xtts.py", line 73, in load_audio
    audio, lsr = torchaudio.load(audiopath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torchaudio/_backend/utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torchaudio/_backend/ffmpeg.py", line 297, in load
    return load_audio(uri, frame_offset, num_frames, normalize, channels_first, format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torchaudio/_backend/ffmpeg.py", line 88, in load_audio
    s = torchaudio.io.StreamReader(src, format, None, buffer_size)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torio/io/_streaming_media_decoder.py", line 526, in __init__
    self._be = ffmpeg_ext.StreamingMediaDecoder(os.path.normpath(src), format, option)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to open the input "/content/gdrive/MyDrive/dataset22050/audio004-chunk65.wav" (No such file or directory).
Exception raised from get_input_format_context at /__w/audio/audio/pytorch/audio/src/libtorio/ffmpeg/stream_reader/stream_reader.cpp:42 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7d4e4f76c1b6 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7d4e4f715a76 in /usr/local/lib/python3.11/dist-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x42034 (0x7d4d7b9d0034 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)
frame #3: torio::io::StreamingMediaDecoder::StreamingMediaDecoder(std::string const&, std::optional<std::string> const&, std::optional<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > const&) + 0x14 (0x7d4d7b9d2a34 in /usr/local/lib/python3.11/dist-packages/torio/lib/libtorio_ffmpeg4.so)
frame #4: <unknown function> + 0x3bfee (0x7d4d652f2fee in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)
frame #5: <unknown function> + 0x330c7 (0x7d4d652ea0c7 in /usr/local/lib/python3.11/dist-packages/torio/lib/_torio_ffmpeg4.so)
frame #6: /usr/bin/python3() [0x55560b]
frame #7: _PyObject_MakeTpCall + 0x27c (0x52f6dc in /usr/bin/python3)
frame #8: /usr/bin/python3() [0x5853fd]
frame #9: /usr/bin/python3() [0x56e2a9]
frame #10: /usr/bin/python3() [0x52fac0]
frame #11: <unknown function> + 0xfc6b (0x7d4d7ba15c6b in /usr/local/lib/python3.11/dist-packages/torchaudio/lib/_torchaudio.so)
frame #12: _PyObject_MakeTpCall + 0x27c (0x52f6dc in /usr/bin/python3)
frame #13: _PyEval_EvalFrameDefault + 0x6bf (0x53d86f in /usr/bin/python3)
frame #14: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #15: /usr/bin/python3() [0x56df36]
frame #16: _PyObject_MakeTpCall + 0x23b (0x52f69b in /usr/bin/python3)
frame #17: _PyEval_EvalFrameDefault + 0x6bf (0x53d86f in /usr/bin/python3)
frame #18: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #19: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #20: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #21: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #22: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #23: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #24: /usr/bin/python3() [0x585b17]
frame #25: /usr/bin/python3() [0x5852fe]
frame #26: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #27: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #28: _PyFunction_Vectorcall + 0x173 (0x566243 in /usr/bin/python3)
frame #29: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #30: /usr/bin/python3() [0x613a24]
frame #31: PyEval_EvalCode + 0x97 (0x613087 in /usr/bin/python3)
frame #32: /usr/bin/python3() [0x62cde3]
frame #33: _PyEval_EvalFrameDefault + 0x3801 (0x5409b1 in /usr/bin/python3)
frame #34: /usr/bin/python3() [0x6288d0]
frame #35: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #36: /usr/bin/python3() [0x6288d0]
frame #37: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #38: /usr/bin/python3() [0x6288d0]
frame #39: /usr/bin/python3() [0x62ae9c]
frame #40: _PyEval_EvalFrameDefault + 0x3a8a (0x540c3a in /usr/bin/python3)
frame #41: /usr/bin/python3() [0x585b17]
frame #42: /usr/bin/python3() [0x5852fe]
frame #43: PyObject_Call + 0xf4 (0x570784 in /usr/bin/python3)
frame #44: _PyEval_EvalFrameDefault + 0x4aab (0x541c5b in /usr/bin/python3)
frame #45: /usr/bin/python3() [0x6288d0]
frame #46: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #47: /usr/bin/python3() [0x6288d0]
frame #48: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #49: /usr/bin/python3() [0x6288d0]
frame #50: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #51: /usr/bin/python3() [0x6288d0]
frame #52: _PyEval_EvalFrameDefault + 0x3444 (0x5405f4 in /usr/bin/python3)
frame #53: /usr/bin/python3() [0x6288d0]
frame #54: <unknown function> + 0x745f (0x7d4e9cfee45f in /usr/lib/python3.11/lib-dynload/_asyncio.cpython-311-x86_64-linux-gnu.so)
frame #55: /usr/bin/python3() [0x553a8f]
frame #56: /usr/bin/python3() [0x4d0cb0]
frame #57: /usr/bin/python3() [0x4e95e3]
frame #58: /usr/bin/python3() [0x54b2cb]
frame #59: _PyEval_EvalFrameDefault + 0x9668 (0x546818 in /usr/bin/python3)
frame #60: /usr/bin/python3() [0x613a24]
frame #61: PyEval_EvalCode + 0x97 (0x613087 in /usr/bin/python3)
frame #62: /usr/bin/python3() [0x62cde3]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-b6cd7ba69c0e>", line 1, in <cell line: 0>
    trainer.fit()
  File "/usr/local/lib/python3.11/dist-packages/trainer/trainer.py", line 1862, in fit
    sys.exit(1)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/exit_hooks.py", line 36, in exit
    self._orig_exit(orig_code)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 1739, in getinnerframes
    traceback_info = getframeinfo(tb, context)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/inspect.py", line 1671, in getframeinfo
    lineno = frame.f_lineno
             ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'f_lineno'

TypeError: object of type 'NoneType' has no len()