# Install packages

In [ ]:
# Step 2: Delete all .jpg files in My Drive
import os
import glob

# Path to My Drive
mydrive_path = '/content/gdrive/MyDrive'

# Recursively find all .jpg files
jpg_files = glob.glob(os.path.join(mydrive_path, '**/*.jpg'), recursive=True)

print(f"Found {len(jpg_files)} JPG files.")

# Delete each file
for file_path in jpg_files:
    try:
        os.remove(file_path)
        print(f"Deleted: {file_path}")
    except Exception as e:
        print(f"Error deleting {file_path}: {e}")

Found 2276 JPG files.
Deleted: /content/gdrive/MyDrive/26cV4_2YRG8FlDCSP-DruA.jpg
Deleted: /content/gdrive/MyDrive/4M4fUQQWV0sklAf4ntUe5Q.jpg
Deleted: /content/gdrive/MyDrive/3r1bF3zTxw0RxJi4rNEfXA.jpg
Deleted: /content/gdrive/MyDrive/23XmaoV5DjMUzfB3SzPUFg.jpg
Deleted: /content/gdrive/MyDrive/3sQQEQLp5RZH1__X10Tk_A.jpg
Deleted: /content/gdrive/MyDrive/BOq385LCdbRfy2cxenrDjQ.jpg
Deleted: /content/gdrive/MyDrive/8-gIRjawRHMTsthYW_VNgw.jpg
Deleted: /content/gdrive/MyDrive/8lkcFc59-2RgSU203mlYEQ.jpg
Deleted: /content/gdrive/MyDrive/AEaVLcuIAvLzYGyoPPdqeA.jpg
Deleted: /content/gdrive/MyDrive/8lajtqnWhhQWqOe10TjkMQ.jpg
Deleted: /content/gdrive/MyDrive/AO_4E4KNEZMFVQ3shYKgoA.jpg
Deleted: /content/gdrive/MyDrive/-Ae9jTBaJa6ZIG0_a1gKTw.jpg
Deleted: /content/gdrive/MyDrive/DIfP3Xu-Ti_23kwjDTWfZg.jpg
Deleted: /content/gdrive/MyDrive/E1R8H0jgIra1gt96wt0N8A.jpg
Deleted: /content/gdrive/MyDrive/9ZYrvatwApKvERkeH6Q7_A.jpg
Deleted: /content/gdrive/MyDrive/32eEAOHpvNLMBZIJ2ksHAg.jpg
Deleted: /content/gdrive/MyDrive/2cr8OB_E63mRn3oThfjO1Q.jpg
Deleted: /content/gdrive/MyDrive/53-TnzoH9sgBc2W4hBRJGw.jpg
Deleted: /content/gdrive/MyDrive/3PPsZLcDWI_RLNYvaAtEdw.jpg
Deleted: /content/gdrive/MyDrive/8elMC15QdDxkyjfUMDF_dw.jpg
Deleted: /content/gdrive/MyDrive/B6yjHwXdb_NP0r83PJWpCA.jpg
Deleted: /content/gdrive/MyDrive/8I5MZLpJHM3gA2MReCtZYQ.jpg
Deleted: /content/gdrive/MyDrive/1YjCK0SG4qhv8KY0-nuRbw.jpg
Deleted: /content/gdrive/MyDrive/698ONp0pL3kQoIa0-IA5tg.jpg
Deleted: /content/gdrive/MyDrive/D6bKRgm_K03nHd9vZ7h0wQ.jpg
Deleted: /content/gdrive/MyDrive/9o6fmrIR7HkLaADbs0f9sQ.jpg
Deleted: /content/gdrive/MyDrive/2KQMkLhh2Z56pk2AXSn89A.jpg
Deleted: /content/gdrive/MyDrive/21oInImRbkimylaXajOadw.jpg
Deleted: /content/gdrive/MyDrive/CKFBXVII0dm-5wMbqP-6Yw.jpg
Deleted: /content/gdrive/MyDrive/B49hEjkeXtRNBFg2nj95TQ.jpg
Deleted: /content/gdrive/MyDrive/4Hdc67iSICfaNYtGVaRGOw.jpg
Deleted: /content/gdrive/MyDrive/1UDwLAhDBDzTJKRhE-CFAQ.jpg
Deleted: /content/gdrive/MyDrive/6i3E1ggNBTC2E-HPGM8HXw.jpg
Deleted: /content/gdrive/MyDrive/6m75SxGyH1KPKOek7LzetQ.jpg
Deleted: /content/gdrive/MyDrive/0eQAT2Iei3INN8SxMOJGUw.jpg
Deleted: /content/gdrive/MyDrive/Dc7etfidn5GIuZeCAzl_qg.jpg
Deleted: /content/gdrive/MyDrive/FJc5z7ciwMJfhDxFvZ7UeQ.jpg
Deleted: /content/gdrive/MyDrive/BUrOHLwF-n-Ig45a_1s12Q.jpg
Deleted: /content/gdrive/MyDrive/9-Gf9JQUG4xCoHUGOpov1w.jpg
Deleted: /content/gdrive/MyDrive/B5tPp3MPceVH1RgKnvRxkw.jpg
Deleted: /content/gdrive/MyDrive/1Y22PXoaKrBh8manH5Lmbw.jpg
Deleted: /content/gdrive/MyDrive/678ZdQYqKCGJGzFb803wdw.jpg
Deleted: /content/gdrive/MyDrive/Aaw3h58QajIYPatuNDRHFw.jpg
Deleted: /content/gdrive/MyDrive/9iuET1FDzFUiMTF8HczxcA.jpg
Deleted: /content/gdrive/MyDrive/9xQjlayDVuJCQDvK1D7IHA.jpg
Deleted: /content/gdrive/MyDrive/3kv5bGiH20dkq9beX4LxXg.jpg
Deleted: /content/gdrive/MyDrive/BkTde1IdiE3tmnU1og_MdA.jpg
Deleted: /content/gdrive/MyDrive/Dh-KO6qP3w7ONgtdE6Znkw.jpg
Deleted: /content/gdrive/MyDrive/BuNbDkBVMntr2eo_ZqUO3g.jpg
Deleted: /content/gdrive/MyDrive/8DhXZYYUVsskrW36cZ65vQ.jpg
Deleted: /content/gdrive/MyDrive/EcIb8cdwAuHLhpLm2GvtTw.jpg
Deleted: /content/gdrive/MyDrive/FGAikUy7T_U5CZbcmiM7XQ.jpg
Deleted: /content/gdrive/MyDrive/2yNmHGGCqRaV2nmLD9R7NQ.jpg
Deleted: /content/gdrive/MyDrive/0VZpPpnAb4F5JwCqL8sE5A.jpg
Deleted: /content/gdrive/MyDrive/AFD3LzVb_95qSXnfPNjUMw.jpg
Deleted: /content/gdrive/MyDrive/E70FQb9ED6_h2csgnwgjkg.jpg
Deleted: /content/gdrive/MyDrive/6l374X0E4ro8lQ1_wO2t7Q.jpg
Deleted: /content/gdrive/MyDrive/-La2XLCsqbAJz05JCLflSg.jpg
Deleted: /content/gdrive/MyDrive/8hhpKw71ALui3Sfsh3TiGA.jpg
Deleted: /content/gdrive/MyDrive/5UCYB4P7whakqCvvr7qFLg.jpg
Deleted: /content/gdrive/MyDrive/61Ptilwk11hi8E8MIdahWg.jpg
Deleted: /content/gdrive/MyDrive/AJBBuFGetKRf2cbehxLelQ.jpg
Deleted: /content/gdrive/MyDrive/C2B5jWSWEmV_pMi_Sjk_Mg.jpg
Deleted: /content/gdrive/MyDrive/3GRfiCoy9vDUs2hDJMp7iQ.jpg
Deleted: /content/gdrive/MyDrive/39bQJF94TrvebfWApuZujA.jpg
Deleted: /content/gdrive/MyDrive/Eehe3sZvSjWKXCT2YnZrYA.jpg
Deleted: /content/gdrive/MyDrive/6zkLzAGofKcb1tnKIyF6wQ.jpg
Deleted: /content/gdrive/MyDrive/4xtDsW5azDgoDRyT6GY3Nw.jpg
Deleted: /content/gdrive/MyDrive/81_2CZ6tu74rKa17IylcyA.jpg
Deleted: /content/gdrive/MyDrive/5YqLVBCtOtA8ieT2ncQPiw.jpg
Deleted: /content/gdrive/MyDrive/0wS8ulXqyM5cALgZnOYSVw.jpg
Deleted: /content/gdrive/MyDrive/-hE6JisEaq_RlW7YvbZ1bQ.jpg
Deleted: /content/gdrive/MyDrive/2S5RJ650snwQ_QjKZfd5FA.jpg
Deleted: /content/gdrive/MyDrive/8h8cQSIojWh0Jb_YxeNFJw.jpg
Deleted: /content/gdrive/MyDrive/EtobqglMr0IjgYL1zdS3oQ.jpg
Deleted: /content/gdrive/MyDrive/5GGAcRS782S64I5amICEbA.jpg
Deleted: /content/gdrive/MyDrive/1RJHXae9MANqDri9zCjCQA.jpg
Deleted: /content/gdrive/MyDrive/FEKI524qRVTmyUl3PxkygQ.jpg
Deleted: /content/gdrive/MyDrive/AzBROGh_Os8wLgq7UXUbAA.jpg
Deleted: /content/gdrive/MyDrive/2pK7CmrWVmXT4yAd17SPCg.jpg
Deleted: /content/gdrive/MyDrive/-e5ywi8g8m7y8CWy5r5l-w.jpg
Deleted: /content/gdrive/MyDrive/2w2KTS0mPibZ7HFzMBLE9g.jpg
Deleted: /content/gdrive/MyDrive/3OdfhZsEMjBBGWYZCd0lJg.jpg
Deleted: /content/gdrive/MyDrive/2_I9ts05iVS1lQPbraxA9A.jpg
Deleted: /content/gdrive/MyDrive/DesgnFqic1D6fkv6ziKopQ.jpg
Deleted: /content/gdrive/MyDrive/3oN99zip6L-TXjxLPAK9aA.jpg
Deleted: /content/gdrive/MyDrive/DF4eRJfIYeKGfpTIu80HzA.jpg
Deleted: /content/gdrive/MyDrive/51RM_N9F5gGELxTCClEtOQ.jpg
Deleted: /content/gdrive/MyDrive/5d9DROI6I3uF7JWIIrYeOQ.jpg
Deleted: /content/gdrive/MyDrive/38JVJ7r_jAV-Apm5TIS3Wg.jpg
Deleted: /content/gdrive/MyDrive/D_8YZSV07ha7n2kS0aRIuA.jpg
Deleted: /content/gdrive/MyDrive/2hVkch2_vnjRn7GCbqWL6g.jpg
Deleted: /content/gdrive/MyDrive/12B49eIm7PfZD_AaSHor-w.jpg
Deleted: /content/gdrive/MyDrive/9-jqPM82z7z9W0kvv0CwZg.jpg
Deleted: /content/gdrive/MyDrive/5a1XdkWR-voCLuI5OM2DkQ.jpg
Deleted: /content/gdrive/MyDrive/A-BA6O5BBG7AsciMn1N56A.jpg
Deleted: /content/gdrive/MyDrive/74lm3VQlEl_teyikqk0mRA.jpg
Deleted: /content/gdrive/MyDrive/5p4IIq1jatiu2esTcZdXiQ.jpg
Deleted: /content/gdrive/MyDrive/EMTfS2keedTsNVX_0QlhSA.jpg
Deleted: /content/gdrive/MyDrive/0RR6iWx9tvLcvolhOomcxg.jpg
Deleted: /content/gdrive/MyDrive/E9-bQ0W-f3wAC9b80vZuTA.jpg
Deleted: /content/gdrive/MyDrive/CkhdQIMsRksLAZ9tXl3UdA.jpg
Deleted: /content/gdrive/MyDrive/CRu5YdkhOYeBhLl2WotOnw.jpg
Deleted: /content/gdrive/MyDrive/444TemJ9wVTkl1Hr0OX2DQ.jpg
Deleted: /content/gdrive/MyDrive/FDXfbkjQQFlS0MxptzzW5w.jpg
Deleted: /content/gdrive/MyDrive/Ew4B0U5DSlzhLg7As_TH9g.jpg
Deleted: /content/gdrive/MyDrive/BsuY8YLFa2cCl28DqyKMqg.jpg
Deleted: /content/gdrive/MyDrive/3-k1We9T9EJQInYoeqGvvw.jpg
Deleted: /content/gdrive/MyDrive/2rabE9KKM-ZU41dlvvU4Hw.jpg
Deleted: /content/gdrive/MyDrive/1jm1jOmJ2xExAcpLDjQ7OQ.jpg
Deleted: /content/gdrive/MyDrive/FCoMhOJU9WPThN8b0d1vwQ.jpg
Deleted: /content/gdrive/MyDrive/5hpAHzgz5hoOQiL1Nm1Cwg.jpg
Deleted: /content/gdrive/MyDrive/B8d1wH9vuV7J68kaTXUNNQ.jpg
Deleted: /content/gdrive/MyDrive/5b62PYfZBE_xOJ1eUrK_jg.jpg
Deleted: /content/gdrive/MyDrive/2vlh6fMgfwf3DuGYWLf43Q.jpg
Deleted: /content/gdrive/MyDrive/2w53hOPKQQ21vHeKNsZBlw.jpg
Deleted: /content/gdrive/MyDrive/9wNBNi9eO8zsBVLUS11wzg.jpg
Deleted: /content/gdrive/MyDrive/83pK953wDzci2MjepxJUKQ.jpg
Deleted: /content/gdrive/MyDrive/5eptXkXM3PZBZDaZqP7m_A.jpg
Deleted: /content/gdrive/MyDrive/0ex5sxSYJs9ymscQOa0QNA.jpg
Deleted: /content/gdrive/MyDrive/DVt_K0tglDGM7hjbGNpCrg.jpg
Deleted: /content/gdrive/MyDrive/7qF3bNFyWLjGJzl5SxzJ9g.jpg
Deleted: /content/gdrive/MyDrive/CyGZYdtCXHAUIF_bvlEk5w.jpg
Deleted: /content/gdrive/MyDrive/3DzRQi6eFW3zaMc8pJKgkQ.jpg
Deleted: /content/gdrive/MyDrive/8QpYBtpKkc-RRyCT4KY2_Q.jpg
Deleted: /content/gdrive/MyDrive/-jrOR8VoL7405tThwHSneQ.jpg
Deleted: /content/gdrive/MyDrive/7wWBjAwc-ZTyyXKusBjbWA.jpg
Deleted: /content/gdrive/MyDrive/3_Xvx1M1hA16iw9i9z7duA.jpg
Deleted: /content/gdrive/MyDrive/1fvQ750eF3tjqmTf_aH4UA.jpg
Deleted: /content/gdrive/MyDrive/4muaoPqXAwi8SOvwV-Jf6g.jpg
Deleted: /content/gdrive/MyDrive/0icaMxV8_mJ8sb892WlhXA.jpg
Deleted: /content/gdrive/MyDrive/9AGo4Bqzz4Dv6OQ-YiqPIw.jpg
Deleted: /content/gdrive/MyDrive/9_eWNxN97fsZFxrNKfLQ8w.jpg
Deleted: /content/gdrive/MyDrive/Ef-0ExiNDffSm-I-smeeOQ.jpg
Deleted: /content/gdrive/MyDrive/0OIYyKLSMLl32IVsPBbBqA.jpg
Deleted: /content/gdrive/MyDrive/16GbzwFn1zVnp_uSX9z1jA.jpg
Deleted: /content/gdrive/MyDrive/F1CgafYoE2jK-TP_xCzhbg.jpg
Deleted: /content/gdrive/MyDrive/61fx41YIe9DNfASzq5A0aQ.jpg
Deleted: /content/gdrive/MyDrive/42_s6bc6KPMg--ovX2T4hQ.jpg
Deleted: /content/gdrive/MyDrive/-FtqiD0037yomyFmsem25w.jpg
Deleted: /content/gdrive/MyDrive/B46Yeq1Njjo2EoiQF7WfSw.jpg
Deleted: /content/gdrive/MyDrive/6e1gn70hj3JhKHHgkPmDow.jpg
Deleted: /content/gdrive/MyDrive/-v-fBBFa9D69F_DaV-z1Tg.jpg
Deleted: /content/gdrive/MyDrive/24Bp4v4-mlvwroqrX56RuA.jpg
Deleted: /content/gdrive/MyDrive/5fgETlKRXKwpHennRKAyjA.jpg
Deleted: /content/gdrive/MyDrive/Ar0l9O0i7u9MpNz8hu3KXQ.jpg
Deleted: /content/gdrive/MyDrive/8GiWW_D0kxgLnMpN5dE_7Q.jpg
Deleted: /content/gdrive/MyDrive/Ciktw3i-ar5zee06SKJElQ.jpg
Deleted: /content/gdrive/MyDrive/AOKVMoyhpE6wvE58TocWNg.jpg
Deleted: /content/gdrive/MyDrive/3Yr7sYFO6Lx6DVDamgt1sg.jpg
Deleted: /content/gdrive/MyDrive/5IqAUirN1ZqVTTtPDrjy9w.jpg
Deleted: /content/gdrive/MyDrive/0RnxUBqLV-4MfR1kW2oPcQ.jpg
Deleted: /content/gdrive/MyDrive/4A4hF8Pvnat-zey_OYychg.jpg
Deleted: /content/gdrive/MyDrive/9IbLLduq_DJuwJD_01EiBQ.jpg
Deleted: /content/gdrive/MyDrive/0ErcYqUJdsDddTvMplWgEw.jpg
Deleted: /content/gdrive/MyDrive/3Kg70UKtLQbI68k-Pkw4tQ.jpg
Deleted: /content/gdrive/MyDrive/9Yl-ue315oprmPG0dUpxng.jpg
Deleted: /content/gdrive/MyDrive/DJC-67MBS1E8xT4OtzL4Qw.jpg
Deleted: /content/gdrive/MyDrive/CXjSVsdIRPoi8lxXyjNoSA.jpg
Deleted: /content/gdrive/MyDrive/5qjUMIbaeGkdCwWLRSBhNA.jpg
Deleted: /content/gdrive/MyDrive/-PGWvPCItNkYR3f90utJGg.jpg
Deleted: /content/gdrive/MyDrive/4eBz4z6YAV4rBMr1owju3A.jpg
Deleted: /content/gdrive/MyDrive/94WIiQAWj6XvwUbHtP1oxQ.jpg
Deleted: /content/gdrive/MyDrive/BVjPDDir1B8VoNZ3EgHkAA.jpg
Deleted: /content/gdrive/MyDrive/1pm1OpHm7j5SW84p_RcV7A.jpg
Deleted: /content/gdrive/MyDrive/8ghIwNw7Jfi9ERIYRCGxzg.jpg
Deleted: /content/gdrive/MyDrive/ATe-yWPuIMaz4bDEU1BHPQ.jpg
Deleted: /content/gdrive/MyDrive/3gCgVvC71bPTb4KjTzHKmQ.jpg
Deleted: /content/gdrive/MyDrive/0FLsXsliWqAZeYB-YGnTCA.jpg
Deleted: /content/gdrive/MyDrive/5X_nZuTXZlLoh9VXWjzVqA.jpg
Deleted: /content/gdrive/MyDrive/9b-u3W0DPhxt68sfXGt1Pg.jpg
Deleted: /content/gdrive/MyDrive/BeyMXSOua9W8ShhlWDgDxQ.jpg
Deleted: /content/gdrive/MyDrive/8zozZmw0s0T_a7igXFKIWg.jpg
Deleted: /content/gdrive/MyDrive/0payhcBxl43WlJSdnrbOww.jpg
Deleted: /content/gdrive/MyDrive/54_7Yd8MSLVWOPaHXwpmOA.jpg
Deleted: /content/gdrive/MyDrive/E_mcxuhVWuO18QaBFxJzcw.jpg
Deleted: /content/gdrive/MyDrive/-o4-dLzOXoOSOdR4P9ZGtA.jpg
Deleted: /content/gdrive/MyDrive/9OkqCzUZbA99K3_E_ysJqQ.jpg
Deleted: /content/gdrive/MyDrive/D9eKuGEMAfS10_NPNFU0Gw.jpg
Deleted: /content/gdrive/MyDrive/AXFPQeF7mmqbux7S95Kw0Q.jpg
Deleted: /content/gdrive/MyDrive/0SPjG7loAzo5lVMCktr8PQ.jpg
Deleted: /content/gdrive/MyDrive/8sqXBqMsJbI9P0ryimj2jw.jpg
Deleted: /content/gdrive/MyDrive/FJkEhvPN_CxR-yEUHGhwJg.jpg
Deleted: /content/gdrive/MyDrive/2OeI10NxZQA1s6Krg4sNsA.jpg
Deleted: /content/gdrive/MyDrive/0MB6iPc35qxiz5rhFDHU2g.jpg
Deleted: /content/gdrive/MyDrive/6-JN82oUGsmjWgd4GufU8Q.jpg
Deleted: /content/gdrive/MyDrive/5ro8Ayuf9Qn8fQVfy3nGBA.jpg
Deleted: /content/gdrive/MyDrive/3VO01uj77j4vAZeSSICz3w.jpg
Deleted: /content/gdrive/MyDrive/4UzISn7eT0IVk2SvyvunAQ.jpg
Deleted: /content/gdrive/MyDrive/9u2ecTxDTdiTLWRxahZ8PA.jpg
Deleted: /content/gdrive/MyDrive/CPnRClaaPK6pTB8yUvDwIg.jpg
Deleted: /content/gdrive/MyDrive/EHLNvLcSe3SbQmegsU0wmg.jpg
Deleted: /content/gdrive/MyDrive/AXCJZb0hmMJXH63kHBrOdw.jpg
Deleted: /content/gdrive/MyDrive/15stPTcTpSOucv7dSmkuZQ.jpg
Deleted: /content/gdrive/MyDrive/6iwfDd7B8FdxtSQnW0t7zQ.jpg
Deleted: /content/gdrive/MyDrive/3iccLjJIeZ8DQj6JyBYISg.jpg
Deleted: /content/gdrive/MyDrive/42tigCsglAnf2zWHKU_PQQ.jpg
Deleted: /content/gdrive/MyDrive/B2niLOMrpy8AgXHzJoMMpA.jpg
Deleted: /content/gdrive/MyDrive/3Sdd2AavEmR9IT1yaO9vPg.jpg
Deleted: /content/gdrive/MyDrive/CrCf88hb1xuUCvwZSsb4Ww.jpg
Deleted: /content/gdrive/MyDrive/4NMKmL-b_-LoclLDwhpB9w.jpg
Deleted: /content/gdrive/MyDrive/-2H8gOJp_LEvus2Y6pCIOA.jpg
Deleted: /content/gdrive/MyDrive/3kcqZK7_FBZnAhq-lE4U4Q.jpg
Deleted: /content/gdrive/MyDrive/3aIjBtppymy8pGEoNFPlQw.jpg
Deleted: /content/gdrive/MyDrive/-vZmlbSsrt2EBaw4ZQ2GfQ.jpg
Deleted: /content/gdrive/MyDrive/0agTvBdoGVCc1mQyQy2ohw.jpg
Deleted: /content/gdrive/MyDrive/C5liPPZ2G763ho1A8zivcw.jpg
Deleted: /content/gdrive/MyDrive/FA6WExqW5qbWUOhqTVm55Q.jpg
Deleted: /content/gdrive/MyDrive/-pknlH0DMwa03Y-g2-tcjA.jpg
Deleted: /content/gdrive/MyDrive/ExLHhgquNytwtU5vbFPGfQ.jpg
Deleted: /content/gdrive/MyDrive/1A7QdPmmlXiILFomp2cIrw.jpg
Deleted: /content/gdrive/MyDrive/025hM-2yEUkg_sNVNSCsQQ.jpg
Deleted: /content/gdrive/MyDrive/CzAPaqBG3tgD7MlRgwpnrg.jpg
Deleted: /content/gdrive/MyDrive/5yXaOF9Uf0wpeBsQUziVOw.jpg
Deleted: /content/gdrive/MyDrive/7H4_34fB7SszzHBTRP53yA.jpg
Deleted: /content/gdrive/MyDrive/4b_djKcxmHBO3acuE0pRww.jpg
Deleted: /content/gdrive/MyDrive/-8LfeDEADhyLcKBvhRWrCw.jpg
Deleted: /content/gdrive/MyDrive/7JCYDni8fKg-z0UVxvOysg.jpg
Deleted: /content/gdrive/MyDrive/FLJaprNEVZLecT8B3UnLoQ.jpg
Deleted: /content/gdrive/MyDrive/1X803WHlIxk5Hu5pHM_XIQ.jpg
Deleted: /content/gdrive/MyDrive/4INDoY2LY7dGYBP4jdhN-g.jpg
Deleted: /content/gdrive/MyDrive/3hdkzpP7xvJ5T0doN8GSNg.jpg
Deleted: /content/gdrive/MyDrive/0ICmP3lYJ-VyHKdkGRV-DA.jpg
Deleted: /content/gdrive/MyDrive/F1rqUxU2_ZNBkwggl0eolA.jpg
Deleted: /content/gdrive/MyDrive/BnA8g8oolcjnJkwuOP-sJw.jpg
Deleted: /content/gdrive/MyDrive/8j0nbzofl8O_2PxeS3kevQ.jpg
Deleted: /content/gdrive/MyDrive/2ZvIEPzdbY1OE31dCOXnYQ.jpg
Deleted: /content/gdrive/MyDrive/Avv43l6bU2HTEVbBsgathA.jpg
Deleted: /content/gdrive/MyDrive/382xH63TSC82w2TY-JlikA.jpg
Deleted: /content/gdrive/MyDrive/EE2v1Yn2YIY2Gi7w3ekcsg.jpg
Deleted: /content/gdrive/MyDrive/2IozVYfLo74uMDrBVkt1_w.jpg
Deleted: /content/gdrive/MyDrive/DsoVFVudGT9Z-scWLtwcnQ.jpg
Deleted: /content/gdrive/MyDrive/38jtMsr4GW3DCAhB55EUTg.jpg
Deleted: /content/gdrive/MyDrive/0rujw3qZ0gFaipyhAVs6eQ.jpg
Deleted: /content/gdrive/MyDrive/C3ZCBfbFRpxWH6gEhKfRPw.jpg
Deleted: /content/gdrive/MyDrive/FIQyjAB2JX_hEEMbmT_oNg.jpg
Deleted: /content/gdrive/MyDrive/7n2vCMgfSgRCPIM1pU0Z2w.jpg
Deleted: /content/gdrive/MyDrive/7dDjWst_gHkoNV-CuJl9mA.jpg
Deleted: /content/gdrive/MyDrive/4JbfYGlqClgtyM4-kW89KA.jpg
Deleted: /content/gdrive/MyDrive/-pVSrIxeKECPZ_q7rQ9m1g.jpg
Deleted: /content/gdrive/MyDrive/1WFwBQG8-tm3vWPhLndlxw.jpg
Deleted: /content/gdrive/MyDrive/7UN79GaUQkCcbgerXSMqZQ.jpg
Deleted: /content/gdrive/MyDrive/5oFaVvMiVrece2YDzeA2Sg.jpg
Deleted: /content/gdrive/MyDrive/50x-R_qN8J9h8b71yoM_vA.jpg
Deleted: /content/gdrive/MyDrive/4I1POpErpuzXkgPk0RQSdQ.jpg
Deleted: /content/gdrive/MyDrive/4Y5U2biFo4uWNWJdKOMxDg.jpg
Deleted: /content/gdrive/MyDrive/8FtpnEsUTQmu6QLpS2vNjA.jpg
Deleted: /content/gdrive/MyDrive/0bTLLUcpIknkA1K9kMOo7Q.jpg
Deleted: /content/gdrive/MyDrive/4D8o1rEfLcLuH5qa5dyU9w.jpg
Deleted: /content/gdrive/MyDrive/8LEypMb0JDD1zz-r9MVslg.jpg
Deleted: /content/gdrive/MyDrive/9WQWX4mNI3-zDyesPDTaIg.jpg
Deleted: /content/gdrive/MyDrive/C_YqjXQLBF30IDH_hl5kew.jpg
Deleted: /content/gdrive/MyDrive/-8d4l3xicTRHZLze9Wuc4g.jpg
Deleted: /content/gdrive/MyDrive/8GnV6FKUAythKwjAIkQgjA.jpg
Deleted: /content/gdrive/MyDrive/3obBBYuP4fYqKOh_fnekgQ.jpg
Deleted: /content/gdrive/MyDrive/3oODfp3nSdrVumFx9Pi-Rw.jpg
Deleted: /content/gdrive/MyDrive/6VonDZ2pfgQ16eRLu-O66A.jpg
Deleted: /content/gdrive/MyDrive/18UTnNtyNaTlJ7kVcqs1vw.jpg
Deleted: /content/gdrive/MyDrive/-uy7fxqZa_l1SIaMr-TJCA.jpg
Deleted: /content/gdrive/MyDrive/1cWSOsWhN5C3yfM1i6vVTg.jpg
Deleted: /content/gdrive/MyDrive/Bes0bZajfc_PpyDu4v1Hzw.jpg
Deleted: /content/gdrive/MyDrive/Ef_c9-VSIoFG9YnsN9da0g.jpg
Deleted: /content/gdrive/MyDrive/BfDAEEMok81k-PxcgQX5EQ.jpg
Deleted: /content/gdrive/MyDrive/5yuwU83HfOKkq1Dq5CRLlA.jpg
Deleted: /content/gdrive/MyDrive/6DvaUiyC1DbAnxIhY_MQyQ.jpg
Deleted: /content/gdrive/MyDrive/6cnA1Bv7AyIjAJwJMu6yqw.jpg
Deleted: /content/gdrive/MyDrive/2aRJss8N0OFe1B2U3vWOJA.jpg
Deleted: /content/gdrive/MyDrive/-DHEVkd576GS3gT-ucMiig.jpg
Deleted: /content/gdrive/MyDrive/6p7vJ6Xf0oozl6W3tmvhlg.jpg
Deleted: /content/gdrive/MyDrive/AsbwGPdF6qt5I8aNfL7gyw.jpg
Deleted: /content/gdrive/MyDrive/E2X0KKi9ZQQ18tNwuwrCWQ.jpg
Deleted: /content/gdrive/MyDrive/8B8cjHZgmECFbK342k0I0w.jpg
Deleted: /content/gdrive/MyDrive/1g8ZyAHMYwp7zskyrtqM4w.jpg
Deleted: /content/gdrive/MyDrive/1hx9lUyRA9rtqEBWW7dAQQ.jpg
Deleted: /content/gdrive/MyDrive/3XHCQhVjMASzFi0K-HdX6A.jpg
Deleted: /content/gdrive/MyDrive/CvdJSq6upJe7AKJHa2EbRw.jpg
Deleted: /content/gdrive/MyDrive/1u25o7lHHNhu8peoren_-Q.jpg
Deleted: /content/gdrive/MyDrive/15XcuRt7cv3X9p8Z-rIa_g.jpg
Deleted: /content/gdrive/MyDrive/15kwLK0TFGJE_3LB4GHglQ.jpg
Deleted: /content/gdrive/MyDrive/4_jKZfOz7FkXMJuaaK_RFQ.jpg
Deleted: /content/gdrive/MyDrive/FCxkPDCkcorJwaz2FnopFw.jpg
Deleted: /content/gdrive/MyDrive/E8DzqvpLs5ZpXvAlmc4pLw.jpg
Deleted: /content/gdrive/MyDrive/DD70VJxtcbunuvXzUIP4bQ.jpg
Deleted: /content/gdrive/MyDrive/E9YV4mZLk7a1AcZkorl1Dg.jpg
Deleted: /content/gdrive/MyDrive/-lsv9582Wjc5TfvD1HO0PQ.jpg
Deleted: /content/gdrive/MyDrive/0tAq2z-y2WgMvq1W1In9Sg.jpg
Deleted: /content/gdrive/MyDrive/7aop7FNNzT3iWPN9AtAQAw.jpg
Deleted: /content/gdrive/MyDrive/-DsdPlUt6iih-L9Gy35IMg.jpg
Deleted: /content/gdrive/MyDrive/24i0owrf57zvRPLu7UKh5g.jpg
Deleted: /content/gdrive/MyDrive/9OWvQ7Gr0geKuYZbnfYxpg.jpg
Deleted: /content/gdrive/MyDrive/42An0WlCDI7uMvTamNJsVg.jpg
Deleted: /content/gdrive/MyDrive/Ah2vbOU0W0UVWywXFYo1YQ.jpg
Deleted: /content/gdrive/MyDrive/3RYJup1xVWPIMOk0TmvOyg.jpg
Deleted: /content/gdrive/MyDrive/D0TJeOa_pMp5RRJPqh75cQ.jpg
Deleted: /content/gdrive/MyDrive/53QQSm8F7c3QQhJaLPIc1A.jpg
Deleted: /content/gdrive/MyDrive/9P7AwWWi9OswAJTS_08gbw.jpg
Deleted: /content/gdrive/MyDrive/0RbE-oFyNrCzpIJTcKyoQw.jpg
Deleted: /content/gdrive/MyDrive/AqYKEC-Gluoo64Aals9r8Q.jpg
Deleted: /content/gdrive/MyDrive/5QMUu8Viw608-_XuzCw9Wg.jpg
Deleted: /content/gdrive/MyDrive/6RyBQgl2JLmdTmBvOZLo9g.jpg
Deleted: /content/gdrive/MyDrive/AZ_NBatdcbWWH6ePzj0cuw.jpg
Deleted: /content/gdrive/MyDrive/5WJmc3Sr2tm9Yt7SeB6lOg.jpg
Deleted: /content/gdrive/MyDrive/3IgDxpZltEd-WKPPZgmspA.jpg
Deleted: /content/gdrive/MyDrive/7o8eJ1h-tpOG3AFM9U7Ufw.jpg
Deleted: /content/gdrive/MyDrive/BfSOVKCEDt0Te8a23DyzFQ.jpg
Deleted: /content/gdrive/MyDrive/2zyf3N7fhaotUCu9AafssQ.jpg
Deleted: /content/gdrive/MyDrive/9yez5EB8br87aEgnR_RHqg.jpg
Deleted: /content/gdrive/MyDrive/4QzLuxE4sDjZpYeqKbEscw.jpg
Deleted: /content/gdrive/MyDrive/3_fNH6k2KclGOCnX8sgTgA.jpg
Deleted: /content/gdrive/MyDrive/7t-OcoH3QmoK2sB3aFq0aQ.jpg
Deleted: /content/gdrive/MyDrive/-oQam8nRcx1ZPK4fUpiaQg.jpg
Deleted: /content/gdrive/MyDrive/2z4tSV3V3DKSIuc2P9ueXA.jpg
Deleted: /content/gdrive/MyDrive/D8iCejZl3AqF7cgaDICBAg.jpg
Deleted: /content/gdrive/MyDrive/6X6Q10Lyw8-ObDG72dhICw.jpg
Deleted: /content/gdrive/MyDrive/DbBhpEKaYXkSj0YryrvERQ.jpg
Deleted: /content/gdrive/MyDrive/0AEbshrlRLCbY98l4gsn8A.jpg
Deleted: /content/gdrive/MyDrive/3RB7MwMIeBcNusnU5bdl-g.jpg
Deleted: /content/gdrive/MyDrive/7aDkEUJmMM4joC8C9Np41g.jpg
Deleted: /content/gdrive/MyDrive/2vKOHm8XC6zt7e59aocQdw.jpg
Deleted: /content/gdrive/MyDrive/BA2d-vw2OQQ8aHBQ1dk0RA.jpg
Deleted: /content/gdrive/MyDrive/Bv3GKAVajGgXYE9eHWyLmw.jpg
Deleted: /content/gdrive/MyDrive/4RcG8jJ5Mx-qbhaywC-pBQ.jpg
Deleted: /content/gdrive/MyDrive/1Bq_-kaEH2knAjOPZh6OWw.jpg
Deleted: /content/gdrive/MyDrive/8NILOiqCktxz-sdq2Y4q2w.jpg
Deleted: /content/gdrive/MyDrive/9OxVdNOAdPsjVaZrvUVmHw.jpg
Deleted: /content/gdrive/MyDrive/6Qu86KUPbdWzNH4UqGO4Ww.jpg
Deleted: /content/gdrive/MyDrive/6EQvCrRMh6QLJh1rDe3TzA.jpg
Deleted: /content/gdrive/MyDrive/FHN5NZfnGeEgMRYtpn7CLQ.jpg
Deleted: /content/gdrive/MyDrive/Bhw1B6zTXx2cfANsXFLFUg.jpg
Deleted: /content/gdrive/MyDrive/-YPY81fouoG7rXRw8krsSA.jpg
Deleted: /content/gdrive/MyDrive/8zaF0iRbpfZVdaQD1YK_Qw.jpg
Deleted: /content/gdrive/MyDrive/9OgTTALhYGm1OoWgWvcxVg.jpg

In [ ]:
!pip3 install ffmpeg-python deepspeed

Requirement already satisfied: ffmpeg-python in /usr/local/lib/python3.11/dist-packages (0.2.0)
Requirement already satisfied: deepspeed in /usr/local/lib/python3.11/dist-packages (0.16.7)
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from ffmpeg-python) (1.0.0)
Requirement already satisfied: einops in /usr/local/lib/python3.11/dist-packages (from deepspeed) (0.8.1)
Requirement already satisfied: hjson in /usr/local/lib/python3.11/dist-packages (from deepspeed) (3.1.0)
Requirement already satisfied: msgpack in /usr/local/lib/python3.11/dist-packages (from deepspeed) (1.1.0)
Requirement already satisfied: ninja in /usr/local/lib/python3.11/dist-packages (from deepspeed) (1.11.1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from deepspeed) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from deepspeed) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from deepspeed) (5.9.5)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from deepspeed) (9.0.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from deepspeed) (2.11.4)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (from deepspeed) (2.6.0+cu124)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from deepspeed) (4.67.1)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.11/dist-packages (from deepspeed) (12.575.51)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (4.13.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->deepspeed) (0.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (3.18.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (2.8.8)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (2025.3.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch->deepspeed) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch->deepspeed) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch->deepspeed) (3.0.2)

# Import libraries

In [ ]:
from google.colab import runtime
runtime.unassign()

In [ ]:
import os
import shutil
import ffmpeg
import tarfile
import pandas as pd

In [ ]:
from google.colab import drive

drive.mount("/content/gdrive", force_remount=True)

Mounted at /content/gdrive

# Dataset Preparation

In [ ]:
import pandas as pd
df = pd.read_excel('/content/gdrive/MyDrive/85cleaned_file.xlsx')
# df1 = pd.read_csv('/content/gdrive/MyDrive/finetuning_dataset/audio_text_youssef.csv')
# df2 = pd.read_csv('/content/gdrive/MyDrive/finetuning_dataset/audio_text_amir.csv')

# df = pd.concat([df1, df2])

In [ ]:
# df = df[df['is_remove'] == 0]
df

,Chunk Name,Start Time (ms),End Time (ms),Duration (s),Chunk Path,Transcript,Word Count,Words Per Second,Is_Music,Detected_Emotions,Is_Denoised,phonemes,transcript_with_emotions,PlayAudio,Unnamed: 14,Unnamed: 15
0,audio001-chunk0.wav,0,13124,13.124,dataset\audio001-chunk0.wav,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...,30,2.285888,False,NaN,0,knɪŋ gʊ ənə ɪ b n tæ ɪlɪʃɪ dɪnm təwəðiaɪ fɪʃ ...,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...,▶ Play,NaN,NaN
1,audio001-chunk1.wav,13757,36498,22.741,dataset\audio001-chunk1.wav,عامه يقرا كتاب يحس روحه باللي را ناجح انت غير ...,31,1.363177,False,"{'Laughter': {'confidence': 0.142, 'start_time...",0,khɪ kənə k tə jihəsəhə b lɪhnɛʃ təɪ kəni tə k...,عامه يقرا كتاب <Laughter> يحس روحه باللي را نا...,▶ Play,باللي را ناجح انت غير قيت كتا,NaN
2,audio001-chunk2.wav,37027,42197,5.170,dataset\audio001-chunk2.wav,في حياتهم يا اما فر يا اماي,7,1.353965,False,NaN,0,jɛ ɛməðeɪɑhaɪ ə ʧivɝz jɛ ɛməðeɪɑɹəloʊ dɛɹ ən d...,في حياتهم يا اما فر يا اماي,▶ Play,NaN,NaN
3,audio001-chunk3.wav,42386,47554,5.168,dataset\audio001-chunk3.wav,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك,9,1.741486,False,NaN,0,hʊ ziumə gə dəwhɑɾɑnioʊ ʃɪv t kʊm zuʃ b niɛ də...,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك,▶ Play,NaN,NaN
4,audio001-chunk4.wav,47828,51925,4.097,dataset\audio001-chunk4.wav,تعرفت عليهم هنا في دباي ومن مدينتي من,8,1.952648,False,NaN,0,ə gʊsənɑ dɑh k tɾəf tɛɾioʊmhənəfɪ du baɪ wumɪm...,تعرفت عليهم هنا في دباي ومن مدينتي من,▶ Play,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8156,audio022-chunk339.wav,2320814,2326703,5.889,dataset\audio022-chunk339.wav,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...,17,2.886738,False,NaN,0,kɪ tfɑʃɪ kənæɑ tɑ k wɪʃ t əhɪ dɪɪ sθɪnəhə deɪ...,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...,▶ Play,NaN,NaN
8157,audio022-chunk340.wav,2326832,2330809,3.977,dataset\audio022-chunk340.wav,كييقوللك اوكي طاك واش ندير بابليش,6,1.508675,False,NaN,0,ki oʊlɪ k oʊ keɪtɑ k wuʃn dɪɾoʊ bɑ b leɪ,كييقوللك اوكي طاك واش ندير بابليش,▶ Play,NaN,NaN
8158,audio022-chunk341.wav,2331038,2334331,3.293,dataset\audio022-chunk341.wav,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك,9,2.733070,False,NaN,0,ʃ k li k ɛɾəhə di mən bæ dɪ təhɑɹ ʤlɪ k lə pɪ ...,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك,▶ Play,NaN,NaN
8159,audio022-chunk342.wav,2334605,2354064,19.459,dataset\audio022-chunk342.wav,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...,50,2.569505,False,NaN,0,hnæɑ wɛʃ daʊ hnɛf diɪvɪɾi ɪ tɪ b lɪ bɪi jɛni...,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...,▶ Play,NaN,NaN
8160,audio022-chunk343.wav,2354158,2377394,23.236,dataset\audio022-chunk343.wav,تكون فخور بهم ان شاء الله ما كناش بزاف تقال عل...,67,2.883457,False,"{'Sigh': {'confidence': 0.361, 'start_time': 0...",0,mɪhʃələmə kənəʃ b zɛf kəɛɾə kəɪ p kəm haɪvə k...,<Sigh> تكون فخور بهم ان شاء الله ما كناش بزاف ...,▶ Play,NaN,NaN

## Remove audios

In [ ]:
# audios_path = '/content/gdrive/MyDrive/finetuning_dataset/dataset/audios'
# audios = os.listdir(audios_path)

# for audio in audios:
#   current_audio_path = os.path.join(audios_path, audio)
#   os.remove(current_audio_path)

## Copy audios to another folder

In [ ]:

# os.makedirs('/content/gdrive/MyDrive/finetuning_dataset/dataset/wavs', exist_ok=True)

# source_path = '/content/gdrive/MyDrive/finetuning_dataset/dataset/splitted_audios'
# distination_path = '/content/gdrive/MyDrive/finetuning_dataset/dataset/wavs'

# audios = df['filename'].tolist()
# for audio in audios:
#   if audio.endswith('.wav'):
#     current_audio_path = os.path.join(source_path, audio)
#     new_audio_path = os.path.join(distination_path, audio)
#     shutil.copy2(current_audio_path, new_audio_path)

In [ ]:
df.drop(columns=['is_remove', 'duration'], axis=1, inplace=True)

In [ ]:
df['filename'] = df['filename'].apply(lambda x: x.replace('.wav', ''))
# df['text'] = df['text'].apply(lambda x: str(x)+'|')
# df['normalized_text'] = df['normalized_text'].apply(lambda x: str(x)+'|')

In [ ]:
import os
import pandas as pd


# Create the new DataFrame with required columns
df2 = pd.DataFrame({
    "filename": df["Chunk Name"],
    "text": df["Transcript"],
    "normalized_text": df["Transcript"]  # Just copying for now
})

In [ ]:
df2.to_csv('/content/gdrive/MyDrive/dataset22050/metadata.csv', encoding='utf-8-sig', index=False, header=False, sep='|',)

In [ ]:
df2

,filename,text,normalized_text
0,audio001-chunk0.wav,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...,خليني نقول انا ابن عائله جدا متواضعه طيب وين ت...
1,audio001-chunk1.wav,عامه يقرا كتاب يحس روحه باللي را ناجح انت غير ...,عامه يقرا كتاب يحس روحه باللي را ناجح انت غير ...
2,audio001-chunk2.wav,في حياتهم يا اما فر يا اماي,في حياتهم يا اما فر يا اماي
3,audio001-chunk3.wav,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك,اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك
4,audio001-chunk4.wav,تعرفت عليهم هنا في دباي ومن مدينتي من,تعرفت عليهم هنا في دباي ومن مدينتي من
...,...,...,...
8156,audio022-chunk339.wav,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...,كي تخرج لك هنايا طاك واش تروح دير استنى هذا يط...
8157,audio022-chunk340.wav,كييقوللك اوكي طاك واش ندير بابليش,كييقوللك اوكي طاك واش ندير بابليش
8158,audio022-chunk341.wav,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك,بابليش كليكي على هذيا من بعد تخرجلك لابيبليس تاعك
8159,audio022-chunk342.wav,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...,تاعك هنايا واجده هنا في الديليفري يكتبلك باللي...
8160,audio022-chunk343.wav,تكون فخور بهم ان شاء الله ما كناش بزاف تقال عل...,تكون فخور بهم ان شاء الله ما كناش بزاف تقال عل...

In [ ]:
metadata_path = os.path.join('/content/gdrive/MyDrive/data/dataset22050', "metadata.csv")
with open(metadata_path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, 1):
      if i > 5:
        break
      cols = line.strip().split("|")
      if len(cols) < 3:  # Check if there are fewer than 3 columns
          print(f"Error on line {i}: {line}")
      else:
          print(f"Line {i} is valid: {cols[2]}")

Line 1 is valid: خليني نقول انا ابن عائله جدا متواضعه طيب وين تقدر تقول همي الوحيد كان نخدم كنت نبيع قصبر كبيع بورسات نخدم باش نجاوب على الغلطه اللي يطيح فيها الجزائري بصفه
Line 2 is valid: عامه يقرا كتاب يحس روحه باللي را ناجح انت غير قيت كتا كيتفرج كيتفرج على اندر اندر ناجح تتفرج على واح ناجح ما تنج بالعكس تلا واحدي دوها عندهم ترا في
Line 3 is valid: في حياتهم يا اما فر يا اماي
Line 4 is valid: اماي اليده وهرانيه جبتلكم بني ادم فها قسره ضحك
Line 5 is valid: تعرفت عليهم هنا في دباي ومن مدينتي من

In [ ]:
len(os.listdir('/content/gdrive/MyDrive/dataset'))

8191

## Change audio sample rate

In [ ]:
import time

def convert_sample_rate(audios_path, output_path, target_sample_rate):
  os.makedirs(output_path, exist_ok=True)
  audios = os.listdir(audios_path)
  start = time.time()
  for i, audio in enumerate(audios):
    if i % 100 == 0:
      current = time.time()
      print(f'Time take to process {i} audios: {current-start:.1f} seconds')
    audio_path = os.path.join(audios_path, audio)
    audio_output_path = os.path.join(output_path, audio)
    try:
      ffmpeg.input(audio_path).output(audio_output_path, ar=target_sample_rate).run(capture_stdout=True, capture_stderr=True) # .overwrite_output()
      print(f'Converted audio {i}')
      print(f"Successfully converted {audio_path} to {target_sample_rate} Hz")
    except ffmpeg.Error as e:
      print(f"Conversion failed. Error: {e.stderr.decode()}")


audios_path = '/content/gdrive/MyDrive/dataset'
output_path = '/content/gdrive/MyDrive/dataset22050'
target_sample_rate = 22050
convert_sample_rate(audios_path, output_path, target_sample_rate)

Streaming output truncated to the last 5000 lines.
Converted audio 5703
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk377.wav to 22050 Hz
Converted audio 5704
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk416.wav to 22050 Hz
Converted audio 5705
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk371.wav to 22050 Hz
Converted audio 5706
Successfully converted /content/gdrive/MyDrive/dataset/audio008-chunk417.wav to 22050 Hz
Converted audio 5707
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk4.wav to 22050 Hz
Converted audio 5708
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk77.wav to 22050 Hz
Converted audio 5709
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk110.wav to 22050 Hz
Converted audio 5710
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk29.wav to 22050 Hz
Converted audio 5711
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk60.wav to 22050 Hz
Converted audio 5712
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk62.wav to 22050 Hz
Converted audio 5713
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk54.wav to 22050 Hz
Converted audio 5714
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk13.wav to 22050 Hz
Converted audio 5715
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk79.wav to 22050 Hz
Converted audio 5716
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk38.wav to 22050 Hz
Converted audio 5717
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk26.wav to 22050 Hz
Converted audio 5718
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk24.wav to 22050 Hz
Converted audio 5719
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk103.wav to 22050 Hz
Converted audio 5720
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk9.wav to 22050 Hz
Converted audio 5721
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk16.wav to 22050 Hz
Converted audio 5722
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk105.wav to 22050 Hz
Converted audio 5723
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk0.wav to 22050 Hz
Converted audio 5724
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk6.wav to 22050 Hz
Converted audio 5725
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk113.wav to 22050 Hz
Converted audio 5726
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk31.wav to 22050 Hz
Converted audio 5727
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk97.wav to 22050 Hz
Converted audio 5728
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk58.wav to 22050 Hz
Converted audio 5729
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk23.wav to 22050 Hz
Converted audio 5730
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk119.wav to 22050 Hz
Converted audio 5731
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk80.wav to 22050 Hz
Converted audio 5732
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk55.wav to 22050 Hz
Converted audio 5733
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk41.wav to 22050 Hz
Converted audio 5734
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk25.wav to 22050 Hz
Converted audio 5735
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk46.wav to 22050 Hz
Converted audio 5736
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk90.wav to 22050 Hz
Converted audio 5737
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk95.wav to 22050 Hz
Converted audio 5738
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk36.wav to 22050 Hz
Converted audio 5739
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk50.wav to 22050 Hz
Converted audio 5740
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk121.wav to 22050 Hz
Converted audio 5741
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk7.wav to 22050 Hz
Converted audio 5742
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk47.wav to 22050 Hz
Converted audio 5743
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk37.wav to 22050 Hz
Converted audio 5744
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk98.wav to 22050 Hz
Converted audio 5745
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk73.wav to 22050 Hz
Converted audio 5746
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk72.wav to 22050 Hz
Converted audio 5747
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk35.wav to 22050 Hz
Converted audio 5748
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk81.wav to 22050 Hz
Converted audio 5749
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk78.wav to 22050 Hz
Converted audio 5750
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk65.wav to 22050 Hz
Converted audio 5751
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk85.wav to 22050 Hz
Converted audio 5752
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk45.wav to 22050 Hz
Converted audio 5753
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk39.wav to 22050 Hz
Converted audio 5754
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk83.wav to 22050 Hz
Converted audio 5755
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk34.wav to 22050 Hz
Converted audio 5756
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk107.wav to 22050 Hz
Converted audio 5757
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk53.wav to 22050 Hz
Converted audio 5758
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk70.wav to 22050 Hz
Converted audio 5759
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk118.wav to 22050 Hz
Converted audio 5760
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk84.wav to 22050 Hz
Converted audio 5761
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk15.wav to 22050 Hz
Converted audio 5762
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk116.wav to 22050 Hz
Converted audio 5763
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk76.wav to 22050 Hz
Converted audio 5764
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk56.wav to 22050 Hz
Converted audio 5765
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk19.wav to 22050 Hz
Converted audio 5766
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk44.wav to 22050 Hz
Converted audio 5767
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk11.wav to 22050 Hz
Converted audio 5768
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk33.wav to 22050 Hz
Converted audio 5769
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk100.wav to 22050 Hz
Converted audio 5770
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk112.wav to 22050 Hz
Converted audio 5771
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk86.wav to 22050 Hz
Converted audio 5772
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk102.wav to 22050 Hz
Converted audio 5773
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk3.wav to 22050 Hz
Converted audio 5774
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk66.wav to 22050 Hz
Converted audio 5775
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk5.wav to 22050 Hz
Converted audio 5776
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk120.wav to 22050 Hz
Converted audio 5777
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk91.wav to 22050 Hz
Converted audio 5778
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk114.wav to 22050 Hz
Converted audio 5779
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk63.wav to 22050 Hz
Converted audio 5780
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk88.wav to 22050 Hz
Converted audio 5781
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk1.wav to 22050 Hz
Converted audio 5782
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk67.wav to 22050 Hz
Converted audio 5783
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk32.wav to 22050 Hz
Converted audio 5784
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk64.wav to 22050 Hz
Converted audio 5785
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk96.wav to 22050 Hz
Converted audio 5786
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk82.wav to 22050 Hz
Converted audio 5787
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk2.wav to 22050 Hz
Converted audio 5788
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk57.wav to 22050 Hz
Converted audio 5789
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk48.wav to 22050 Hz
Converted audio 5790
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk8.wav to 22050 Hz
Converted audio 5791
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk42.wav to 22050 Hz
Converted audio 5792
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk93.wav to 22050 Hz
Converted audio 5793
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk30.wav to 22050 Hz
Converted audio 5794
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk104.wav to 22050 Hz
Converted audio 5795
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk94.wav to 22050 Hz
Converted audio 5796
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk108.wav to 22050 Hz
Converted audio 5797
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk14.wav to 22050 Hz
Converted audio 5798
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk52.wav to 22050 Hz
Converted audio 5799
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk22.wav to 22050 Hz
Time take to process 5800 audios: 1628.2 seconds
Converted audio 5800
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk20.wav to 22050 Hz
Converted audio 5801
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk10.wav to 22050 Hz
Converted audio 5802
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk106.wav to 22050 Hz
Converted audio 5803
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk17.wav to 22050 Hz
Converted audio 5804
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk115.wav to 22050 Hz
Converted audio 5805
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk117.wav to 22050 Hz
Converted audio 5806
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk21.wav to 22050 Hz
Converted audio 5807
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk27.wav to 22050 Hz
Converted audio 5808
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk49.wav to 22050 Hz
Converted audio 5809
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk51.wav to 22050 Hz
Converted audio 5810
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk71.wav to 22050 Hz
Converted audio 5811
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk74.wav to 22050 Hz
Converted audio 5812
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk61.wav to 22050 Hz
Converted audio 5813
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk111.wav to 22050 Hz
Converted audio 5814
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk101.wav to 22050 Hz
Converted audio 5815
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk43.wav to 22050 Hz
Converted audio 5816
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk18.wav to 22050 Hz
Converted audio 5817
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk109.wav to 22050 Hz
Converted audio 5818
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk28.wav to 22050 Hz
Converted audio 5819
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk69.wav to 22050 Hz
Converted audio 5820
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk92.wav to 22050 Hz
Converted audio 5821
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk59.wav to 22050 Hz
Converted audio 5822
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk12.wav to 22050 Hz
Converted audio 5823
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk89.wav to 22050 Hz
Converted audio 5824
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk75.wav to 22050 Hz
Converted audio 5825
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk40.wav to 22050 Hz
Converted audio 5826
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk87.wav to 22050 Hz
Converted audio 5827
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk122.wav to 22050 Hz
Converted audio 5828
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk68.wav to 22050 Hz
Converted audio 5829
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk99.wav to 22050 Hz
Converted audio 5830
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk126.wav to 22050 Hz
Converted audio 5831
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk160.wav to 22050 Hz
Converted audio 5832
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk140.wav to 22050 Hz
Converted audio 5833
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk150.wav to 22050 Hz
Converted audio 5834
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk123.wav to 22050 Hz
Converted audio 5835
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk149.wav to 22050 Hz
Converted audio 5836
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk156.wav to 22050 Hz
Converted audio 5837
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk129.wav to 22050 Hz
Converted audio 5838
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk131.wav to 22050 Hz
Converted audio 5839
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk139.wav to 22050 Hz
Converted audio 5840
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk124.wav to 22050 Hz
Converted audio 5841
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk125.wav to 22050 Hz
Converted audio 5842
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk144.wav to 22050 Hz
Converted audio 5843
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk127.wav to 22050 Hz
Converted audio 5844
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk137.wav to 22050 Hz
Converted audio 5845
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk159.wav to 22050 Hz
Converted audio 5846
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk138.wav to 22050 Hz
Converted audio 5847
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk141.wav to 22050 Hz
Converted audio 5848
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk151.wav to 22050 Hz
Converted audio 5849
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk143.wav to 22050 Hz
Converted audio 5850
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk135.wav to 22050 Hz
Converted audio 5851
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk157.wav to 22050 Hz
Converted audio 5852
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk154.wav to 22050 Hz
Converted audio 5853
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk158.wav to 22050 Hz
Converted audio 5854
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk136.wav to 22050 Hz
Converted audio 5855
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk142.wav to 22050 Hz
Converted audio 5856
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk146.wav to 22050 Hz
Converted audio 5857
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk155.wav to 22050 Hz
Converted audio 5858
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk161.wav to 22050 Hz
Converted audio 5859
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk145.wav to 22050 Hz
Converted audio 5860
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk147.wav to 22050 Hz
Converted audio 5861
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk148.wav to 22050 Hz
Converted audio 5862
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk128.wav to 22050 Hz
Converted audio 5863
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk152.wav to 22050 Hz
Converted audio 5864
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk133.wav to 22050 Hz
Converted audio 5865
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk132.wav to 22050 Hz
Converted audio 5866
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk134.wav to 22050 Hz
Converted audio 5867
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk130.wav to 22050 Hz
Converted audio 5868
Successfully converted /content/gdrive/MyDrive/dataset/audio009-chunk153.wav to 22050 Hz
Converted audio 5869
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk2.wav to 22050 Hz
Converted audio 5870
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk24.wav to 22050 Hz
Converted audio 5871
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk26.wav to 22050 Hz
Converted audio 5872
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk16.wav to 22050 Hz
Converted audio 5873
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk0.wav to 22050 Hz
Converted audio 5874
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk11.wav to 22050 Hz
Converted audio 5875
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk25.wav to 22050 Hz
Converted audio 5876
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk19.wav to 22050 Hz
Converted audio 5877
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk6.wav to 22050 Hz
Converted audio 5878
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk4.wav to 22050 Hz
Converted audio 5879
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk17.wav to 22050 Hz
Converted audio 5880
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk15.wav to 22050 Hz
Converted audio 5881
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk21.wav to 22050 Hz
Converted audio 5882
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk9.wav to 22050 Hz
Converted audio 5883
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk8.wav to 22050 Hz
Converted audio 5884
Successfully converted /content/gdrive/MyDrive/dataset/audio010-chunk23.wav to 22050 Hz

# FINE-TUNING XTTS-v2 #

In [ ]:
!pip install git+https://github.com/coqui-ai/TTS

Collecting git+https://github.com/coqui-ai/TTS
  Cloning https://github.com/coqui-ai/TTS to /tmp/pip-req-build-1h34opkb
  Running command git clone --filter=blob:none --quiet https://github.com/coqui-ai/TTS /tmp/pip-req-build-1h34opkb
  Resolved https://github.com/coqui-ai/TTS to commit dbf1a08a0d4e47fdad6172e433eeb34bc6b13b4e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (2.0.2)
Requirement already satisfied: cython>=0.29.30 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.0.12)
Requirement already satisfied: scipy>=1.11.2 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.15.3)
Requirement already satisfied: torch>=2.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (2.6.0+cu124)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (2.6.0+cu124)
Requirement already satisfied: soundfile>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.13.1)
Requirement already satisfied: librosa>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.11.0)
Requirement already satisfied: scikit-learn>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (1.6.1)
Requirement already satisfied: numba>=0.57.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.60.0)
Requirement already satisfied: inflect>=5.6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (7.5.0)
Requirement already satisfied: tqdm>=4.64.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (4.67.1)
Collecting anyascii>=0.3.0 (from TTS==0.22.0)
  Downloading anyascii-0.3.2-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: pyyaml>=6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (6.0.2)
Requirement already satisfied: fsspec>=2023.6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (2025.3.2)
Requirement already satisfied: aiohttp>=3.8.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.11.15)
Requirement already satisfied: packaging>=23.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (24.2)
Collecting mutagen==1.47.0 (from TTS==0.22.0)
  Downloading mutagen-1.47.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: flask>=2.0.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.1.1)
Collecting pysbd>=0.3.4 (from TTS==0.22.0)
  Downloading pysbd-0.3.4-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: umap-learn>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.5.7)
Collecting pandas<2.0,>=1.4 (from TTS==0.22.0)
  Downloading pandas-1.5.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: matplotlib>=3.7.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.10.0)
Collecting trainer>=0.0.36 (from TTS==0.22.0)
  Downloading trainer-0.0.36-py3-none-any.whl.metadata (8.1 kB)
Collecting coqpit>=0.0.16 (from TTS==0.22.0)
  Downloading coqpit-0.0.17-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: jieba in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.42.1)
Collecting pypinyin (from TTS==0.22.0)
  Downloading pypinyin-0.54.0-py2.py3-none-any.whl.metadata (12 kB)
Collecting hangul_romanize (from TTS==0.22.0)
  Downloading hangul_romanize-0.1.0-py3-none-any.whl.metadata (1.2 kB)
Collecting gruut==2.2.3 (from gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading gruut-2.2.3.tar.gz (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting jamo (from TTS==0.22.0)
  Downloading jamo-0.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (3.9.1)
Collecting g2pkk>=0.1.1 (from TTS==0.22.0)
  Downloading g2pkk-0.1.2-py3-none-any.whl.metadata (2.0 kB)
Collecting bangla (from TTS==0.22.0)
  Downloading bangla-0.0.5-py3-none-any.whl.metadata (4.7 kB)
Collecting bnnumerizer (from TTS==0.22.0)
  Downloading bnnumerizer-0.0.2.tar.gz (4.7 kB)
  Preparing metadata (setup.py) ... done
Collecting bnunicodenormalizer (from TTS==0.22.0)
  Downloading bnunicodenormalizer-0.1.7-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (0.8.1)
Requirement already satisfied: transformers>=4.33.0 in /usr/local/lib/python3.11/dist-packages (from TTS==0.22.0) (4.51.3)
Collecting encodec>=0.1.1 (from TTS==0.22.0)
  Downloading encodec-0.1.1.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 76.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting unidecode>=1.3.2 (from TTS==0.22.0)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Collecting num2words (from TTS==0.22.0)
  Downloading num2words-0.5.14-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: spacy>=3 in /usr/local/lib/python3.11/dist-packages (from spacy[ja]>=3->TTS==0.22.0) (3.8.5)
Requirement already satisfied: Babel<3.0.0,>=2.8.0 in /usr/local/lib/python3.11/dist-packages (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (2.17.0)
Collecting dateparser~=1.1.0 (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading dateparser-1.1.8-py2.py3-none-any.whl.metadata (27 kB)
Collecting gruut-ipa<1.0,>=0.12.0 (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading gruut-ipa-0.13.0.tar.gz (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 11.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gruut_lang_en~=2.0.0 (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading gruut_lang_en-2.0.1.tar.gz (15.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 109.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting jsonlines~=1.2.0 (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading jsonlines-1.2.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting networkx<3.0.0,>=2.5.0 (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading networkx-2.8.8-py3-none-any.whl.metadata (5.1 kB)
Collecting numpy>=1.24.3 (from TTS==0.22.0)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.7 MB/s eta 0:00:00
Collecting python-crfsuite~=0.9.7 (from gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading python_crfsuite-0.9.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.3 kB)
Collecting gruut_lang_de~=2.0.0 (from gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading gruut_lang_de-2.0.1.tar.gz (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 27.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gruut_lang_es~=2.0.0 (from gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading gruut_lang_es-2.0.1.tar.gz (31.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.4/31.4 MB 12.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gruut_lang_fr~=2.0.0 (from gruut[de,es,fr]==2.2.3->TTS==0.22.0)
  Downloading gruut_lang_fr-2.0.2.tar.gz (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 119.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.8.1->TTS==0.22.0) (1.20.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (8.2.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from flask>=2.0.1->TTS==0.22.0) (3.1.3)
Requirement already satisfied: more_itertools>=8.5.0 in /usr/local/lib/python3.11/dist-packages (from inflect>=5.6.0->TTS==0.22.0) (10.7.0)
Requirement already satisfied: typeguard>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from inflect>=5.6.0->TTS==0.22.0) (4.4.2)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (3.0.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (1.5.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (1.8.2)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (0.5.0.post1)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (4.13.2)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (0.4)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.11/dist-packages (from librosa>=0.10.0->TTS==0.22.0) (1.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.7.0->TTS==0.22.0) (2.9.0.post0)
Collecting docopt>=0.6.2 (from num2words->TTS==0.22.0)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.57.0->TTS==0.22.0) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.0,>=1.4->TTS==0.22.0) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.3.0->TTS==0.22.0) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.11/dist-packages (from soundfile>=0.12.0->TTS==0.22.0) (1.17.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.15.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.11.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (75.2.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.5.0)
Collecting sudachipy!=0.6.1,>=0.5.2 (from spacy[ja]>=3->TTS==0.22.0)
  Downloading SudachiPy-0.6.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting sudachidict_core>=20211220 (from spacy[ja]>=3->TTS==0.22.0)
  Downloading SudachiDict_core-20250129-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (3.18.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.1->TTS==0.22.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.1->TTS==0.22.0) (1.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from trainer>=0.0.36->TTS==0.22.0) (5.9.5)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.11/dist-packages (from trainer>=0.0.36->TTS==0.22.0) (2.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (0.31.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.33.0->TTS==0.22.0) (0.5.3)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.1->TTS==0.22.0) (0.5.13)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.0->soundfile>=0.12.0->TTS==0.22.0) (2.22)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.11/dist-packages (from dateparser~=1.1.0->gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (5.3.1)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from jsonlines~=1.2.0->gruut==2.2.3->gruut[de,es,fr]==2.2.3->TTS==0.22.0) (1.17.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (1.3.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from pooch>=1.1->librosa>=0.10.0->TTS==0.22.0) (4.3.8)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3->spacy[ja]>=3->TTS==0.22.0) (3.10)

In [ ]:
!pip install transformers==4.37.1

Collecting transformers==4.37.1
  Using cached transformers-4.37.1-py3-none-any.whl.metadata (129 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (0.31.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (2.32.3)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.37.1)
  Downloading tokenizers-0.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.37.1) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.37.1) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.37.1) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.37.1) (2025.4.26)
Downloading transformers-4.37.1-py3-none-any.whl (8.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 76.2 MB/s eta 0:00:00
Downloading tokenizers-0.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 111.1 MB/s eta 0:00:00
Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.21.1
    Uninstalling tokenizers-0.21.1:
      Successfully uninstalled tokenizers-0.21.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.51.3
    Uninstalling transformers-4.51.3:
      Successfully uninstalled transformers-4.51.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 4.1.0 requires transformers<5.0.0,>=4.41.0, but you have transformers 4.37.1 which is incompatible.
Successfully installed tokenizers-0.15.2 transformers-4.37.1

In [ ]:
###updated training zone####

In [ ]:
from trainer import Trainer, TrainerArgs
#from trainer.logging.wandb_logger import WandbLogger
from TTS.tts.configs.shared_configs import BaseDatasetConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.layers.xtts.trainer.gpt_trainer import GPTArgs, GPTTrainer, GPTTrainerConfig, XttsAudioConfig
from TTS.utils.manage import ModelManager

import sys
import os
import wandb

### Monkey Patching for wandb

In [ ]:
from trainer.logging.wandb_logger import WandbLogger

In [ ]:
def add_artifact(self, file_or_dir, name, artifact_type, aliases=None):
    ###instead of adding artifact, do nothing###
    print(f"========Ignoring artifact: {name} {file_or_dir}========")
    return


WandbLogger.add_artifact = add_artifact

In [ ]:
# Logging parameters
RUN_NAME = "finetuned_egtts_v2_dz"
PROJECT_NAME = "dz_ar_model2"
DASHBOARD_LOGGER = "wandb"
LOGGER_URI = None

### Dir for Training Run

In [ ]:
OUT_PATH = '/content/gdrive/MyDrive/models'
os.makedirs(OUT_PATH, exist_ok=True)

Retreive the base model files.

In [ ]:
# Define the path where XTTS v2.0.1 files will be downloaded
CHECKPOINTS_OUT_PATH = os.path.join(OUT_PATH, "Checkpoints_dztts/")
os.makedirs(CHECKPOINTS_OUT_PATH, exist_ok=True)

# DVAE files
DVAE_CHECKPOINT_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/dvae.pth"
MEL_NORM_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/mel_stats.pth"

# Set the path to the downloaded files
DVAE_CHECKPOINT = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(DVAE_CHECKPOINT_LINK))
MEL_NORM_FILE = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(MEL_NORM_LINK))

# download DVAE files if needed
if not os.path.isfile(DVAE_CHECKPOINT) or not os.path.isfile(MEL_NORM_FILE):
    print(" > Downloading DVAE files!")
    ModelManager._download_model_files([MEL_NORM_LINK, DVAE_CHECKPOINT_LINK], CHECKPOINTS_OUT_PATH, progress_bar=True)

# Download XTTS v2.0 checkpoint if needed
TOKENIZER_FILE_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/vocab.json"
XTTS_CHECKPOINT_LINK = "https://coqui.gateway.scarf.sh/hf-coqui/XTTS-v2/main/model.pth"

# XTTS transfer learning parameters: You we need to provide the paths of XTTS model checkpoint that you want to do the fine tuning.
TOKENIZER_FILE = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(TOKENIZER_FILE_LINK))  # vocab.json file
XTTS_CHECKPOINT = os.path.join(CHECKPOINTS_OUT_PATH, os.path.basename(XTTS_CHECKPOINT_LINK))  # model.pth file

# download XTTS v2.0 files if needed
if not os.path.isfile(TOKENIZER_FILE) or not os.path.isfile(XTTS_CHECKPOINT):
    print(" > Downloading XTTS v2.0 files!")
    ModelManager._download_model_files(
        [TOKENIZER_FILE_LINK, XTTS_CHECKPOINT_LINK], CHECKPOINTS_OUT_PATH, progress_bar=True
    )

In [ ]:
training_dir = "/content/gdrive/MyDrive/data/dataset22050"

### Batch Size ###

* BATCH_SIZE is the amount of items being loaded into VRAM/memory at once.

* GRAD_ACCUM_STEPS is the amount of times we perform a forward pass with BATCH_SIZE amount of items before updating the parameters according to the SGD algorithm.

So a BATCH_SIZE of 2 and GRAD_ACCUM_STEPS of 32 would give an 'effective batch size' of 64 (i.e., 64 items considered per optimisation step).

The creators of XTTS-v2 recommend an effective batch size of 252 for proper training. (I found that reducing this to 126 gave me similar performance and faster fine-tuning, but we should probably listen to them.)

Your BATCH_SIZE will depend on how big your dataset items are and how much VRAM you have available. Make it as large as possible while ensuring that everything fits in VRAM and then make BATCH_SIZE*GRAD_ACCUM_STEPS==252.

In [ ]:

OPTIMIZER_WD_ONLY_ON_WEIGHTS = True
START_WITH_EVAL = True
BATCH_SIZE = 1
GRAD_ACUMM_STEPS = 1
LANGUAGE = "ar"

### Dataset Config

In [ ]:

model_args = GPTArgs(
    max_conditioning_length=242524,#the audio you will use for conditioning latents should be less than this
    min_conditioning_length=66168,#and more than this
    debug_loading_failures=True,#this will print output to console and help you find problems in your ds
    max_wav_length=530000,#set this to >= the longest audio in your dataset
    max_text_length=300,
    mel_norm_file=MEL_NORM_FILE,
    dvae_checkpoint=DVAE_CHECKPOINT,
    xtts_checkpoint=XTTS_CHECKPOINT,
    tokenizer_file=TOKENIZER_FILE,
    gpt_num_audio_tokens=1026,
    gpt_start_audio_token=1024,
    gpt_stop_audio_token=1025,
    gpt_use_masking_gt_prompt_approach=True,
    gpt_use_perceiver_resampler=True,
)

### Audio Config ###

The coqui TTS docs mention inspecting your data with the CheckSpectrograms.ipynb notebook to help decide on audio parameters. I think this is irrelevant for XTTS-v2, because it doesn't use the same audio config as some of the older coqui models and doesn't have the same parameters.

The default is 22050 for input and 24000 for output.

**the only reason my sample rate is lower is the dataset I chose has a sample rate of 16000. Assuming you are using your own data, sample_rate and dvae_sample_rate should match your data which should probably be 22050.**

In [ ]:
audio_config = XttsAudioConfig(sample_rate=22050, dvae_sample_rate=22050, output_sample_rate=24000)

### Speaker Reference ###

In [ ]:
SPEAKER_REFERENCE = "/content/gdrive/MyDrive/data/dataset22050/audio004-chunk65.wav"

### Trainer Config

In [ ]:
config = GPTTrainerConfig(
    run_eval=False,
    epochs = 15, # assuming you want to end training manually w/ keyboard interrupt
    output_path=OUT_PATH,
    model_args=model_args,
    run_name=RUN_NAME,
    project_name=PROJECT_NAME,
    run_description="""
        GPT XTTS training
        """,
    dashboard_logger=DASHBOARD_LOGGER,
    wandb_entity=None,
    logger_uri=LOGGER_URI,
    audio=audio_config,
    batch_size=BATCH_SIZE,
    batch_group_size=48,
    eval_batch_size=BATCH_SIZE,
    num_loader_workers=8, #consider decreasing if your jupyter env is crashing or similar
    eval_split_max_size=256,
    print_step=50,
    plot_step=100,
    log_model_step=1000,
    save_step=9999999999, #ALREADY SAVES EVERY EPOCHMaking this high on kaggle because Output dir is limited in size. I changed this to be size of training set/2 so I would effectively have a checkpoint every half epoch
    save_n_checkpoints=1,#if you want to store multiple checkpoint rather than just 1, increase this
    save_checkpoints=True,# Making this False on kaggle because Output dir is limited
    print_eval=False,
    optimizer="AdamW",
    optimizer_wd_only_on_weights=OPTIMIZER_WD_ONLY_ON_WEIGHTS,
    optimizer_params={"betas": [0.9, 0.96], "eps": 1e-8, "weight_decay": 1e-2},
    lr=5e-06,
    lr_scheduler="MultiStepLR",
    lr_scheduler_params={"milestones": [50000 * 18, 150000 * 18, 300000 * 18], "gamma": 0.5, "last_epoch": -1},
    test_sentences=[
        {
            "text": "في رفاهيه على جال هذيك هذاك الشي اللي بدا يصرى معها عجبها بزاف وشافت حياتها عمرها ما كانت تستنا ولا تتوقع انه يجي نهار تعيشها في حياتها",
            "speaker_wav": SPEAKER_REFERENCE,
            "language": LANGUAGE,
        },
    ],
)
import torch
from TTS.tts.configs.xtts_config import XttsConfig
from TTS.tts.models.xtts import XttsAudioConfig, XttsArgs


torch.serialization.add_safe_globals([
    XttsConfig,
    XttsAudioConfig,
    BaseDatasetConfig,
    XttsArgs,  # ✅ New required class
])

model = GPTTrainer.init_from_config(config)

>> DVAE weights restored from: /content/gdrive/MyDrive/models/Checkpoints_dztts/dvae.pth

### Load Dataset

In [1]:
dataset_config = BaseDatasetConfig(
    formatter="ljspeech", meta_file_train="metadata.csv", language=LANGUAGE, path=training_dir
)
train_samples, eval_samples = load_tts_samples(dataset_config, eval_split=True, eval_split_size=0.001)

NameError: name 'BaseDatasetConfig' is not defined

### Train! ###

**Note on warnings:**

The trainer will print out warnings if it encounters items in your dataset where the text exceeds 166 chars or the length of your audio exceeds max_wav_length (It will also have problems if you have data items that are < ~0.2s long, which you won't want anyway). You should remove these from your dataset or re-think how you're creating your dataset.

In [ ]:
def clean_and_rename(samples):
    for sample in samples:
        original_path = sample['audio_file']

        # Check if the path ends with '.wav.wav'
        if original_path.endswith('.wav.wav'):
            # New path: remove one '.wav' and remove 'wavs/' from the path
            new_path = original_path.replace('/wavs/', '/').replace('.wav.wav', '.wav')

            # Rename the actual file
            if os.path.exists(original_path):
                os.rename(original_path, new_path)
                print(f"Renamed: {original_path} -> {new_path}")
            else:
                print(f"File not found: {original_path}")

            # Update the dictionary
            sample['audio_file'] = new_path
            sample['audio_unique_name'] = '#' + new_path.replace(sample['root_path'], '').lstrip('/')
    return samples

# Process both lists
train_samples = clean_and_rename(train_samples)
eval_samples = clean_and_rename(eval_samples)
train_samples

Streaming output truncated to the last 5000 lines.
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk244.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk340.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk289.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk338.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk240.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk70.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk139.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk963.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk559.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk84.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk17.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio001-chunk119.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk72.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk77.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk76.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio009-chunk120.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk236.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk206.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk528.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk539.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk11.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1286.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk903.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk180.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio009-chunk44.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk282.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk445.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk207.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk279.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk338.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk279.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1214.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk50.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk165.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk28.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk342.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk120.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio001-chunk135.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk33.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk162.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk202.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio002-chunk95.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk442.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk442.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk11.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk39.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk94.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk20.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk22.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk546.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk427.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1203.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio002-chunk121.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk16.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk233.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk93.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk18.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk438.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk38.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk499.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1112.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk136.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk252.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk115.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio009-chunk109.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk326.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk44.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk570.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1408.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk236.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio002-chunk305.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk381.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk146.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk182.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk324.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1128.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk290.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio002-chunk262.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk302.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk352.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk329.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1302.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk653.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk979.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk682.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk251.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk33.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk316.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk4.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk14.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk58.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio012-chunk284.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk26.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk9.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk435.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk55.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk231.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk335.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk190.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk447.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio012-chunk131.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk902.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio012-chunk273.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk11.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk339.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk439.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio007-chunk17.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk549.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk416.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk255.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk127.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk366.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk924.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk199.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk91.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk310.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk64.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk304.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk339.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk92.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk359.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk387.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk465.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk183.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk68.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio002-chunk77.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk271.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1008.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio012-chunk72.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk303.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk309.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk613.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk341.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk283.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk56.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk336.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk186.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk87.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk168.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk282.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk262.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk225.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk460.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio001-chunk45.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk381.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk305.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk128.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk379.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk53.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk110.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk142.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio016-chunk334.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1070.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk577.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk283.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio001-chunk38.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk308.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk238.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk248.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk250.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio007-chunk21.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio006-chunk223.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk250.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk32.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio016-chunk244.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk507.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk239.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk887.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk123.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk116.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk267.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk491.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio001-chunk23.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio016-chunk112.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk175.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk391.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk552.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk90.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk84.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1029.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk206.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk335.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk488.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk107.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1012.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio002-chunk299.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio006-chunk203.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk117.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk201.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk281.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk121.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk521.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk201.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk77.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk212.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk124.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk466.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk276.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk270.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk157.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk818.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk259.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio013-chunk170.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio014-chunk594.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio017-chunk62.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk165.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio022-chunk261.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio015-chunk115.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1394.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk57.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1260.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio018-chunk327.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio019-chunk201.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk407.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk1190.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio020-chunk45.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk209.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio008-chunk304.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio010-chunk128.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio012-chunk215.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio003-chunk407.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio021-chunk138.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio002-chunk274.wav.wav
File not found: /content/gdrive/MyDrive/data/dataset22050/wavs/audio011-chunk311.wav.wav

[{'text': 'نقدروا نقولوا حصريه وفي اعتقاد ما راني شفت انا في كثير من المحتويات على الصعيد الوطني كاين كثير من المعلومات اللي قالت اول مره فبودكاست راح\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk7.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk7.wav'},
 {'text': 'هذه قاعده والا كانت الدوله تبعث لنا كتب للدار وكل واحد يقرا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio013-chunk355.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio013-chunk355.wav'},
 {'text': 'جومي ولكن السؤال المطروح شش الحاجه اللي درتها باش ولا السيت ويب يجيب لك نتيجه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk308.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk308.wav'},
 {'text': 'جاتني لحظه ادراك تاع علاش ما كنتش عاطل عن العمل تس نقرا بصح حبيت ندير حاجه اون باراليل انا جامي قعدت\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk35.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk35.wav'},
 {'text': 'دونك الماركت بليس في الجزائر التحدي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk1368.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk1368.wav'},
 {'text': 'تقدمت لها ونجحت فيها وكملت ياسين\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk36.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk36.wav'},
 {'text': 'واش خرج عليها هي يخرج عليكم واش خرج عل انا هذو ديزيكسبيغونس اللي برك تتحفزوا بهم وتدو زعما نقولوا بلي كاينه هذ الطريقه كي تشوفوا انتما هذوك باسكو دوك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk154.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk154.wav'},
 {'text': 'كنت كان عندي شعري كحل طويل ورطب بزاف ومعمر وكنت بيضه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk207.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk207.wav'},
 {'text': 'تخدم ا حبيت اونطر بارونتيز نريبونديلك على هذ لي دو كوتي تاع صعيبه وسهله\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk359.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk359.wav'},
 {'text': 'فقير ومن بعدها شكون شحال من واحد شحال من واحد مات فقير بصح عند ربي غاني بارك الله فيك اول واحد يدخل الجنه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio019-chunk251.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio019-chunk251.wav'},
 {'text': 'لله تما كل واحداني يعرف قدراته قدراته بمعنى انه انايا تيلمون كنت دائما نجي الاولى ودائما نقرا ونجيب\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk179.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk179.wav'},
 {'text': 'عيطلي في التليفون نوضني قاللي راه الوقت باش تروحي تخدمي قلت له ايه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio010-chunk58.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio010-chunk58.wav'},
 {'text': 'وهذا ممنوع جدا في كاس افريقيا ايضا كنا عالجنا هذا المشكل باش ما ياثرش كثير\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk157.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk157.wav'},
 {'text': 'نقدر نسهل عليك الخدمه توليلك كاع اوطوماتيك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio022-chunk198.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio022-chunk198.wav'},
 {'text': 'وفيها رجليا ماقدروش يرفدوني خلاص من صدمه لصدمه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio010-chunk132.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio010-chunk132.wav'},
 {'text': 'دراهمك يروحوا مننا وتتنشر الحاجه هذيك بسعر البنك ما نقدرش نتغمق اكثر مي الفكره انه انت تولي تستقاملك لاماتير بروميير\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk1308.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk1308.wav'},
 {'text': 'اللي كان زاد النص في صخره الدفاع وبنناصر اللي كان المفاجاه ساره واحد ما كان يعرفو\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk88.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk88.wav'},
 {'text': 'هما بعد يخدموا نقولوا دي برودوي دي برودوي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio020-chunk124.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio020-chunk124.wav'},
 {'text': 'كانوا طائرات يرجعوا تاع اللي كانوا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk579.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk579.wav'},
 {'text': 'في اوروبا عندنا في في اليوكرين ريببليك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk186.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk186.wav'},
 {'text': 'كامل يخافوا يسلكوني يعني ماما شغل واحد ما يقدر عليها\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk233.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk233.wav'},
 {'text': 'مالازمش نديروها بطبيعه الحال من بعد تقلقت قلت فين نفسك كيفاش نواجهه خبرت صاحبتي اللي تسكن قدامي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio009-chunk78.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio009-chunk78.wav'},
 {'text': 'وتدي فيها علامه انت 10 و 12 و 13 اذا كان ماشي راح تتفوق فيها\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio013-chunk196.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio013-chunk196.wav'},
 {'text': 'دونك عاودت حبست هذا الفشل تاعي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk78.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk78.wav'},
 {'text': 'تقرا تدير كلش تقدر تخدم دي جنا ما شاء الله اون باغال زعما تلقاهم يخدموا يخدموا اون ميم طون عندهم باك يقراو\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio012-chunk111.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio012-chunk111.wav'},
 {'text': 'اكرم لي كوميرسون نخليلك الكلام انت تعطينا ايطاب ايطاب من ليدي شغل بلا ما تقولي هذ كومس وكذا نروح ديرون قال هذا هو الكور تاع اليوم\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio020-chunk183.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio020-chunk183.wav'},
 {'text': 'وكي بدينا ندير في الحكايات هذوما كامل بدينا نديكوفري قلت لك بعد ما حنا ولينا نديليكيو ليطاش تعلمنا شش معتها ديليكي لاطاش وماديرش كلش وحدك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk394.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk394.wav'},
 {'text': 'نبداو كي كان بابا يقرا في المرحله الابتدائيه والمتوسطه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio009-chunk35.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio009-chunk35.wav'},
 {'text': 'يعني الحمد لله احنا كنا تما في يعني عائله محافظه وكلشي يعني وينلعب الجيمين في وسط المنزل يعني كلشي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk65.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk65.wav'},
 {'text': 'البي ام تاعي البي ام تاعي ديته 18.57\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio012-chunk185.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio012-chunk185.wav'},
 {'text': 'في خدمتي وكي نبدا في خدمتي نحب شاني ندير نحب شفت لو كانك دير حاجه ماكش حابها نحبس\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk420.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk420.wav'},
 {'text': 'لابو تنحي اكسيتيرا باش ترجعها بيفتك تقطعها تقط تقطع ويلعب رول تديبون الكراماج تاع الحبه تاع اللحم قدمها باسك تحطها\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio019-chunk22.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio019-chunk22.wav'},
 {'text': 'قالت لي ش ندير للفطور قلت لها والله غير راني هنا ماني قادر نجوز اني حبس طوماطيش مورسو كسره نبرد\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio019-chunk279.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio019-chunk279.wav'},
 {'text': 'ثلاثه تاع العشيه والشروق تقريبا تسعه وتسعه واش يعني\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk199.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk199.wav'},
 {'text': 'لايطاب نستعمل واش صرا من قبل بلا ما نكون خططت لها من قبل يعني كان كانت الامور متسلسله\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk52.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk52.wav'},
 {'text': 'وبايتين الليل كامل يندبوا فوق راسه كان جدي مكفن كفنوه في السبيطار وجابوه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk321.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk321.wav'},
 {'text': 'البراند تاعي ا ولا التعاقد مع دي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio003-chunk906.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio003-chunk906.wav'},
 {'text': 'ايوب كيفاش تتعامل مع الضغط اللي يجيك من العائله تاعك سيغتو لي باغون تاعك\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio012-chunk283.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio012-chunk283.wav'},
 {'text': 'مي هو يتخبى مور الرجال هذاك النهار الحومه كاع شافتني انا وماما واقفين عند دارهم برا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio010-chunk144.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio010-chunk144.wav'},
 {'text': 'بيناتهم سكلابيليتي حفظ باسكو عندك وقت ليميتي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio022-chunk192.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio022-chunk192.wav'},
 {'text': 'فوالاك الهدف تاعك كبير اكزاكتمون كي تكون انت حاب تجيب 18 ولا 19 ش معنتها معها تقولشي لازم\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk411.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk411.wav'},
 {'text': 'حتى حتىكط اني ماني سانكيام مani قريب نكمل باش هذا هو الطاقه الشمسيه هو\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk151.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk151.wav'},
 {'text': 'حامل كاس افريقيا اول مره تدخل بلادك بكاس افريقيا في يدك وهذه هي كانت\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio021-chunk252.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio021-chunk252.wav'},
 {'text': 'يمشي بحثت لي 400 وخلات الباقي عند هذك قلت لي دي 200 غيريبان ندور ناكل\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio002-chunk227.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio002-chunk227.wav'},
 {'text': 'غدوه ليفينمون ذاك يخلص يبقى داير قهوه في في الصحراء هكذاك ولا ما عندها ما عندها حتى واحد لهذا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio017-chunk232.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio017-chunk232.wav'},
 {'text': 'خدام خدام خدام عليه انت ديستيس انت معلم انا نرفد عليه ديزاستيس\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio019-chunk49.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio019-chunk49.wav'},
 {'text': 'عن خصنا عن كوراج يح يقرا عندي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio001-chunk179.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio001-chunk179.wav'},
 {'text': 'يتكون داخل الجزائر ويخدم يمشي في وشنو هو الحاجه اللي راه حاليا راهي تبلوكي يعني راه يدير\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio018-chunk213.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio018-chunk213.wav'},
 {'text': 'ملي تزيد وانت في وسط الدومين تاع الدم غدو العزيز انا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio019-chunk343.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio019-chunk343.wav'},
 {'text': 'باسبور ويركب طياره ويروح لا بوطي لا حرقه لا والو يعني كيفاش نقدر كريم روح كريم\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio017-chunk35.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio017-chunk35.wav'},
 {'text': 'الحمد لله كاين ناس ما با اكزومبل او مع الكوميرسيال بلاك ما يعجبوا حتى بيسي يكون خارج نخرج ليه أنا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk230.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk230.wav'},
 {'text': 'في السجود مادعيتش ربي لوين راني واصلني حشمت\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio019-chunk225.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio019-chunk225.wav'},
 {'text': 'تعامل انت مع هذا الكليون هذول نكون بروفيسيونيل او ماكسيموم\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk260.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk260.wav'},
 {'text': 'القول لا كونكونس تاعي في اني ما عنديش كونكيرونس\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk318.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk318.wav'},
 {'text': 'لله ما بخل علي بوالو دونك من هذا المنبر نوجه له تحيه يعطيه الصحه بارك الله فيه تعلمت وليت نخدم وليت نفلاشي بيوس وليت نافونسي وليت افونسيت\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk161.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk161.wav'},
 {'text': 'بصح ما نقولوش راك حب ازوس بصح دال\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio015-chunk309.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio015-chunk309.wav'},
 {'text': 'على بالنا الغاز و واستنشقوا عفوا جدي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk282.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio008-chunk282.wav'},
 {'text': 'جا سويمات بديت نريح شويه وبديت نرجع نورمال ورجعت لخدمتي\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio010-chunk81.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio010-chunk81.wav'},
 {'text': 'معكم منصر ايوب شعبه علوم التجريبيه\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio012-chunk17.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio012-chunk17.wav'},
 {'text': 'مي ساديبونك لاحق صح ماكينش قاعده ما يقولوا كش قاعده\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio014-chunk260.wav',
  'speaker_name': 'ljspeech',
  'root_path': '/content/gdrive/MyDrive/data/dataset22050',
  'language': 'ar',
  'audio_unique_name': '#audio014-chunk260.wav'},
 {'text': 'اكيد كانت تديني باش نعس خوتي وكانوا خوتي بداو يكبروا\n',
  'audio_file': '/content/gdrive/MyDrive/data/dataset22050/audio008-chunk102.wav',
  'speaker_name': 'ljspeech',

In [ ]:
trainer = Trainer(
    TrainerArgs(
        restore_path=None,
        skip_train_epoch=False,
        start_with_eval=START_WITH_EVAL,
        grad_accum_steps=GRAD_ACUMM_STEPS,
    ),
    config,
    output_path=OUT_PATH,
    model=model,
    train_samples=train_samples,
    eval_samples=eval_samples,
)

 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 2
 | > Num. of Torch Threads: 1
 | > Torch seed: 1
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
wandb: Currently logged in as: ba-alasmar (ba-alasmar-nit) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

 > Model has 518442047 parameters

========Ignoring artifact: colab_kernel_launcher.py /usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py========

In [ ]:
trainer.fit()

 > EPOCH: 0/15
 --> /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000
/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(

 > TRAINING (2025-05-17 15:59:45)

 > Sampling by language: dict_keys(['ar'])

   --> TIME: 2025-05-17 15:59:51 -- STEP: 0/6836 -- GLOBAL_STEP: 0
     | > loss_text_ce: 0.03566084802150726  (0.03566084802150726)
     | > loss_mel_ce: 5.313497066497803  (5.313497066497803)
     | > loss: 5.349157810211182  (5.349157810211182)
     | > grad_norm: 0  (0)
     | > current_lr: 5e-06
     | > step_time: 1.0539  (1.0539155006408691)
     | > loader_time: 4.8074  (4.807368516921997)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 16:00:13 -- STEP: 50/6836 -- GLOBAL_STEP: 50
     | > loss_text_ce: 0.034941576421260834  (0.03797326721251011)
     | > loss_mel_ce: 4.0569586753845215  (4.664744691848756)
     | > loss: 4.09190034866333  (4.702717962265013)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1232  (0.20881531715393067)
     | > loader_time: 0.0101  (0.020718669891357427)


   --> TIME: 2025-05-17 16:00:36 -- STEP: 100/6836 -- GLOBAL_STEP: 100
     | > loss_text_ce: 0.037045981734991074  (0.03701728634536265)
     | > loss_mel_ce: 4.7475481033325195  (4.588584575653078)
     | > loss: 4.7845940589904785  (4.6256018638610845)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1825  (0.19590365409851074)
     | > loader_time: 0.0097  (0.019837386608123782)


   --> TIME: 2025-05-17 16:00:58 -- STEP: 150/6836 -- GLOBAL_STEP: 150
     | > loss_text_ce: 0.033178020268678665  (0.03661398414522409)
     | > loss_mel_ce: 3.9241199493408203  (4.5415695031484)
     | > loss: 3.9572980403900146  (4.578183480898537)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1284  (0.1928357203801473)
     | > loader_time: 0.0095  (0.01910579204559326)


   --> TIME: 2025-05-17 16:01:20 -- STEP: 200/6836 -- GLOBAL_STEP: 200
     | > loss_text_ce: 0.03670167177915573  (0.03617963738739488)
     | > loss_mel_ce: 4.7569990158081055  (nan)
     | > loss: 4.793700695037842  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1679  (0.19055363178253182)
     | > loader_time: 0.0095  (0.018130599260330185)


   --> TIME: 2025-05-17 16:01:43 -- STEP: 250/6836 -- GLOBAL_STEP: 250
     | > loss_text_ce: 0.03268056735396385  (0.03613244879245757)
     | > loss_mel_ce: 3.973897695541382  (nan)
     | > loss: 4.00657844543457  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1391  (0.19352080821990972)
     | > loader_time: 0.0114  (0.017495144844055156)


   --> TIME: 2025-05-17 16:02:06 -- STEP: 300/6836 -- GLOBAL_STEP: 300
     | > loss_text_ce: 0.03764740377664566  (0.036143986787647)
     | > loss_mel_ce: 4.671970844268799  (nan)
     | > loss: 4.709618091583252  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2585  (0.19451843579610203)
     | > loader_time: 0.021  (0.016851864655812565)


   --> TIME: 2025-05-17 16:02:28 -- STEP: 350/6836 -- GLOBAL_STEP: 350
     | > loss_text_ce: 0.03688909113407135  (0.03599289434828926)
     | > loss_mel_ce: 4.246379375457764  (nan)
     | > loss: 4.283268451690674  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1624  (0.1939283875056677)
     | > loader_time: 0.0098  (0.016377929959978357)


   --> TIME: 2025-05-17 16:02:51 -- STEP: 400/6836 -- GLOBAL_STEP: 400
     | > loss_text_ce: 0.033922988921403885  (0.035840141386724984)
     | > loss_mel_ce: 3.7393205165863037  (nan)
     | > loss: 3.7732434272766113  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1256  (0.19424891710281386)
     | > loader_time: 0.0102  (0.01623021900653838)


   --> TIME: 2025-05-17 16:03:14 -- STEP: 450/6836 -- GLOBAL_STEP: 450
     | > loss_text_ce: 0.0344262570142746  (0.03571597807937198)
     | > loss_mel_ce: 4.4191203117370605  (nan)
     | > loss: 4.453546524047852  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.19  (0.19465709103478337)
     | > loader_time: 0.0092  (0.01590711010826958)


   --> TIME: 2025-05-17 16:03:38 -- STEP: 500/6836 -- GLOBAL_STEP: 500
     | > loss_text_ce: 0.028165793046355247  (0.03564714705571532)
     | > loss_mel_ce: 3.712130069732666  (nan)
     | > loss: 3.740295886993408  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.219  (0.19595310020446788)
     | > loader_time: 0.0093  (0.015807426929473862)


   --> TIME: 2025-05-17 16:04:00 -- STEP: 550/6836 -- GLOBAL_STEP: 550
     | > loss_text_ce: 0.030878832563757896  (0.03551332806321706)
     | > loss_mel_ce: 3.8282907009124756  (nan)
     | > loss: 3.8591694831848145  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2156  (0.1943899861249058)
     | > loader_time: 0.0094  (0.015526710423556227)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:04:22 -- STEP: 600/6836 -- GLOBAL_STEP: 600
     | > loss_text_ce: 0.033479347825050354  (0.03539257628843187)
     | > loss_mel_ce: 3.6988890171051025  (nan)
     | > loss: 3.7323684692382812  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1486  (0.1942304066816966)
     | > loader_time: 0.0094  (0.015351022879282621)


   --> TIME: 2025-05-17 16:04:45 -- STEP: 650/6836 -- GLOBAL_STEP: 650
     | > loss_text_ce: 0.03769295662641525  (0.03529503665864467)
     | > loss_mel_ce: 4.216516017913818  (nan)
     | > loss: 4.254209041595459  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1893  (0.19422920520489023)
     | > loader_time: 0.0096  (0.015149351633512045)


   --> TIME: 2025-05-17 16:05:07 -- STEP: 700/6836 -- GLOBAL_STEP: 700
     | > loss_text_ce: 0.03421579301357269  (0.03524809000215361)
     | > loss_mel_ce: 3.853816509246826  (nan)
     | > loss: 3.8880321979522705  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1736  (0.19412606545857017)
     | > loader_time: 0.0087  (0.014923443113054538)


   --> TIME: 2025-05-17 16:05:30 -- STEP: 750/6836 -- GLOBAL_STEP: 750
     | > loss_text_ce: 0.03136038780212402  (0.03519892660776774)
     | > loss_mel_ce: 4.099304676055908  (nan)
     | > loss: 4.130664825439453  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1548  (0.19415431912740067)
     | > loader_time: 0.0097  (0.01479356638590494)


   --> TIME: 2025-05-17 16:05:52 -- STEP: 800/6836 -- GLOBAL_STEP: 800
     | > loss_text_ce: 0.030530329793691635  (0.035190610941499466)
     | > loss_mel_ce: 3.2822628021240234  (nan)
     | > loss: 3.312793016433716  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1446  (0.19366926252841946)
     | > loader_time: 0.0085  (0.014669567346572867)


   --> TIME: 2025-05-17 16:06:15 -- STEP: 850/6836 -- GLOBAL_STEP: 850
     | > loss_text_ce: 0.0360049307346344  (0.03511619484819032)
     | > loss_mel_ce: 3.754005193710327  (nan)
     | > loss: 3.7900102138519287  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1512  (0.19393409139969767)
     | > loader_time: 0.009  (0.014612899948568897)


   --> TIME: 2025-05-17 16:06:37 -- STEP: 900/6836 -- GLOBAL_STEP: 900
     | > loss_text_ce: 0.03240840509533882  (0.03502706687483525)
     | > loss_mel_ce: 4.280240058898926  (nan)
     | > loss: 4.312648296356201  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1941  (0.1930024711290995)
     | > loader_time: 0.0121  (0.014428615834977884)


   --> TIME: 2025-05-17 16:06:59 -- STEP: 950/6836 -- GLOBAL_STEP: 950
     | > loss_text_ce: 0.03305065631866455  (0.03499956184900123)
     | > loss_mel_ce: 4.912020206451416  (nan)
     | > loss: 4.945070743560791  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2434  (0.19276842569050032)
     | > loader_time: 0.0091  (0.014265727243925387)


   --> TIME: 2025-05-17 16:07:22 -- STEP: 1000/6836 -- GLOBAL_STEP: 1000
     | > loss_text_ce: 0.03193407505750656  (0.03492189549840989)
     | > loss_mel_ce: 4.0789995193481445  (nan)
     | > loss: 4.110933780670166  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2235  (0.19322340941429136)
     | > loader_time: 0.0277  (0.01417559623718261)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 16:07:44 -- STEP: 1050/6836 -- GLOBAL_STEP: 1050
     | > loss_text_ce: 0.03295030817389488  (0.0348563682039579)
     | > loss_mel_ce: 4.941671848297119  (nan)
     | > loss: 4.9746222496032715  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1668  (0.1929235104152134)
     | > loader_time: 0.0085  (0.014020676612853998)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:08:08 -- STEP: 1100/6836 -- GLOBAL_STEP: 1100
     | > loss_text_ce: 0.03426489606499672  (0.03480015473948287)
     | > loss_mel_ce: 4.042856693267822  (nan)
     | > loss: 4.077121734619141  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1855  (0.19360175436193292)
     | > loader_time: 0.0081  (0.013942925713279023)


   --> TIME: 2025-05-17 16:08:30 -- STEP: 1150/6836 -- GLOBAL_STEP: 1150
     | > loss_text_ce: 0.03566724807024002  (0.03472820872683894)
     | > loss_mel_ce: 4.41538143157959  (nan)
     | > loss: 4.451048851013184  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1285  (0.19312255693518593)
     | > loader_time: 0.0078  (0.013794970512390127)


   --> TIME: 2025-05-17 16:08:53 -- STEP: 1200/6836 -- GLOBAL_STEP: 1200
     | > loss_text_ce: 0.03583008423447609  (0.03471215829253201)
     | > loss_mel_ce: 4.113943099975586  (nan)
     | > loss: 4.149773120880127  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1322  (0.1935609199603399)
     | > loader_time: 0.0076  (0.01372366249561309)


   --> TIME: 2025-05-17 16:09:15 -- STEP: 1250/6836 -- GLOBAL_STEP: 1250
     | > loss_text_ce: 0.03864697739481926  (0.03469936726987365)
     | > loss_mel_ce: 5.564154624938965  (nan)
     | > loss: 5.60280179977417  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1847  (0.19323605003356936)
     | > loader_time: 0.0258  (0.01361956024169921)


   --> TIME: 2025-05-17 16:09:37 -- STEP: 1300/6836 -- GLOBAL_STEP: 1300
     | > loss_text_ce: 0.03462190553545952  (0.03466252521826674)
     | > loss_mel_ce: 3.6703271865844727  (nan)
     | > loss: 3.704949140548706  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1658  (0.19326392925702604)
     | > loader_time: 0.0094  (0.01349937255565936)


   --> TIME: 2025-05-17 16:10:00 -- STEP: 1350/6836 -- GLOBAL_STEP: 1350
     | > loss_text_ce: 0.03603244572877884  (0.03460509417371618)
     | > loss_mel_ce: 4.062878608703613  (nan)
     | > loss: 4.098911285400391  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2629  (0.19331261140328868)
     | > loader_time: 0.0112  (0.013387553780167183)


   --> TIME: 2025-05-17 16:10:23 -- STEP: 1400/6836 -- GLOBAL_STEP: 1400
     | > loss_text_ce: 0.03228909894824028  (0.034557836333821965)
     | > loss_mel_ce: 5.007630825042725  (nan)
     | > loss: 5.039919853210449  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1904  (0.19337060298238481)
     | > loader_time: 0.0084  (0.013331889084407253)


   --> TIME: 2025-05-17 16:10:45 -- STEP: 1450/6836 -- GLOBAL_STEP: 1450
     | > loss_text_ce: 0.034467440098524094  (0.034541661818993534)
     | > loss_mel_ce: 3.822110652923584  (nan)
     | > loss: 3.8565781116485596  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1917  (0.19317378520965575)
     | > loader_time: 0.0092  (0.013315448596559714)


   --> TIME: 2025-05-17 16:11:08 -- STEP: 1500/6836 -- GLOBAL_STEP: 1500
     | > loss_text_ce: 0.030458148568868637  (0.03450271071741982)
     | > loss_mel_ce: 3.656167984008789  (nan)
     | > loss: 3.6866261959075928  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2064  (0.19333923117319743)
     | > loader_time: 0.0098  (0.013231781164805088)


   --> TIME: 2025-05-17 16:11:31 -- STEP: 1550/6836 -- GLOBAL_STEP: 1550
     | > loss_text_ce: 0.03434057906270027  (0.03446526746235551)
     | > loss_mel_ce: 3.1366631984710693  (nan)
     | > loss: 3.171003818511963  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1632  (0.19340751955586094)
     | > loader_time: 0.012  (0.013224693421394587)


   --> TIME: 2025-05-17 16:11:53 -- STEP: 1600/6836 -- GLOBAL_STEP: 1600
     | > loss_text_ce: 0.03441509231925011  (0.03444712112308482)
     | > loss_mel_ce: 2.9062399864196777  (nan)
     | > loss: 2.940654993057251  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.176  (0.1934454023838043)
     | > loader_time: 0.0282  (0.013142179399728768)


   --> TIME: 2025-05-17 16:12:15 -- STEP: 1650/6836 -- GLOBAL_STEP: 1650
     | > loss_text_ce: 0.033388156443834305  (0.03441917662141907)
     | > loss_mel_ce: 3.5334689617156982  (nan)
     | > loss: 3.566857099533081  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1859  (0.19340711347984546)
     | > loader_time: 0.0091  (0.01308938720009543)


   --> TIME: 2025-05-17 16:12:39 -- STEP: 1700/6836 -- GLOBAL_STEP: 1700
     | > loss_text_ce: 0.030156420543789864  (0.03438942678163161)
     | > loss_mel_ce: 3.7477495670318604  (nan)
     | > loss: 3.7779059410095215  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1836  (0.19367810712141148)
     | > loader_time: 0.0109  (0.01305067384944242)


   --> TIME: 2025-05-17 16:13:01 -- STEP: 1750/6836 -- GLOBAL_STEP: 1750
     | > loss_text_ce: 0.028563862666487694  (0.034365528687834816)
     | > loss_mel_ce: 3.25211501121521  (nan)
     | > loss: 3.2806789875030518  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.168  (0.1935924893787929)
     | > loader_time: 0.0098  (0.01297747693743024)


   --> TIME: 2025-05-17 16:13:24 -- STEP: 1800/6836 -- GLOBAL_STEP: 1800
     | > loss_text_ce: 0.03472896292805672  (0.034330242534892516)
     | > loss_mel_ce: 4.006682872772217  (nan)
     | > loss: 4.041411876678467  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1258  (0.19355409423510234)
     | > loader_time: 0.0096  (0.012939773665534119)


   --> TIME: 2025-05-17 16:13:46 -- STEP: 1850/6836 -- GLOBAL_STEP: 1850
     | > loss_text_ce: 0.03226057440042496  (0.03429167951079647)
     | > loss_mel_ce: 4.006707668304443  (nan)
     | > loss: 4.038968086242676  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3181  (0.19361368269533724)
     | > loader_time: 0.0105  (0.012897773433375998)


   --> TIME: 2025-05-17 16:14:09 -- STEP: 1900/6836 -- GLOBAL_STEP: 1900
     | > loss_text_ce: 0.033070795238018036  (0.034258706922593946)
     | > loss_mel_ce: nan  (nan)
     | > loss: nan  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1423  (0.19368944481799477)
     | > loader_time: 0.0109  (0.012887572991220569)


   --> TIME: 2025-05-17 16:14:32 -- STEP: 1950/6836 -- GLOBAL_STEP: 1950
     | > loss_text_ce: 0.02997351624071598  (0.03420979424260373)
     | > loss_mel_ce: 4.803302764892578  (nan)
     | > loss: 4.833276271820068  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1953  (0.19373294610243577)
     | > loader_time: 0.0243  (0.012856689477578183)


   --> TIME: 2025-05-17 16:14:56 -- STEP: 2000/6836 -- GLOBAL_STEP: 2000
     | > loss_text_ce: 0.031271934509277344  (0.03418900127895184)
     | > loss_mel_ce: 4.240396499633789  (nan)
     | > loss: 4.271668434143066  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2353  (0.1941771512031555)
     | > loader_time: 0.0106  (0.012831519961357112)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 16:15:18 -- STEP: 2050/6836 -- GLOBAL_STEP: 2050
     | > loss_text_ce: 0.028956670314073563  (0.034175946475347434)
     | > loss_mel_ce: 3.916476249694824  (nan)
     | > loss: 3.9454329013824463  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2657  (0.19405211704533273)
     | > loader_time: 0.0113  (0.01279353095263969)


   --> TIME: 2025-05-17 16:15:40 -- STEP: 2100/6836 -- GLOBAL_STEP: 2100
     | > loss_text_ce: 0.03723778948187828  (0.03415424171835191)
     | > loss_mel_ce: 4.667999267578125  (nan)
     | > loss: 4.705236911773682  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.168  (0.19378730410621278)
     | > loader_time: 0.0116  (0.012759198915390735)


   --> TIME: 2025-05-17 16:16:03 -- STEP: 2150/6836 -- GLOBAL_STEP: 2150
     | > loss_text_ce: 0.034274838864803314  (0.034135445586817276)
     | > loss_mel_ce: 3.8701157569885254  (nan)
     | > loss: 3.904390573501587  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1446  (0.19394706559735675)
     | > loader_time: 0.01  (0.01274911159692808)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:16:26 -- STEP: 2200/6836 -- GLOBAL_STEP: 2200
     | > loss_text_ce: 0.03864084929227829  (0.03411650831726469)
     | > loss_mel_ce: 4.015738487243652  (nan)
     | > loss: 4.054379463195801  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1637  (0.19404351039366283)
     | > loader_time: 0.0182  (0.012727323228662657)


   --> TIME: 2025-05-17 16:16:49 -- STEP: 2250/6836 -- GLOBAL_STEP: 2250
     | > loss_text_ce: 0.03218894824385643  (0.03409274521801211)
     | > loss_mel_ce: 4.078286647796631  (nan)
     | > loss: 4.110475540161133  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1486  (0.1941656917995875)
     | > loader_time: 0.0083  (0.012702201525370277)


   --> TIME: 2025-05-17 16:17:11 -- STEP: 2300/6836 -- GLOBAL_STEP: 2300
     | > loss_text_ce: 0.03058994933962822  (0.03406314291626866)
     | > loss_mel_ce: 2.4829394817352295  (nan)
     | > loss: 2.5135295391082764  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2129  (0.1941254893593164)
     | > loader_time: 0.0092  (0.012686974691308056)


   --> TIME: 2025-05-17 16:17:33 -- STEP: 2350/6836 -- GLOBAL_STEP: 2350
     | > loss_text_ce: 0.02662290446460247  (0.034036623882328)
     | > loss_mel_ce: 4.977328777313232  (nan)
     | > loss: 5.003951549530029  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1877  (0.19396208925450076)
     | > loader_time: 0.0088  (0.012648956724937915)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:17:56 -- STEP: 2400/6836 -- GLOBAL_STEP: 2400
     | > loss_text_ce: 0.034087929874658585  (0.03399960563207671)
     | > loss_mel_ce: 4.3874125480651855  (nan)
     | > loss: 4.4215006828308105  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2565  (0.19401731580495812)
     | > loader_time: 0.0103  (0.01262891908486683)


   --> TIME: 2025-05-17 16:18:19 -- STEP: 2450/6836 -- GLOBAL_STEP: 2450
     | > loss_text_ce: 0.032533057034015656  (0.0339718814832824)
     | > loss_mel_ce: 4.4468183517456055  (nan)
     | > loss: 4.47935152053833  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3206  (0.19401636931360963)
     | > loader_time: 0.0423  (0.012609639265099334)


   --> TIME: 2025-05-17 16:18:42 -- STEP: 2500/6836 -- GLOBAL_STEP: 2500
     | > loss_text_ce: 0.02825009450316429  (0.03394542899951343)
     | > loss_mel_ce: 4.662589073181152  (nan)
     | > loss: 4.6908392906188965  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2273  (0.19418271818160987)
     | > loader_time: 0.0097  (0.012579529285430886)


   --> TIME: 2025-05-17 16:19:05 -- STEP: 2550/6836 -- GLOBAL_STEP: 2550
     | > loss_text_ce: 0.039167363196611404  (0.03394101649814965)
     | > loss_mel_ce: 3.3542027473449707  (nan)
     | > loss: 3.3933701515197754  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1549  (0.19429024715049562)
     | > loader_time: 0.0102  (0.012547954765020616)


   --> TIME: 2025-05-17 16:19:27 -- STEP: 2600/6836 -- GLOBAL_STEP: 2600
     | > loss_text_ce: 0.03585265204310417  (0.033910715405900946)
     | > loss_mel_ce: 3.843000888824463  (nan)
     | > loss: 3.8788535594940186  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2126  (0.1941395275409402)
     | > loader_time: 0.0105  (0.012508674584902233)


   --> TIME: 2025-05-17 16:19:50 -- STEP: 2650/6836 -- GLOBAL_STEP: 2650
     | > loss_text_ce: 0.030178243294358253  (0.03389177821787465)
     | > loss_mel_ce: 3.013941526412964  (nan)
     | > loss: 3.0441198348999023  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1709  (0.1942346366846334)
     | > loader_time: 0.009  (0.012472890188109183)


   --> TIME: 2025-05-17 16:20:13 -- STEP: 2700/6836 -- GLOBAL_STEP: 2700
     | > loss_text_ce: 0.03262428566813469  (0.03389173745833065)
     | > loss_mel_ce: 3.618236541748047  (nan)
     | > loss: 3.6508607864379883  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2009  (0.19444779272432655)
     | > loader_time: 0.0272  (0.012454080758271377)


   --> TIME: 2025-05-17 16:20:36 -- STEP: 2750/6836 -- GLOBAL_STEP: 2750
     | > loss_text_ce: 0.030462129041552544  (0.0338760763643818)
     | > loss_mel_ce: nan  (nan)
     | > loss: nan  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1435  (0.19440150044181106)
     | > loader_time: 0.0092  (0.012416899767788958)


   --> TIME: 2025-05-17 16:20:58 -- STEP: 2800/6836 -- GLOBAL_STEP: 2800
     | > loss_text_ce: 0.03575935587286949  (0.03386149834109741)
     | > loss_mel_ce: 3.4733569622039795  (nan)
     | > loss: 3.5091164112091064  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1708  (0.19426391482353186)
     | > loader_time: 0.0098  (0.012395660536629797)


   --> TIME: 2025-05-17 16:21:20 -- STEP: 2850/6836 -- GLOBAL_STEP: 2850
     | > loss_text_ce: 0.03514958545565605  (0.03382767961670961)
     | > loss_mel_ce: 3.921998977661133  (nan)
     | > loss: 3.957148551940918  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2005  (0.19412503409803936)
     | > loader_time: 0.009  (0.012346965304592184)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:21:43 -- STEP: 2900/6836 -- GLOBAL_STEP: 2900
     | > loss_text_ce: 0.03182246908545494  (0.03382125823790663)
     | > loss_mel_ce: 3.88602352142334  (nan)
     | > loss: 3.9178459644317627  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1658  (0.1942023291258974)
     | > loader_time: 0.0097  (0.012329945235416792)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:22:05 -- STEP: 2950/6836 -- GLOBAL_STEP: 2950
     | > loss_text_ce: 0.03003097139298916  (0.03378803525814571)
     | > loss_mel_ce: 4.775743007659912  (nan)
     | > loss: 4.805774211883545  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2015  (0.19422308590452528)
     | > loader_time: 0.0197  (0.012309874680082662)


   --> TIME: 2025-05-17 16:22:29 -- STEP: 3000/6836 -- GLOBAL_STEP: 3000
     | > loss_text_ce: 0.028977490961551666  (0.033764635970195196)
     | > loss_mel_ce: 4.41019344329834  (nan)
     | > loss: 4.439170837402344  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1829  (0.19437150526046731)
     | > loader_time: 0.0096  (0.012284465551376328)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 16:22:52 -- STEP: 3050/6836 -- GLOBAL_STEP: 3050
     | > loss_text_ce: 0.030421826988458633  (0.03375079250299056)
     | > loss_mel_ce: 4.226475715637207  (nan)
     | > loss: 4.256897449493408  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1315  (0.19451495874123473)
     | > loader_time: 0.0093  (0.01227874075780148)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:23:15 -- STEP: 3100/6836 -- GLOBAL_STEP: 3100
     | > loss_text_ce: 0.03327353298664093  (0.033735707697248304)
     | > loss_mel_ce: 3.9825048446655273  (nan)
     | > loss: 4.015778541564941  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2189  (0.19456286914886944)
     | > loader_time: 0.0262  (0.012270602718476312)


   --> TIME: 2025-05-17 16:23:37 -- STEP: 3150/6836 -- GLOBAL_STEP: 3150
     | > loss_text_ce: 0.03262686729431152  (0.033732040134805574)
     | > loss_mel_ce: 3.713303565979004  (nan)
     | > loss: 3.7459304332733154  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1334  (0.1944454258964173)
     | > loader_time: 0.0085  (0.012248564977494483)


   --> TIME: 2025-05-17 16:23:59 -- STEP: 3200/6836 -- GLOBAL_STEP: 3200
     | > loss_text_ce: 0.03215501829981804  (0.033707789856707686)
     | > loss_mel_ce: 4.054730415344238  (nan)
     | > loss: 4.086885452270508  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2175  (0.1943864998221395)
     | > loader_time: 0.0088  (0.012233917415142046)


   --> TIME: 2025-05-17 16:24:22 -- STEP: 3250/6836 -- GLOBAL_STEP: 3250
     | > loss_text_ce: 0.030933191999793053  (0.03369929640281661)
     | > loss_mel_ce: 4.261354446411133  (nan)
     | > loss: 4.292287826538086  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.126  (0.19432417047940748)
     | > loader_time: 0.0093  (0.012196956121004531)


   --> TIME: 2025-05-17 16:24:44 -- STEP: 3300/6836 -- GLOBAL_STEP: 3300
     | > loss_text_ce: 0.033148523420095444  (0.0336820159496909)
     | > loss_mel_ce: 3.205915689468384  (nan)
     | > loss: 3.2390642166137695  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1793  (0.19434377150102075)
     | > loader_time: 0.0079  (0.012189237493457203)


   --> TIME: 2025-05-17 16:25:07 -- STEP: 3350/6836 -- GLOBAL_STEP: 3350
     | > loss_text_ce: 0.030709780752658844  (0.03367518991732334)
     | > loss_mel_ce: 4.323788642883301  (nan)
     | > loss: 4.354498386383057  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2598  (0.1942388998572504)
     | > loader_time: 0.014  (0.012169581313631415)


   --> TIME: 2025-05-17 16:25:29 -- STEP: 3400/6836 -- GLOBAL_STEP: 3400
     | > loss_text_ce: 0.02889595925807953  (0.03367237225503611)
     | > loss_mel_ce: 3.879171371459961  (nan)
     | > loss: 3.908067226409912  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1314  (0.19419642834102385)
     | > loader_time: 0.0089  (0.012135574326795677)


   --> TIME: 2025-05-17 16:25:51 -- STEP: 3450/6836 -- GLOBAL_STEP: 3450
     | > loss_text_ce: 0.03458501026034355  (0.03366426477991591)
     | > loss_mel_ce: 3.855803966522217  (nan)
     | > loss: 3.8903889656066895  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1731  (0.19413136268007564)
     | > loader_time: 0.0075  (0.012140264165574214)


   --> TIME: 2025-05-17 16:26:14 -- STEP: 3500/6836 -- GLOBAL_STEP: 3500
     | > loss_text_ce: 0.03377700597047806  (0.033659024730324824)
     | > loss_mel_ce: 3.5082457065582275  (nan)
     | > loss: 3.542022705078125  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1351  (0.19416172804151244)
     | > loader_time: 0.009  (0.012113589831760939)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:26:36 -- STEP: 3550/6836 -- GLOBAL_STEP: 3550
     | > loss_text_ce: 0.03482043743133545  (0.033648904707335316)
     | > loss_mel_ce: 4.7229228019714355  (nan)
     | > loss: 4.7577433586120605  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1786  (0.19418802026291948)
     | > loader_time: 0.0091  (0.012123523631565995)


   --> TIME: 2025-05-17 16:27:00 -- STEP: 3600/6836 -- GLOBAL_STEP: 3600
     | > loss_text_ce: 0.030288593843579292  (0.033632275811914)
     | > loss_mel_ce: 5.524889945983887  (nan)
     | > loss: 5.555178642272949  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1934  (0.1943612391418879)
     | > loader_time: 0.0228  (0.012125547991858577)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:27:23 -- STEP: 3650/6836 -- GLOBAL_STEP: 3650
     | > loss_text_ce: 0.03214123845100403  (0.03362087264503934)
     | > loss_mel_ce: 3.8230984210968018  (nan)
     | > loss: 3.8552396297454834  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1706  (0.19437497557026048)
     | > loader_time: 0.0095  (0.012105351278226657)


   --> TIME: 2025-05-17 16:27:46 -- STEP: 3700/6836 -- GLOBAL_STEP: 3700
     | > loss_text_ce: 0.03887971490621567  (0.03360598705255909)
     | > loss_mel_ce: 4.200409412384033  (nan)
     | > loss: 4.239289283752441  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1644  (0.1944060777329108)
     | > loader_time: 0.0095  (0.01211758587811443)


   --> TIME: 2025-05-17 16:28:08 -- STEP: 3750/6836 -- GLOBAL_STEP: 3750
     | > loss_text_ce: 0.030565205961465836  (0.03359035906593009)
     | > loss_mel_ce: 4.2067952156066895  (nan)
     | > loss: 4.23736047744751  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2045  (0.19434066390991192)
     | > loader_time: 0.0084  (0.012098872311909982)


   --> TIME: 2025-05-17 16:28:31 -- STEP: 3800/6836 -- GLOBAL_STEP: 3800
     | > loss_text_ce: 0.03136453032493591  (0.0335793034506864)
     | > loss_mel_ce: nan  (nan)
     | > loss: nan  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1719  (0.1943293957333814)
     | > loader_time: 0.0099  (0.012078992944014688)


   --> TIME: 2025-05-17 16:28:53 -- STEP: 3850/6836 -- GLOBAL_STEP: 3850
     | > loss_text_ce: 0.0324004590511322  (0.03357396949130996)
     | > loss_mel_ce: 3.2734456062316895  (nan)
     | > loss: 3.3058459758758545  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2111  (0.19422443135992257)
     | > loader_time: 0.0072  (0.012061627994884134)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:29:16 -- STEP: 3900/6836 -- GLOBAL_STEP: 3900
     | > loss_text_ce: 0.03336301073431969  (0.03355524666702903)
     | > loss_mel_ce: 3.657041072845459  (nan)
     | > loss: 3.690404176712036  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1267  (0.19425176730522725)
     | > loader_time: 0.0101  (0.012042517539782392)


   --> TIME: 2025-05-17 16:29:39 -- STEP: 3950/6836 -- GLOBAL_STEP: 3950
     | > loss_text_ce: 0.029577845707535744  (0.03353474031379331)
     | > loss_mel_ce: 3.445002794265747  (nan)
     | > loss: 3.4745805263519287  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1382  (0.19439533547510057)
     | > loader_time: 0.0093  (0.012059101153023624)


   --> TIME: 2025-05-17 16:30:02 -- STEP: 4000/6836 -- GLOBAL_STEP: 4000
     | > loss_text_ce: 0.03450154513120651  (0.0335283264005557)
     | > loss_mel_ce: 2.9584624767303467  (nan)
     | > loss: 2.992964029312134  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2371  (0.1943923508524893)
     | > loader_time: 0.0121  (0.012047237038612355)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 16:30:24 -- STEP: 4050/6836 -- GLOBAL_STEP: 4050
     | > loss_text_ce: 0.03330684453248978  (0.03351887560185094)
     | > loss_mel_ce: 3.414029598236084  (nan)
     | > loss: 3.447336435317993  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2119  (0.19434416800369433)
     | > loader_time: 0.0096  (0.012031030242825721)


   --> TIME: 2025-05-17 16:30:47 -- STEP: 4100/6836 -- GLOBAL_STEP: 4100
     | > loss_text_ce: 0.0324360728263855  (0.033513383586414)
     | > loss_mel_ce: 4.0309858322143555  (nan)
     | > loss: 4.063421726226807  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2252  (0.19448258731423337)
     | > loader_time: 0.0261  (0.012022412811837534)


   --> TIME: 2025-05-17 16:31:10 -- STEP: 4150/6836 -- GLOBAL_STEP: 4150
     | > loss_text_ce: 0.03476903960108757  (0.033503621953977186)
     | > loss_mel_ce: 4.334961414337158  (nan)
     | > loss: 4.369730472564697  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2724  (0.19448242698807297)
     | > loader_time: 0.0141  (0.012012684776122301)


   --> TIME: 2025-05-17 16:31:33 -- STEP: 4200/6836 -- GLOBAL_STEP: 4200
     | > loss_text_ce: 0.03506546467542648  (0.033489736747883636)
     | > loss_mel_ce: 3.892103910446167  (nan)
     | > loss: 3.9271693229675293  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1402  (0.19443034069878698)
     | > loader_time: 0.0128  (0.01199652847789582)


   --> TIME: 2025-05-17 16:31:55 -- STEP: 4250/6836 -- GLOBAL_STEP: 4250
     | > loss_text_ce: 0.037937507033348083  (0.03348056800575819)
     | > loss_mel_ce: 3.5333139896392822  (nan)
     | > loss: 3.571251392364502  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1768  (0.19442915888393614)
     | > loader_time: 0.0226  (0.01199114087048698)


   --> TIME: 2025-05-17 16:32:18 -- STEP: 4300/6836 -- GLOBAL_STEP: 4300
     | > loss_text_ce: 0.029020819813013077  (0.03346591762028808)
     | > loss_mel_ce: 4.4202752113342285  (nan)
     | > loss: 4.449295997619629  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1767  (0.1943525675285693)
     | > loader_time: 0.008  (0.01198240867880887)


   --> TIME: 2025-05-17 16:32:41 -- STEP: 4350/6836 -- GLOBAL_STEP: 4350
     | > loss_text_ce: 0.028600718826055527  (0.03346190002029654)
     | > loss_mel_ce: 4.258323669433594  (nan)
     | > loss: 4.286924362182617  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1725  (0.19441436427763129)
     | > loader_time: 0.0099  (0.01197523204759619)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:33:04 -- STEP: 4400/6836 -- GLOBAL_STEP: 4400
     | > loss_text_ce: 0.037881627678871155  (0.033453164417296635)
     | > loss_mel_ce: 4.8504719734191895  (nan)
     | > loss: 4.8883538246154785  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1569  (0.194486865563826)
     | > loader_time: 0.0098  (0.011967400204051615)


   --> TIME: 2025-05-17 16:33:27 -- STEP: 4450/6836 -- GLOBAL_STEP: 4450
     | > loss_text_ce: 0.034856557846069336  (0.03344097832196882)
     | > loss_mel_ce: 3.5238938331604004  (nan)
     | > loss: 3.5587503910064697  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1724  (0.1945316763138502)
     | > loader_time: 0.0093  (0.01196398927924337)


   --> TIME: 2025-05-17 16:33:49 -- STEP: 4500/6836 -- GLOBAL_STEP: 4500
     | > loss_text_ce: 0.02950700744986534  (0.03342626159265637)
     | > loss_mel_ce: 4.402060031890869  (nan)
     | > loss: 4.431567192077637  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1727  (0.19450852611329816)
     | > loader_time: 0.0086  (0.011943373945024257)


   --> TIME: 2025-05-17 16:34:11 -- STEP: 4550/6836 -- GLOBAL_STEP: 4550
     | > loss_text_ce: 0.03096003271639347  (0.033415011823341105)
     | > loss_mel_ce: 4.197218418121338  (nan)
     | > loss: 4.22817850112915  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1233  (0.19440406364398988)
     | > loader_time: 0.0094  (0.011922752831008385)


   --> TIME: 2025-05-17 16:34:34 -- STEP: 4600/6836 -- GLOBAL_STEP: 4600
     | > loss_text_ce: 0.027487969025969505  (0.03340298864302109)
     | > loss_mel_ce: 2.9279603958129883  (nan)
     | > loss: 2.9554483890533447  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1502  (0.19437286786411112)
     | > loader_time: 0.0092  (0.011908967805945333)


   --> TIME: 2025-05-17 16:34:57 -- STEP: 4650/6836 -- GLOBAL_STEP: 4650
     | > loss_text_ce: 0.03661557659506798  (0.03339249573768152)
     | > loss_mel_ce: 4.016908645629883  (nan)
     | > loss: 4.053524017333984  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3037  (0.1944799638563586)
     | > loader_time: 0.0193  (0.011900072815597672)


   --> TIME: 2025-05-17 16:35:19 -- STEP: 4700/6836 -- GLOBAL_STEP: 4700
     | > loss_text_ce: 0.029551072046160698  (0.03337871639612828)
     | > loss_mel_ce: 4.183415412902832  (nan)
     | > loss: 4.212966442108154  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1656  (0.1944029628469587)
     | > loader_time: 0.0086  (0.011892589812583084)


   --> TIME: 2025-05-17 16:35:42 -- STEP: 4750/6836 -- GLOBAL_STEP: 4750
     | > loss_text_ce: 0.02879916876554489  (0.03336504122340369)
     | > loss_mel_ce: nan  (nan)
     | > loss: nan  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1479  (0.19441158982327103)
     | > loader_time: 0.0084  (0.011886571382221397)


   --> TIME: 2025-05-17 16:36:05 -- STEP: 4800/6836 -- GLOBAL_STEP: 4800
     | > loss_text_ce: 0.031003102660179138  (0.03335846451693218)
     | > loss_mel_ce: 3.044654130935669  (nan)
     | > loss: 3.0756571292877197  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1375  (0.1944006582101186)
     | > loader_time: 0.0086  (0.011867604553699474)


   --> TIME: 2025-05-17 16:36:27 -- STEP: 4850/6836 -- GLOBAL_STEP: 4850
     | > loss_text_ce: 0.026723820716142654  (0.033345565207148986)
     | > loss_mel_ce: 3.7386856079101562  (nan)
     | > loss: 3.765409469604492  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1551  (0.19436205460853184)
     | > loader_time: 0.0104  (0.011859363968839331)


   --> TIME: 2025-05-17 16:36:49 -- STEP: 4900/6836 -- GLOBAL_STEP: 4900
     | > loss_text_ce: 0.033590998500585556  (0.033329289412620144)
     | > loss_mel_ce: 3.808450937271118  (nan)
     | > loss: 3.8420419692993164  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1877  (0.19432887841244129)
     | > loader_time: 0.0074  (0.01183913912091935)


   --> TIME: 2025-05-17 16:37:11 -- STEP: 4950/6836 -- GLOBAL_STEP: 4950
     | > loss_text_ce: 0.0229119174182415  (0.03331502083726608)
     | > loss_mel_ce: 3.4713709354400635  (nan)
     | > loss: 3.4942829608917236  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1967  (0.19419630252953723)
     | > loader_time: 0.0094  (0.011836105789801073)


   --> TIME: 2025-05-17 16:37:33 -- STEP: 5000/6836 -- GLOBAL_STEP: 5000
     | > loss_text_ce: 0.033043794333934784  (0.03330242391005163)
     | > loss_mel_ce: 4.213873386383057  (nan)
     | > loss: 4.246917247772217  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2081  (0.19417342429161064)
     | > loader_time: 0.01  (0.011831141614913927)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========
[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:37:55 -- STEP: 5050/6836 -- GLOBAL_STEP: 5050
     | > loss_text_ce: 0.03218770772218704  (0.03328952912351878)
     | > loss_mel_ce: 3.9243557453155518  (nan)
     | > loss: 3.956543445587158  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1453  (0.1940275787126899)
     | > loader_time: 0.0081  (0.011832645954471992)


   --> TIME: 2025-05-17 16:38:18 -- STEP: 5100/6836 -- GLOBAL_STEP: 5100
     | > loss_text_ce: 0.0318404920399189  (0.033276751644398125)
     | > loss_mel_ce: 4.413059234619141  (nan)
     | > loss: 4.444899559020996  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1767  (0.19405333808824118)
     | > loader_time: 0.01  (0.01184407767127541)


   --> TIME: 2025-05-17 16:38:41 -- STEP: 5150/6836 -- GLOBAL_STEP: 5150
     | > loss_text_ce: 0.03170958161354065  (0.03327080685898524)
     | > loss_mel_ce: 5.136007308959961  (nan)
     | > loss: 5.167716979980469  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1835  (0.19406640506485118)
     | > loader_time: 0.0223  (0.011838506356026356)


   --> TIME: 2025-05-17 16:39:03 -- STEP: 5200/6836 -- GLOBAL_STEP: 5200
     | > loss_text_ce: 0.033112265169620514  (0.03326541670669736)
     | > loss_mel_ce: 4.097120761871338  (nan)
     | > loss: 4.130232810974121  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2808  (0.19404031097888932)
     | > loader_time: 0.0098  (0.011832407437838033)


   --> TIME: 2025-05-17 16:39:26 -- STEP: 5250/6836 -- GLOBAL_STEP: 5250
     | > loss_text_ce: 0.02864278294146061  (0.03326259583447665)
     | > loss_mel_ce: 4.071948528289795  (nan)
     | > loss: 4.10059118270874  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1765  (0.19403441283816378)
     | > loader_time: 0.023  (0.011833451316470183)


   --> TIME: 2025-05-17 16:39:49 -- STEP: 5300/6836 -- GLOBAL_STEP: 5300
     | > loss_text_ce: 0.03221786767244339  (0.03325147623688265)
     | > loss_mel_ce: 4.448705196380615  (nan)
     | > loss: 4.480923175811768  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2114  (0.19403616365396742)
     | > loader_time: 0.0099  (0.011818920081516466)


   --> TIME: 2025-05-17 16:40:12 -- STEP: 5350/6836 -- GLOBAL_STEP: 5350
     | > loss_text_ce: 0.02902066893875599  (0.033241614666985005)
     | > loss_mel_ce: 3.9839746952056885  (nan)
     | > loss: 4.01299524307251  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.272  (0.19411348899948255)
     | > loader_time: 0.0102  (0.011810633088940757)


   --> TIME: 2025-05-17 16:40:34 -- STEP: 5400/6836 -- GLOBAL_STEP: 5400
     | > loss_text_ce: 0.030619945377111435  (0.03323296620717477)
     | > loss_mel_ce: 4.608758926391602  (nan)
     | > loss: 4.639379024505615  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.319  (0.19409279867454804)
     | > loader_time: 0.0299  (0.011809699976885746)


   --> TIME: 2025-05-17 16:40:57 -- STEP: 5450/6836 -- GLOBAL_STEP: 5450
     | > loss_text_ce: 0.03601684793829918  (0.03322772783218716)
     | > loss_mel_ce: 4.284479141235352  (nan)
     | > loss: 4.320496082305908  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2164  (0.19407320066329528)
     | > loader_time: 0.0092  (0.011806995496837355)


   --> TIME: 2025-05-17 16:41:19 -- STEP: 5500/6836 -- GLOBAL_STEP: 5500
     | > loss_text_ce: 0.03402414545416832  (0.0332265985956923)
     | > loss_mel_ce: 3.1642894744873047  (nan)
     | > loss: 3.1983137130737305  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1935  (0.19412042062932786)
     | > loader_time: 0.0091  (0.01179395081780172)


   --> TIME: 2025-05-17 16:41:42 -- STEP: 5550/6836 -- GLOBAL_STEP: 5550
     | > loss_text_ce: 0.03402232751250267  (0.03322139931053991)
     | > loss_mel_ce: 3.9040462970733643  (nan)
     | > loss: 3.9380686283111572  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1884  (0.1941347593444961)
     | > loader_time: 0.0106  (0.011776607960194065)


   --> TIME: 2025-05-17 16:42:05 -- STEP: 5600/6836 -- GLOBAL_STEP: 5600
     | > loss_text_ce: 0.030589140951633453  (0.03321516254351339)
     | > loss_mel_ce: 3.5078341960906982  (nan)
     | > loss: 3.5384232997894287  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2541  (0.19417037065540033)
     | > loader_time: 0.0092  (0.011768386832305348)


   --> TIME: 2025-05-17 16:42:28 -- STEP: 5650/6836 -- GLOBAL_STEP: 5650
     | > loss_text_ce: 0.03381398692727089  (0.033215587238360794)
     | > loss_mel_ce: 4.324970245361328  (nan)
     | > loss: 4.358784198760986  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2379  (0.19421724585305264)
     | > loader_time: 0.0221  (0.011760275638208965)


   --> TIME: 2025-05-17 16:42:51 -- STEP: 5700/6836 -- GLOBAL_STEP: 5700
     | > loss_text_ce: 0.030646400526165962  (0.03320365393566982)
     | > loss_mel_ce: 4.470450401306152  (nan)
     | > loss: 4.501096725463867  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3247  (0.19432267916829954)
     | > loader_time: 0.0107  (0.011761351300958987)


   --> TIME: 2025-05-17 16:43:14 -- STEP: 5750/6836 -- GLOBAL_STEP: 5750
     | > loss_text_ce: 0.03168194368481636  (0.03319490106079889)
     | > loss_mel_ce: 4.877464294433594  (nan)
     | > loss: 4.909146308898926  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2667  (0.1943376324695089)
     | > loader_time: 0.0097  (0.011769758183023189)


   --> TIME: 2025-05-17 16:43:37 -- STEP: 5800/6836 -- GLOBAL_STEP: 5800
     | > loss_text_ce: 0.030754391103982925  (0.03318185766677148)
     | > loss_mel_ce: 3.741452932357788  (nan)
     | > loss: 3.772207260131836  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2074  (0.19438425762899983)
     | > loader_time: 0.0093  (0.011766427549822562)


   --> TIME: 2025-05-17 16:44:00 -- STEP: 5850/6836 -- GLOBAL_STEP: 5850
     | > loss_text_ce: 0.027977026998996735  (0.03317570132004399)
     | > loss_mel_ce: 3.4663710594177246  (nan)
     | > loss: 3.4943480491638184  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1537  (0.19437680211841543)
     | > loader_time: 0.0093  (0.011769309818235204)


   --> TIME: 2025-05-17 16:44:22 -- STEP: 5900/6836 -- GLOBAL_STEP: 5900
     | > loss_text_ce: 0.030490461736917496  (0.033161636148658344)
     | > loss_mel_ce: 4.3361968994140625  (nan)
     | > loss: 4.366687297821045  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2239  (0.1943735881983223)
     | > loader_time: 0.0234  (0.011768494824231666)


   --> TIME: 2025-05-17 16:44:45 -- STEP: 5950/6836 -- GLOBAL_STEP: 5950
     | > loss_text_ce: 0.033544257283210754  (0.03315143617104835)
     | > loss_mel_ce: 4.2863922119140625  (nan)
     | > loss: 4.319936275482178  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2317  (0.19444170599224178)
     | > loader_time: 0.0122  (0.011754452961833523)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:45:08 -- STEP: 6000/6836 -- GLOBAL_STEP: 6000
     | > loss_text_ce: 0.030778851360082626  (0.033141130077963085)
     | > loss_mel_ce: 3.42569637298584  (nan)
     | > loss: 3.456475257873535  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.155  (0.19449292560418438)
     | > loader_time: 0.0089  (0.01175070969263711)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 16:45:31 -- STEP: 6050/6836 -- GLOBAL_STEP: 6050
     | > loss_text_ce: 0.03142857924103737  (0.03313626474831718)
     | > loss_mel_ce: 4.794544219970703  (nan)
     | > loss: 4.825973033905029  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.196  (0.19451662426152497)
     | > loader_time: 0.0197  (0.011757078840712856)


   --> TIME: 2025-05-17 16:45:53 -- STEP: 6100/6836 -- GLOBAL_STEP: 6100
     | > loss_text_ce: 0.03210563212633133  (0.033122080706792824)
     | > loss_mel_ce: 4.278757095336914  (nan)
     | > loss: 4.3108625411987305  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.166  (0.19441985290558605)
     | > loader_time: 0.0086  (0.011748870278968171)


   --> TIME: 2025-05-17 16:46:16 -- STEP: 6150/6836 -- GLOBAL_STEP: 6150
     | > loss_text_ce: 0.030622009187936783  (0.033114966921266066)
     | > loss_mel_ce: 3.8062784671783447  (nan)
     | > loss: 3.836900472640991  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1669  (0.19443024747739954)
     | > loader_time: 0.01  (0.01174106830503881)


   --> TIME: 2025-05-17 16:46:39 -- STEP: 6200/6836 -- GLOBAL_STEP: 6200
     | > loss_text_ce: 0.02861769311130047  (0.03311142547566811)
     | > loss_mel_ce: 4.209557056427002  (nan)
     | > loss: 4.238174915313721  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1876  (0.19447146231128315)
     | > loader_time: 0.0097  (0.011732024300482952)


   --> TIME: 2025-05-17 16:47:02 -- STEP: 6250/6836 -- GLOBAL_STEP: 6250
     | > loss_text_ce: 0.032802876085042953  (0.03310595262169844)
     | > loss_mel_ce: 5.154000282287598  (nan)
     | > loss: 5.186803340911865  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1453  (0.19450889446258537)
     | > loader_time: 0.0096  (0.011735263175964341)


   --> TIME: 2025-05-17 16:47:25 -- STEP: 6300/6836 -- GLOBAL_STEP: 6300
     | > loss_text_ce: 0.030074169859290123  (0.033096839364559004)
     | > loss_mel_ce: 4.142716884613037  (nan)
     | > loss: 4.172791004180908  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2084  (0.1944989357297382)
     | > loader_time: 0.0253  (0.011736646531120165)


   --> TIME: 2025-05-17 16:47:47 -- STEP: 6350/6836 -- GLOBAL_STEP: 6350
     | > loss_text_ce: 0.030611634254455566  (0.03308314304270854)
     | > loss_mel_ce: 3.949805974960327  (nan)
     | > loss: 3.9804177284240723  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2207  (0.19446558573114583)
     | > loader_time: 0.0086  (0.01173037390070636)


   --> TIME: 2025-05-17 16:48:09 -- STEP: 6400/6836 -- GLOBAL_STEP: 6400
     | > loss_text_ce: 0.029025157913565636  (0.03306996691972021)
     | > loss_mel_ce: 3.6249868869781494  (nan)
     | > loss: 3.6540119647979736  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1817  (0.19437821671366684)
     | > loader_time: 0.0079  (0.011742849387228476)


   --> TIME: 2025-05-17 16:48:31 -- STEP: 6450/6836 -- GLOBAL_STEP: 6450
     | > loss_text_ce: 0.026233812794089317  (0.03306277753770817)
     | > loss_mel_ce: 3.1155896186828613  (nan)
     | > loss: 3.1418235301971436  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1491  (0.19428800837938168)
     | > loader_time: 0.0085  (0.011734576373137231)


   --> TIME: 2025-05-17 16:48:54 -- STEP: 6500/6836 -- GLOBAL_STEP: 6500
     | > loss_text_ce: 0.02999114990234375  (0.03304871107809822)
     | > loss_mel_ce: 3.188112497329712  (nan)
     | > loss: 3.2181036472320557  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1667  (0.19428805538324204)
     | > loader_time: 0.0094  (0.011716022418095502)


   --> TIME: 2025-05-17 16:49:16 -- STEP: 6550/6836 -- GLOBAL_STEP: 6550
     | > loss_text_ce: 0.030005579814314842  (0.03303538168944024)
     | > loss_mel_ce: 4.523535251617432  (nan)
     | > loss: 4.5535407066345215  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1626  (0.19429198188636132)
     | > loader_time: 0.0078  (0.011709410652859508)


   --> TIME: 2025-05-17 16:49:39 -- STEP: 6600/6836 -- GLOBAL_STEP: 6600
     | > loss_text_ce: 0.029312720522284508  (0.03302365688465989)
     | > loss_mel_ce: 3.572838306427002  (nan)
     | > loss: 3.6021509170532227  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1302  (0.19426601615819059)
     | > loader_time: 0.0089  (0.011705491831808367)


   --> TIME: 2025-05-17 16:50:02 -- STEP: 6650/6836 -- GLOBAL_STEP: 6650
     | > loss_text_ce: 0.03222744166851044  (0.03301829412439489)
     | > loss_mel_ce: 3.457324266433716  (nan)
     | > loss: 3.4895517826080322  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2289  (0.19432317927367698)
     | > loader_time: 0.0111  (0.01170701568288013)


   --> TIME: 2025-05-17 16:50:24 -- STEP: 6700/6836 -- GLOBAL_STEP: 6700
     | > loss_text_ce: 0.027596626430749893  (0.03301007370395003)
     | > loss_mel_ce: 3.401207685470581  (nan)
     | > loss: 3.428804397583008  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1287  (0.19424379338079417)
     | > loader_time: 0.0091  (0.011696949894748504)


   --> TIME: 2025-05-17 16:50:46 -- STEP: 6750/6836 -- GLOBAL_STEP: 6750
     | > loss_text_ce: 0.031857240945100784  (0.03300529041224056)
     | > loss_mel_ce: 3.7874016761779785  (nan)
     | > loss: 3.81925892829895  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1786  (0.1942755492528279)
     | > loader_time: 0.0096  (0.011701921074478702)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:51:09 -- STEP: 6800/6836 -- GLOBAL_STEP: 6800
     | > loss_text_ce: 0.03304312005639076  (0.03299817798193543)
     | > loss_mel_ce: 4.057344436645508  (nan)
     | > loss: 4.090387344360352  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1911  (0.19428940573159378)
     | > loader_time: 0.0088  (0.011702596510157853)

 | > Synthesizing test sentences.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.01169301607178001 (+0)
     | > avg_step_time: 0.1942841926105892 (+0)
     | > avg_loss_text_ce: 0.03299162459546792 (+0)
     | > avg_loss_mel_ce: nan (+0)
     | > avg_loss: nan (+0)
     | > avg_grad_norm: 0.0 (+0)


 > EPOCH: 1/15
 --> /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000

 > TRAINING (2025-05-17 16:51:35)

   --> TIME: 2025-05-17 16:51:43 -- STEP: 14/6836 -- GLOBAL_STEP: 6850
     | > loss_text_ce: 0.03495470806956291  (0.03240946826658079)
     | > loss_mel_ce: 4.496704578399658  (nan)
     | > loss: 4.531659126281738  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2285  (0.20396009513310023)
     | > loader_time: 0.01  (0.013128774506705148)


   --> TIME: 2025-05-17 16:52:05 -- STEP: 64/6836 -- GLOBAL_STEP: 6900
     | > loss_text_ce: 0.027937261387705803  (0.03162128580152057)
     | > loss_mel_ce: 3.777174234390259  (nan)
     | > loss: 3.8051114082336426  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2283  (0.1964920312166214)
     | > loader_time: 0.0134  (0.011377591639757156)


   --> TIME: 2025-05-17 16:52:28 -- STEP: 114/6836 -- GLOBAL_STEP: 6950
     | > loss_text_ce: 0.033912524580955505  (0.03181556703751548)
     | > loss_mel_ce: 3.762204647064209  (nan)
     | > loss: 3.796117067337036  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.211  (0.19821991000259132)
     | > loader_time: 0.01  (0.011225765211540352)


   --> TIME: 2025-05-17 16:52:51 -- STEP: 164/6836 -- GLOBAL_STEP: 7000
     | > loss_text_ce: 0.02961539290845394  (0.03191139469513807)
     | > loss_mel_ce: 3.0921292304992676  (nan)
     | > loss: 3.1217446327209473  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2228  (0.19630726226946202)
     | > loader_time: 0.0097  (0.010937167377006713)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 16:53:13 -- STEP: 214/6836 -- GLOBAL_STEP: 7050
     | > loss_text_ce: 0.031392306089401245  (0.03193485389559346)
     | > loss_mel_ce: 3.595651388168335  (nan)
     | > loss: 3.6270437240600586  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3  (0.19615543668515215)
     | > loader_time: 0.0094  (0.010818790052538711)


   --> TIME: 2025-05-17 16:53:36 -- STEP: 264/6836 -- GLOBAL_STEP: 7100
     | > loss_text_ce: 0.031125692650675774  (0.031896582197849466)
     | > loss_mel_ce: 3.4868924617767334  (nan)
     | > loss: 3.5180182456970215  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2084  (0.1970132923487461)
     | > loader_time: 0.0084  (0.01091156312913605)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:53:59 -- STEP: 314/6836 -- GLOBAL_STEP: 7150
     | > loss_text_ce: 0.03111240826547146  (0.03197428819005654)
     | > loss_mel_ce: 5.124213218688965  (nan)
     | > loss: 5.155325412750244  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2149  (0.19664810797211468)
     | > loader_time: 0.016  (0.011071622751320996)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:54:21 -- STEP: 364/6836 -- GLOBAL_STEP: 7200
     | > loss_text_ce: 0.02940642274916172  (0.03196579086399832)
     | > loss_mel_ce: 4.2336320877075195  (nan)
     | > loss: 4.263038635253906  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1859  (0.19709737418772097)
     | > loader_time: 0.0097  (0.011211441768394715)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.
[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:54:45 -- STEP: 414/6836 -- GLOBAL_STEP: 7250
     | > loss_text_ce: 0.035617537796497345  (0.03199605998281693)
     | > loss_mel_ce: 3.8668575286865234  (nan)
     | > loss: 3.902475118637085  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1929  (0.19834161150282703)
     | > loader_time: 0.0086  (0.01123918600128468)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:55:07 -- STEP: 464/6836 -- GLOBAL_STEP: 7300
     | > loss_text_ce: 0.027088357135653496  (0.03199035017992012)
     | > loss_mel_ce: 3.9125020503997803  (nan)
     | > loss: 3.9395904541015625  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3164  (0.19675833295131548)
     | > loader_time: 0.0098  (0.011057708797783682)


   --> TIME: 2025-05-17 16:55:30 -- STEP: 514/6836 -- GLOBAL_STEP: 7350
     | > loss_text_ce: 0.030451271682977676  (0.03195368913853906)
     | > loss_mel_ce: 3.579350471496582  (nan)
     | > loss: 3.609801769256592  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1779  (0.19754296378866704)
     | > loader_time: 0.0094  (0.011091927146169456)


   --> TIME: 2025-05-17 16:55:52 -- STEP: 564/6836 -- GLOBAL_STEP: 7400
     | > loss_text_ce: 0.032606836408376694  (0.03203961666316742)
     | > loss_mel_ce: 3.076982259750366  (nan)
     | > loss: 3.109589099884033  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2037  (0.1975471838146237)
     | > loader_time: 0.0087  (0.011082913858670707)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:56:15 -- STEP: 614/6836 -- GLOBAL_STEP: 7450
     | > loss_text_ce: 0.028719255700707436  (0.03200396988844246)
     | > loss_mel_ce: 4.461831569671631  (nan)
     | > loss: 4.490550994873047  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1764  (0.19676734997317535)
     | > loader_time: 0.0111  (0.011036702010064636)


   --> TIME: 2025-05-17 16:56:37 -- STEP: 664/6836 -- GLOBAL_STEP: 7500
     | > loss_text_ce: 0.03401978313922882  (0.03195850461362352)
     | > loss_mel_ce: 4.664417743682861  (nan)
     | > loss: 4.698437690734863  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2659  (0.19644493044140818)
     | > loader_time: 0.0092  (0.01115084807556796)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:57:00 -- STEP: 714/6836 -- GLOBAL_STEP: 7550
     | > loss_text_ce: 0.028698652982711792  (0.03198723251088738)
     | > loss_mel_ce: 4.320499897003174  (nan)
     | > loss: 4.349198341369629  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1964  (0.19599792636743105)
     | > loader_time: 0.0085  (0.011071159726097473)


   --> TIME: 2025-05-17 16:57:21 -- STEP: 764/6836 -- GLOBAL_STEP: 7600
     | > loss_text_ce: 0.03197465464472771  (0.03195799045332978)
     | > loss_mel_ce: 3.8176865577697754  (nan)
     | > loss: 3.849661111831665  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1975  (0.19523627939024513)
     | > loader_time: 0.0086  (0.011116196347780879)


   --> TIME: 2025-05-17 16:57:44 -- STEP: 814/6836 -- GLOBAL_STEP: 7650
     | > loss_text_ce: 0.03192169964313507  (0.031962651313174946)
     | > loss_mel_ce: 3.6635897159576416  (nan)
     | > loss: 3.6955113410949707  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2014  (0.19518169870540603)
     | > loader_time: 0.0087  (0.011166493488471107)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:58:06 -- STEP: 864/6836 -- GLOBAL_STEP: 7700
     | > loss_text_ce: 0.0366835854947567  (0.03195147968923531)
     | > loss_mel_ce: 3.672985553741455  (nan)
     | > loss: 3.7096691131591797  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1286  (0.19498984267314268)
     | > loader_time: 0.0097  (0.011211898315835885)


   --> TIME: 2025-05-17 16:58:29 -- STEP: 914/6836 -- GLOBAL_STEP: 7750
     | > loss_text_ce: 0.031576406210660934  (0.03193757053733651)
     | > loss_mel_ce: 3.600562810897827  (nan)
     | > loss: 3.632139205932617  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1689  (0.19555749543647008)
     | > loader_time: 0.009  (0.011225095202155918)


   --> TIME: 2025-05-17 16:58:52 -- STEP: 964/6836 -- GLOBAL_STEP: 7800
     | > loss_text_ce: 0.03268519416451454  (0.03191110219311786)
     | > loss_mel_ce: 3.702061891555786  (nan)
     | > loss: 3.7347471714019775  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2029  (0.1956498323634452)
     | > loader_time: 0.0088  (0.01122554654402357)


   --> TIME: 2025-05-17 16:59:14 -- STEP: 1014/6836 -- GLOBAL_STEP: 7850
     | > loss_text_ce: 0.029223598539829254  (0.03191519558936707)
     | > loss_mel_ce: 4.093982696533203  (nan)
     | > loss: 4.12320613861084  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.263  (0.19533918124919336)
     | > loader_time: 0.0086  (0.01117873967751949)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 16:59:36 -- STEP: 1064/6836 -- GLOBAL_STEP: 7900
     | > loss_text_ce: 0.030995909124612808  (0.03188424291705387)
     | > loss_mel_ce: 3.6433207988739014  (nan)
     | > loss: 3.674316644668579  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2207  (0.19457293363442094)
     | > loader_time: 0.024  (0.011200711467212306)


   --> TIME: 2025-05-17 16:59:58 -- STEP: 1114/6836 -- GLOBAL_STEP: 7950
     | > loss_text_ce: 0.03286540135741234  (0.03189983311706159)
     | > loss_mel_ce: 3.8366196155548096  (nan)
     | > loss: 3.8694849014282227  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1809  (0.19445596135069265)
     | > loader_time: 0.0099  (0.011191902725658035)


   --> TIME: 2025-05-17 17:00:21 -- STEP: 1164/6836 -- GLOBAL_STEP: 8000
     | > loss_text_ce: 0.03703463077545166  (0.03193872087855928)
     | > loss_mel_ce: 4.0509796142578125  (nan)
     | > loss: 4.088014125823975  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1281  (0.19436491273113132)
     | > loader_time: 0.0108  (0.01122096682741879)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 17:00:43 -- STEP: 1214/6836 -- GLOBAL_STEP: 8050
     | > loss_text_ce: 0.030471554026007652  (0.03190205291472067)
     | > loss_mel_ce: 4.79418420791626  (nan)
     | > loss: 4.824655532836914  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1563  (0.1941111784986846)
     | > loader_time: 0.0088  (0.011268894008592475)


   --> TIME: 2025-05-17 17:01:05 -- STEP: 1264/6836 -- GLOBAL_STEP: 8100
     | > loss_text_ce: 0.028807753697037697  (0.03190261437822888)
     | > loss_mel_ce: 4.31238317489624  (nan)
     | > loss: 4.341190814971924  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1568  (0.19396734784675565)
     | > loader_time: 0.0108  (0.011262009981312323)


   --> TIME: 2025-05-17 17:01:28 -- STEP: 1314/6836 -- GLOBAL_STEP: 8150
     | > loss_text_ce: 0.028756430372595787  (0.03188902172692337)
     | > loss_mel_ce: 3.40497088432312  (nan)
     | > loss: 3.433727264404297  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2256  (0.19415744762623893)
     | > loader_time: 0.009  (0.011234901629989358)


   --> TIME: 2025-05-17 17:01:51 -- STEP: 1364/6836 -- GLOBAL_STEP: 8200
     | > loss_text_ce: 0.03328057751059532  (0.03189383014692457)
     | > loss_mel_ce: 3.899639129638672  (nan)
     | > loss: 3.93291974067688  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1936  (0.19414604217076256)
     | > loader_time: 0.0102  (0.011243741183686455)


   --> TIME: 2025-05-17 17:02:13 -- STEP: 1414/6836 -- GLOBAL_STEP: 8250
     | > loss_text_ce: 0.03198980912566185  (0.03187451056366763)
     | > loss_mel_ce: 3.6653707027435303  (nan)
     | > loss: 3.6973605155944824  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1509  (0.19409132357871203)
     | > loader_time: 0.0096  (0.01129409042746881)


   --> TIME: 2025-05-17 17:02:35 -- STEP: 1464/6836 -- GLOBAL_STEP: 8300
     | > loss_text_ce: 0.03393092006444931  (0.03189172420034929)
     | > loss_mel_ce: 3.8571436405181885  (nan)
     | > loss: 3.8910746574401855  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2161  (0.1936898492073103)
     | > loader_time: 0.0101  (0.011241051668677811)


   --> TIME: 2025-05-17 17:02:57 -- STEP: 1514/6836 -- GLOBAL_STEP: 8350
     | > loss_text_ce: 0.03490732982754707  (0.0318876463646756)
     | > loss_mel_ce: 4.35575532913208  (nan)
     | > loss: 4.390662670135498  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.135  (0.19368958882643042)
     | > loader_time: 0.0091  (0.0112930172500711)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:03:19 -- STEP: 1564/6836 -- GLOBAL_STEP: 8400
     | > loss_text_ce: 0.03314387798309326  (0.03190166424588326)
     | > loss_mel_ce: 3.2346580028533936  (nan)
     | > loss: 3.2678017616271973  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2013  (0.19370342017439646)
     | > loader_time: 0.0107  (0.011244730876229899)


   --> TIME: 2025-05-17 17:03:42 -- STEP: 1614/6836 -- GLOBAL_STEP: 8450
     | > loss_text_ce: 0.03348246589303017  (0.03190790718049735)
     | > loss_mel_ce: 4.328792095184326  (nan)
     | > loss: 4.362274646759033  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.23  (0.1937377990547759)
     | > loader_time: 0.0099  (0.011221627763655978)


   --> TIME: 2025-05-17 17:04:04 -- STEP: 1664/6836 -- GLOBAL_STEP: 8500
     | > loss_text_ce: 0.04072478786110878  (0.03191132999647658)
     | > loss_mel_ce: 3.9300873279571533  (nan)
     | > loss: 3.9708120822906494  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2041  (0.1936612665080109)
     | > loader_time: 0.0073  (0.011208739848091039)


   --> TIME: 2025-05-17 17:04:27 -- STEP: 1714/6836 -- GLOBAL_STEP: 8550
     | > loss_text_ce: 0.03386525809764862  (0.03192093767999489)
     | > loss_mel_ce: 4.356130123138428  (nan)
     | > loss: 4.389995574951172  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2304  (0.19379887447334943)
     | > loader_time: 0.0087  (0.01118230833612216)


   --> TIME: 2025-05-17 17:04:49 -- STEP: 1764/6836 -- GLOBAL_STEP: 8600
     | > loss_text_ce: 0.03352511674165726  (0.0318997554647865)
     | > loss_mel_ce: 3.690666913986206  (nan)
     | > loss: 3.7241921424865723  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1425  (0.19389230012893696)
     | > loader_time: 0.0167  (0.01119103426295342)


   --> TIME: 2025-05-17 17:05:12 -- STEP: 1814/6836 -- GLOBAL_STEP: 8650
     | > loss_text_ce: 0.03474988043308258  (0.031889076617802055)
     | > loss_mel_ce: 2.903012752532959  (nan)
     | > loss: 2.93776273727417  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1726  (0.19375739365717562)
     | > loader_time: 0.0089  (0.01115469632890021)


   --> TIME: 2025-05-17 17:05:34 -- STEP: 1864/6836 -- GLOBAL_STEP: 8700
     | > loss_text_ce: 0.03472807630896568  (0.03189829030861606)
     | > loss_mel_ce: 3.6900224685668945  (nan)
     | > loss: 3.724750518798828  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1703  (0.19386864642216942)
     | > loader_time: 0.0092  (0.01116435287336422)


   --> TIME: 2025-05-17 17:05:56 -- STEP: 1914/6836 -- GLOBAL_STEP: 8750
     | > loss_text_ce: 0.04042109102010727  (0.031892572748576944)
     | > loss_mel_ce: 4.1133832931518555  (nan)
     | > loss: 4.153804302215576  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1909  (0.19369848282733326)
     | > loader_time: 0.0244  (0.011179065255909493)


   --> TIME: 2025-05-17 17:06:19 -- STEP: 1964/6836 -- GLOBAL_STEP: 8800
     | > loss_text_ce: 0.03550232574343681  (0.031876344961169215)
     | > loss_mel_ce: 3.661500930786133  (nan)
     | > loss: 3.6970033645629883  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2551  (0.193653175641466)
     | > loader_time: 0.0104  (0.011187810640471033)


   --> TIME: 2025-05-17 17:06:41 -- STEP: 2014/6836 -- GLOBAL_STEP: 8850
     | > loss_text_ce: 0.03116592764854431  (0.031880772953747576)
     | > loss_mel_ce: 2.763678789138794  (nan)
     | > loss: 2.794844627380371  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1865  (0.19373571730654449)
     | > loader_time: 0.0097  (0.011189019194662619)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:07:04 -- STEP: 2064/6836 -- GLOBAL_STEP: 8900
     | > loss_text_ce: 0.02642471343278885  (0.031850534314361884)
     | > loss_mel_ce: 3.7928030490875244  (nan)
     | > loss: 3.819227695465088  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1391  (0.19365797521070005)
     | > loader_time: 0.0083  (0.011143419978230488)


   --> TIME: 2025-05-17 17:07:27 -- STEP: 2114/6836 -- GLOBAL_STEP: 8950
     | > loss_text_ce: 0.035456061363220215  (0.031852894682920026)
     | > loss_mel_ce: 3.3937392234802246  (nan)
     | > loss: 3.4291954040527344  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1435  (0.19385965612550457)
     | > loader_time: 0.01  (0.011125679047691892)


   --> TIME: 2025-05-17 17:07:50 -- STEP: 2164/6836 -- GLOBAL_STEP: 9000
     | > loss_text_ce: 0.031660038977861404  (0.03182921996219653)
     | > loss_mel_ce: 3.7614023685455322  (nan)
     | > loss: 3.793062448501587  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1978  (0.19408479955412336)
     | > loader_time: 0.0069  (0.011145675578972319)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 17:08:13 -- STEP: 2214/6836 -- GLOBAL_STEP: 9050
     | > loss_text_ce: 0.031020650640130043  (0.03184396424604197)
     | > loss_mel_ce: 5.01755952835083  (nan)
     | > loss: 5.048580169677734  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3229  (0.1942946843015469)
     | > loader_time: 0.0112  (0.011141820867102525)


   --> TIME: 2025-05-17 17:08:35 -- STEP: 2264/6836 -- GLOBAL_STEP: 9100
     | > loss_text_ce: 0.03234266862273216  (0.03184029334570306)
     | > loss_mel_ce: 3.5905776023864746  (nan)
     | > loss: 3.622920274734497  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1324  (0.19412536408370448)
     | > loader_time: 0.0078  (0.011147517724087707)


   --> TIME: 2025-05-17 17:08:57 -- STEP: 2314/6836 -- GLOBAL_STEP: 9150
     | > loss_text_ce: 0.04090544208884239  (0.0318499420976384)
     | > loss_mel_ce: 3.49006986618042  (nan)
     | > loss: 3.530975341796875  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1547  (0.19382037689898057)
     | > loader_time: 0.0091  (0.011146826278369992)


   --> TIME: 2025-05-17 17:09:20 -- STEP: 2364/6836 -- GLOBAL_STEP: 9200
     | > loss_text_ce: 0.029733559116721153  (0.03184445635234391)
     | > loss_mel_ce: 4.124147891998291  (nan)
     | > loss: 4.153881549835205  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1422  (0.19406617252556385)
     | > loader_time: 0.0095  (0.0111490817844565)


   --> TIME: 2025-05-17 17:09:43 -- STEP: 2414/6836 -- GLOBAL_STEP: 9250
     | > loss_text_ce: 0.03201925382018089  (0.03183392726514541)
     | > loss_mel_ce: nan  (nan)
     | > loss: nan  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1901  (0.19416432382651552)
     | > loader_time: 0.0098  (0.011143034316333922)


   --> TIME: 2025-05-17 17:10:05 -- STEP: 2464/6836 -- GLOBAL_STEP: 9300
     | > loss_text_ce: 0.032849591225385666  (0.03183185468902569)
     | > loss_mel_ce: 2.86637020111084  (nan)
     | > loss: 2.8992197513580322  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2059  (0.19405199432527848)
     | > loader_time: 0.0093  (0.011136619011303028)


   --> TIME: 2025-05-17 17:10:28 -- STEP: 2514/6836 -- GLOBAL_STEP: 9350
     | > loss_text_ce: 0.027334026992321014  (0.031826080206867564)
     | > loss_mel_ce: 3.6843149662017822  (nan)
     | > loss: 3.711648941040039  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1823  (0.19426166925908264)
     | > loader_time: 0.0089  (0.011142190619888227)


   --> TIME: 2025-05-17 17:10:51 -- STEP: 2564/6836 -- GLOBAL_STEP: 9400
     | > loss_text_ce: 0.03117792122066021  (0.031831265972017686)
     | > loss_mel_ce: 3.5800974369049072  (nan)
     | > loss: 3.6112754344940186  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2039  (0.19430147030052258)
     | > loader_time: 0.0226  (0.011137981031688605)


   --> TIME: 2025-05-17 17:11:14 -- STEP: 2614/6836 -- GLOBAL_STEP: 9450
     | > loss_text_ce: 0.03027975931763649  (0.03182358140668847)
     | > loss_mel_ce: 3.6248507499694824  (nan)
     | > loss: 3.655130624771118  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.143  (0.19438893920880915)
     | > loader_time: 0.0093  (0.011156361159607006)


   --> TIME: 2025-05-17 17:11:35 -- STEP: 2664/6836 -- GLOBAL_STEP: 9500
     | > loss_text_ce: 0.03340970352292061  (0.031813907014015874)
     | > loss_mel_ce: 3.8610377311706543  (nan)
     | > loss: 3.8944473266601562  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2296  (0.1941441470259302)
     | > loader_time: 0.0078  (0.011138094438088888)


   --> TIME: 2025-05-17 17:11:58 -- STEP: 2714/6836 -- GLOBAL_STEP: 9550
     | > loss_text_ce: 0.02653934620320797  (0.031798348791606305)
     | > loss_mel_ce: 4.064205169677734  (nan)
     | > loss: 4.090744495391846  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2309  (0.19407988077766675)
     | > loader_time: 0.01  (0.011124264956750474)


   --> TIME: 2025-05-17 17:12:20 -- STEP: 2764/6836 -- GLOBAL_STEP: 9600
     | > loss_text_ce: 0.029647402465343475  (0.0317841293654161)
     | > loss_mel_ce: 3.012795925140381  (nan)
     | > loss: 3.04244327545166  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1266  (0.19405663160097747)
     | > loader_time: 0.009  (0.01114168810602896)


   --> TIME: 2025-05-17 17:12:42 -- STEP: 2814/6836 -- GLOBAL_STEP: 9650
     | > loss_text_ce: 0.029976993799209595  (0.03178036104366133)
     | > loss_mel_ce: 4.6348419189453125  (nan)
     | > loss: 4.66481876373291  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2024  (0.19399595031860278)
     | > loader_time: 0.0081  (0.011149631803901631)


   --> TIME: 2025-05-17 17:13:05 -- STEP: 2864/6836 -- GLOBAL_STEP: 9700
     | > loss_text_ce: 0.033744074404239655  (0.031774955629319104)
     | > loss_mel_ce: 3.5431177616119385  (nan)
     | > loss: 3.57686185836792  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1492  (0.1941431602619213)
     | > loader_time: 0.0087  (0.011157718950143738)


   --> TIME: 2025-05-17 17:13:28 -- STEP: 2914/6836 -- GLOBAL_STEP: 9750
     | > loss_text_ce: 0.029184745624661446  (0.031770101545139554)
     | > loss_mel_ce: 4.566281795501709  (nan)
     | > loss: 4.595466613769531  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2262  (0.1941089280762734)
     | > loader_time: 0.0078  (0.011174099446979382)


   --> TIME: 2025-05-17 17:13:51 -- STEP: 2964/6836 -- GLOBAL_STEP: 9800
     | > loss_text_ce: 0.03309456631541252  (0.03176475863705184)
     | > loss_mel_ce: 4.31144905090332  (nan)
     | > loss: 4.34454345703125  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.169  (0.19415764971139773)
     | > loader_time: 0.0083  (0.011161579937748257)


   --> TIME: 2025-05-17 17:14:13 -- STEP: 3014/6836 -- GLOBAL_STEP: 9850
     | > loss_text_ce: 0.029999051243066788  (0.03176149340407026)
     | > loss_mel_ce: 4.278844833374023  (nan)
     | > loss: 4.308844089508057  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1494  (0.19424255667890858)
     | > loader_time: 0.0094  (0.011163416016394518)


   --> TIME: 2025-05-17 17:14:36 -- STEP: 3064/6836 -- GLOBAL_STEP: 9900
     | > loss_text_ce: 0.03311826288700104  (0.03175709161642392)
     | > loss_mel_ce: 4.177260398864746  (nan)
     | > loss: 4.210378646850586  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1994  (0.19431028758265634)
     | > loader_time: 0.0108  (0.01115695443539333)


   --> TIME: 2025-05-17 17:15:00 -- STEP: 3114/6836 -- GLOBAL_STEP: 9950
     | > loss_text_ce: 0.029915370047092438  (0.03175851158012974)
     | > loss_mel_ce: 3.2841031551361084  (nan)
     | > loss: 3.314018487930298  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2078  (0.19482985029790206)
     | > loader_time: 0.012  (0.01121242948273626)


   --> TIME: 2025-05-17 17:15:24 -- STEP: 3164/6836 -- GLOBAL_STEP: 10000
     | > loss_text_ce: 0.030451063066720963  (0.03175365374401201)
     | > loss_mel_ce: 3.2253427505493164  (nan)
     | > loss: 3.255793809890747  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2616  (0.19576176477292387)
     | > loader_time: 0.0352  (0.011395488767949427)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========
[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:15:49 -- STEP: 3214/6836 -- GLOBAL_STEP: 10050
     | > loss_text_ce: 0.03570760041475296  (0.03174173269668914)
     | > loss_mel_ce: 3.2238271236419678  (nan)
     | > loss: 3.2595348358154297  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2704  (0.19685737064482628)
     | > loader_time: 0.0219  (0.011537318728173377)


   --> TIME: 2025-05-17 17:16:11 -- STEP: 3264/6836 -- GLOBAL_STEP: 10100
     | > loss_text_ce: 0.03178861364722252  (0.031735375994364504)
     | > loss_mel_ce: 4.471240520477295  (nan)
     | > loss: 4.5030293464660645  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2077  (0.19684814004337078)
     | > loader_time: 0.01  (0.011542619662541966)


   --> TIME: 2025-05-17 17:16:33 -- STEP: 3314/6836 -- GLOBAL_STEP: 10150
     | > loss_text_ce: 0.03271722421050072  (0.031729794920668936)
     | > loss_mel_ce: 1.7430970668792725  (nan)
     | > loss: 1.7758142948150635  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2303  (0.19673640079072383)
     | > loader_time: 0.0103  (0.011548444601736946)


   --> TIME: 2025-05-17 17:16:56 -- STEP: 3364/6836 -- GLOBAL_STEP: 10200
     | > loss_text_ce: 0.035083819180727005  (0.031729589434015076)
     | > loss_mel_ce: 4.490687847137451  (nan)
     | > loss: 4.525771617889404  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1752  (0.19670431813785488)
     | > loader_time: 0.0093  (0.011520860169645437)


   --> TIME: 2025-05-17 17:17:19 -- STEP: 3414/6836 -- GLOBAL_STEP: 10250
     | > loss_text_ce: 0.03000498376786709  (0.03172188459098448)
     | > loss_mel_ce: 4.16416597366333  (nan)
     | > loss: 4.194170951843262  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1288  (0.19677093151932784)
     | > loader_time: 0.0096  (0.011521550878559416)


   --> TIME: 2025-05-17 17:17:41 -- STEP: 3464/6836 -- GLOBAL_STEP: 10300
     | > loss_text_ce: 0.029095465317368507  (0.03171638678544252)
     | > loss_mel_ce: 3.8835346698760986  (nan)
     | > loss: 3.912630081176758  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1939  (0.19663719457787118)
     | > loader_time: 0.0254  (0.011524245383833075)


   --> TIME: 2025-05-17 17:18:03 -- STEP: 3514/6836 -- GLOBAL_STEP: 10350
     | > loss_text_ce: 0.033054135739803314  (0.03170556340506539)
     | > loss_mel_ce: 3.647294282913208  (nan)
     | > loss: 3.6803483963012695  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.178  (0.19643528778985875)
     | > loader_time: 0.0087  (0.011533619194595257)


   --> TIME: 2025-05-17 17:18:26 -- STEP: 3564/6836 -- GLOBAL_STEP: 10400
     | > loss_text_ce: 0.038206782191991806  (0.03169580657290152)
     | > loss_mel_ce: 4.367898941040039  (nan)
     | > loss: 4.4061055183410645  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2278  (0.19655403565076057)
     | > loader_time: 0.0097  (0.011534622488867418)


   --> TIME: 2025-05-17 17:18:48 -- STEP: 3614/6836 -- GLOBAL_STEP: 10450
     | > loss_text_ce: 0.03311321884393692  (0.031696012932198994)
     | > loss_mel_ce: 5.422268867492676  (nan)
     | > loss: 5.455381870269775  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2616  (0.19642692939576742)
     | > loader_time: 0.0091  (0.011533296101648764)


   --> TIME: 2025-05-17 17:19:10 -- STEP: 3664/6836 -- GLOBAL_STEP: 10500
     | > loss_text_ce: 0.027873706072568893  (0.0316896160935381)
     | > loss_mel_ce: 3.5688998699188232  (nan)
     | > loss: 3.596773624420166  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1476  (0.19635017027500928)
     | > loader_time: 0.0092  (0.011526287968502292)


   --> TIME: 2025-05-17 17:19:34 -- STEP: 3714/6836 -- GLOBAL_STEP: 10550
     | > loss_text_ce: 0.03174876794219017  (0.03168135135312699)
     | > loss_mel_ce: 3.70967698097229  (nan)
     | > loss: 3.7414257526397705  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2183  (0.19644783463732293)
     | > loader_time: 0.0087  (0.011512228925188316)


   --> TIME: 2025-05-17 17:19:56 -- STEP: 3764/6836 -- GLOBAL_STEP: 10600
     | > loss_text_ce: 0.03818666934967041  (0.03168511064772618)
     | > loss_mel_ce: 3.80764102935791  (nan)
     | > loss: 3.845827579498291  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.227  (0.1963544296027496)
     | > loader_time: 0.0096  (0.011501522107281415)


   --> TIME: 2025-05-17 17:20:18 -- STEP: 3814/6836 -- GLOBAL_STEP: 10650
     | > loss_text_ce: 0.02795470878481865  (0.031688124302815666)
     | > loss_mel_ce: 3.400857925415039  (nan)
     | > loss: 3.4288127422332764  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1718  (0.19631936728923052)
     | > loader_time: 0.0098  (0.011501418525283724)


   --> TIME: 2025-05-17 17:20:40 -- STEP: 3864/6836 -- GLOBAL_STEP: 10700
     | > loss_text_ce: 0.030455725267529488  (0.03168200268448706)
     | > loss_mel_ce: 4.084978103637695  (nan)
     | > loss: 4.115433692932129  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1285  (0.19614131060693074)
     | > loader_time: 0.008  (0.011476616743435275)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:21:02 -- STEP: 3914/6836 -- GLOBAL_STEP: 10750
     | > loss_text_ce: 0.025962354615330696  (0.03168156227609923)
     | > loss_mel_ce: 4.5636701583862305  (nan)
     | > loss: 4.589632511138916  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1953  (0.19610053011514603)
     | > loader_time: 0.0096  (0.011457428678786442)


   --> TIME: 2025-05-17 17:21:25 -- STEP: 3964/6836 -- GLOBAL_STEP: 10800
     | > loss_text_ce: 0.03333904966711998  (0.03167676865466225)
     | > loss_mel_ce: 3.7638161182403564  (nan)
     | > loss: 3.7971551418304443  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2204  (0.19610646195657072)
     | > loader_time: 0.0135  (0.011432757110576454)


   --> TIME: 2025-05-17 17:21:48 -- STEP: 4014/6836 -- GLOBAL_STEP: 10850
     | > loss_text_ce: 0.03395361453294754  (0.03167940596026681)
     | > loss_mel_ce: 3.7276151180267334  (nan)
     | > loss: 3.761568784713745  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.147  (0.1961950484234477)
     | > loader_time: 0.0094  (0.011429781217627341)


   --> TIME: 2025-05-17 17:22:11 -- STEP: 4064/6836 -- GLOBAL_STEP: 10900
     | > loss_text_ce: 0.03195643052458763  (0.031667094888975816)
     | > loss_mel_ce: 3.728862762451172  (nan)
     | > loss: 3.76081919670105  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2606  (0.19621724388965467)
     | > loader_time: 0.0098  (0.011428165212860256)


   --> TIME: 2025-05-17 17:22:33 -- STEP: 4114/6836 -- GLOBAL_STEP: 10950
     | > loss_text_ce: 0.03427829593420029  (0.03166214108383785)
     | > loss_mel_ce: 3.6960885524749756  (nan)
     | > loss: 3.7303669452667236  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1447  (0.1960848883395642)
     | > loader_time: 0.0106  (0.011416988229079331)


   --> TIME: 2025-05-17 17:22:56 -- STEP: 4164/6836 -- GLOBAL_STEP: 11000
     | > loss_text_ce: 0.029935769736766815  (0.03165985385401524)
     | > loss_mel_ce: 3.630472421646118  (nan)
     | > loss: 3.6604082584381104  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2008  (0.19621882561189863)
     | > loader_time: 0.0088  (0.011421646038920229)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 17:24:24 -- STEP: 4214/6836 -- GLOBAL_STEP: 11050
     | > loss_text_ce: 0.027890896424651146  (0.03165918898666608)
     | > loss_mel_ce: 3.3517343997955322  (nan)
     | > loss: 3.3796253204345703  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2177  (0.19630071564653093)
     | > loader_time: 0.0257  (0.026850759671885195)


   --> TIME: 2025-05-17 17:24:45 -- STEP: 4264/6836 -- GLOBAL_STEP: 11100
     | > loss_text_ce: 0.0255864467471838  (0.031662270739520694)
     | > loss_mel_ce: 3.90572452545166  (nan)
     | > loss: 3.9313108921051025  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.137  (0.19615862863819764)
     | > loader_time: 0.0102  (0.02665817044242015)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:25:08 -- STEP: 4314/6836 -- GLOBAL_STEP: 11150
     | > loss_text_ce: 0.03262999281287193  (0.03166485336895435)
     | > loss_mel_ce: 4.176478862762451  (nan)
     | > loss: 4.209108829498291  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2168  (0.19611757316686615)
     | > loader_time: 0.0091  (0.02647368384004469)


   --> TIME: 2025-05-17 17:25:29 -- STEP: 4364/6836 -- GLOBAL_STEP: 11200
     | > loss_text_ce: 0.03038562275469303  (0.031668522109223635)
     | > loss_mel_ce: 3.999100685119629  (nan)
     | > loss: 4.029486179351807  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1727  (0.19597745957885931)
     | > loader_time: 0.0093  (0.026301238921451316)


   --> TIME: 2025-05-17 17:25:51 -- STEP: 4414/6836 -- GLOBAL_STEP: 11250
     | > loss_text_ce: 0.02985340729355812  (0.03166047656570187)
     | > loss_mel_ce: 3.6699929237365723  (nan)
     | > loss: 3.6998462677001953  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1295  (0.19586518294788552)
     | > loader_time: 0.0088  (0.026131822018262547)


   --> TIME: 2025-05-17 17:26:13 -- STEP: 4464/6836 -- GLOBAL_STEP: 11300
     | > loss_text_ce: 0.03138073906302452  (0.03165899713124774)
     | > loss_mel_ce: 4.62596321105957  (nan)
     | > loss: 4.657343864440918  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1917  (0.19569993916378214)
     | > loader_time: 0.01  (0.02594521962186343)


   --> TIME: 2025-05-17 17:26:36 -- STEP: 4514/6836 -- GLOBAL_STEP: 11350
     | > loss_text_ce: 0.029443928971886635  (0.03165855448681471)
     | > loss_mel_ce: 3.567448616027832  (nan)
     | > loss: 3.5968925952911377  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2601  (0.19578995422604958)
     | > loader_time: 0.0093  (0.025780137524332274)


   --> TIME: 2025-05-17 17:26:59 -- STEP: 4564/6836 -- GLOBAL_STEP: 11400
     | > loss_text_ce: 0.031219519674777985  (0.031662014560360836)
     | > loss_mel_ce: 4.218443393707275  (nan)
     | > loss: 4.24966287612915  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2457  (0.1958218916375629)
     | > loader_time: 0.0123  (0.02562079071267252)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:27:21 -- STEP: 4614/6836 -- GLOBAL_STEP: 11450
     | > loss_text_ce: 0.03133634105324745  (0.031650686268397864)
     | > loss_mel_ce: 3.7211053371429443  (nan)
     | > loss: 3.752441644668579  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1756  (0.1958300532021457)
     | > loader_time: 0.0096  (0.025458732724034747)


   --> TIME: 2025-05-17 17:27:44 -- STEP: 4664/6836 -- GLOBAL_STEP: 11500
     | > loss_text_ce: 0.0332062728703022  (0.03164687897933326)
     | > loss_mel_ce: 3.3167054653167725  (nan)
     | > loss: 3.349911689758301  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1289  (0.19582722010170805)
     | > loader_time: 0.0082  (0.025300037543933146)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:28:07 -- STEP: 4714/6836 -- GLOBAL_STEP: 11550
     | > loss_text_ce: 0.03517167642712593  (0.031647106603350544)
     | > loss_mel_ce: 3.3797552585601807  (nan)
     | > loss: 3.4149270057678223  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2097  (0.1958803420963051)
     | > loader_time: 0.0124  (0.02513404341638215)


   --> TIME: 2025-05-17 17:28:29 -- STEP: 4764/6836 -- GLOBAL_STEP: 11600
     | > loss_text_ce: 0.03391357511281967  (0.03164687663774951)
     | > loss_mel_ce: 0.8362938165664673  (nan)
     | > loss: 0.8702073693275452  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1487  (0.1958109368605335)
     | > loader_time: 0.0093  (0.02498564687123526)


   --> TIME: 2025-05-17 17:28:51 -- STEP: 4814/6836 -- GLOBAL_STEP: 11650
     | > loss_text_ce: 0.03089260496199131  (0.03164448748846844)
     | > loss_mel_ce: 3.7500526905059814  (nan)
     | > loss: 3.780945301055908  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1967  (0.19578165011530738)
     | > loader_time: 0.0125  (0.024829448581880978)


   --> TIME: 2025-05-17 17:29:14 -- STEP: 4864/6836 -- GLOBAL_STEP: 11700
     | > loss_text_ce: 0.03117471933364868  (0.03164338334356304)
     | > loss_mel_ce: 3.871490001678467  (nan)
     | > loss: 3.9026646614074707  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2796  (0.19580525056900147)
     | > loader_time: 0.0101  (0.024693281585840807)


   --> TIME: 2025-05-17 17:29:38 -- STEP: 4914/6836 -- GLOBAL_STEP: 11750
     | > loss_text_ce: 0.028156545013189316  (0.03163433670739861)
     | > loss_mel_ce: 3.35223388671875  (nan)
     | > loss: 3.3803904056549072  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3035  (0.19598743844721228)
     | > loader_time: 0.0103  (0.024544343358382605)


   --> TIME: 2025-05-17 17:30:00 -- STEP: 4964/6836 -- GLOBAL_STEP: 11800
     | > loss_text_ce: 0.03541034460067749  (0.031634019357568745)
     | > loss_mel_ce: 3.6321966648101807  (nan)
     | > loss: 3.667607069015503  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1994  (0.19593290947407685)
     | > loader_time: 0.0078  (0.02439455881318578)


   --> TIME: 2025-05-17 17:30:22 -- STEP: 5014/6836 -- GLOBAL_STEP: 11850
     | > loss_text_ce: 0.03019959107041359  (0.03163199455005131)
     | > loss_mel_ce: 3.4886739253997803  (nan)
     | > loss: 3.518873453140259  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2769  (0.19585631295034112)
     | > loader_time: 0.0089  (0.024263212677963625)


   --> TIME: 2025-05-17 17:30:44 -- STEP: 5064/6836 -- GLOBAL_STEP: 11900
     | > loss_text_ce: 0.029834827408194542  (0.03163407238657873)
     | > loss_mel_ce: 3.511603832244873  (nan)
     | > loss: 3.541438579559326  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2068  (0.1958385836833272)
     | > loader_time: 0.0081  (0.02413401181852272)


   --> TIME: 2025-05-17 17:31:07 -- STEP: 5114/6836 -- GLOBAL_STEP: 11950
     | > loss_text_ce: 0.02759942039847374  (0.03162975579982426)
     | > loss_mel_ce: 4.096776962280273  (nan)
     | > loss: 4.12437629699707  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1444  (0.1958628984275253)
     | > loader_time: 0.0092  (0.024013659056155153)


   --> TIME: 2025-05-17 17:31:30 -- STEP: 5164/6836 -- GLOBAL_STEP: 12000
     | > loss_text_ce: 0.027661310508847237  (0.03161758615286895)
     | > loss_mel_ce: 3.389604091644287  (nan)
     | > loss: 3.4172654151916504  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1924  (0.19588409173774857)
     | > loader_time: 0.009  (0.023888418002243093)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 17:31:52 -- STEP: 5214/6836 -- GLOBAL_STEP: 12050
     | > loss_text_ce: 0.03315950930118561  (0.031613606535538394)
     | > loss_mel_ce: 3.8418776988983154  (nan)
     | > loss: 3.87503719329834  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1964  (0.19589338062090286)
     | > loader_time: 0.0081  (0.02375254884367935)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:32:14 -- STEP: 5264/6836 -- GLOBAL_STEP: 12100
     | > loss_text_ce: 0.029893171042203903  (0.031604899238939346)
     | > loss_mel_ce: 4.623829364776611  (nan)
     | > loss: 4.653722763061523  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2828  (0.19579166962020647)
     | > loader_time: 0.0097  (0.023637229186060923)


   --> TIME: 2025-05-17 17:32:36 -- STEP: 5314/6836 -- GLOBAL_STEP: 12150
     | > loss_text_ce: 0.03026818484067917  (0.03159917749276628)
     | > loss_mel_ce: 3.5756070613861084  (nan)
     | > loss: 3.605875253677368  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2237  (0.19575602262595276)
     | > loader_time: 0.011  (0.023523774369569636)


   --> TIME: 2025-05-17 17:32:59 -- STEP: 5364/6836 -- GLOBAL_STEP: 12200
     | > loss_text_ce: 0.03565974533557892  (0.03159095571077049)
     | > loss_mel_ce: 3.682027578353882  (nan)
     | > loss: 3.7176873683929443  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1909  (0.19570936474846318)
     | > loader_time: 0.0094  (0.02341302293703504)


   --> TIME: 2025-05-17 17:33:22 -- STEP: 5414/6836 -- GLOBAL_STEP: 12250
     | > loss_text_ce: 0.02918565273284912  (0.031586018293589514)
     | > loss_mel_ce: 3.0101287364959717  (nan)
     | > loss: 3.0393142700195312  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2087  (0.1957690118202036)
     | > loader_time: 0.0107  (0.023296939652918177)


   --> TIME: 2025-05-17 17:33:44 -- STEP: 5464/6836 -- GLOBAL_STEP: 12300
     | > loss_text_ce: 0.031676605343818665  (0.03158546094632653)
     | > loss_mel_ce: 3.8786723613739014  (nan)
     | > loss: 3.910348892211914  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.177  (0.19568150048723665)
     | > loader_time: 0.0112  (0.023178638249504786)


   --> TIME: 2025-05-17 17:34:06 -- STEP: 5514/6836 -- GLOBAL_STEP: 12350
     | > loss_text_ce: 0.026056239381432533  (0.03158228689555372)
     | > loss_mel_ce: 3.6414482593536377  (nan)
     | > loss: 3.6675045490264893  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1788  (0.19562441112772883)
     | > loader_time: 0.0097  (0.023077302235038455)


   --> TIME: 2025-05-17 17:34:28 -- STEP: 5564/6836 -- GLOBAL_STEP: 12400
     | > loss_text_ce: 0.0263961348682642  (0.03157372555061423)
     | > loss_mel_ce: 3.8188891410827637  (nan)
     | > loss: 3.845285177230835  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.168  (0.19549799153995018)
     | > loader_time: 0.023  (0.02296475430858126)


   --> TIME: 2025-05-17 17:34:50 -- STEP: 5614/6836 -- GLOBAL_STEP: 12450
     | > loss_text_ce: 0.027511950582265854  (0.03156644743371195)
     | > loss_mel_ce: nan  (nan)
     | > loss: nan  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1364  (0.1954072985650806)
     | > loader_time: 0.0088  (0.022863516104276553)


   --> TIME: 2025-05-17 17:35:12 -- STEP: 5664/6836 -- GLOBAL_STEP: 12500
     | > loss_text_ce: 0.028263188898563385  (0.0315596912763907)
     | > loss_mel_ce: 2.2048535346984863  (nan)
     | > loss: 2.233116626739502  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2562  (0.19542899984592757)
     | > loader_time: 0.0104  (0.022769431273142498)


   --> TIME: 2025-05-17 17:35:34 -- STEP: 5714/6836 -- GLOBAL_STEP: 12550
     | > loss_text_ce: 0.03268459811806679  (0.031553250214943596)
     | > loss_mel_ce: 3.6570427417755127  (nan)
     | > loss: 3.689727306365967  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2821  (0.19533402163706154)
     | > loader_time: 0.0078  (0.022654975048929066)


   --> TIME: 2025-05-17 17:35:56 -- STEP: 5764/6836 -- GLOBAL_STEP: 12600
     | > loss_text_ce: 0.032020412385463715  (0.03154322261987336)
     | > loss_mel_ce: 3.0621867179870605  (nan)
     | > loss: 3.0942070484161377  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1764  (0.19528035411066996)
     | > loader_time: 0.0102  (0.022568313261438457)


   --> TIME: 2025-05-17 17:36:19 -- STEP: 5814/6836 -- GLOBAL_STEP: 12650
     | > loss_text_ce: 0.030575046315789223  (0.03153449540402284)
     | > loss_mel_ce: 3.6442677974700928  (nan)
     | > loss: 3.6748428344726562  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1976  (0.1953591583190932)
     | > loader_time: 0.0106  (0.0224747739791214)


   --> TIME: 2025-05-17 17:36:42 -- STEP: 5864/6836 -- GLOBAL_STEP: 12700
     | > loss_text_ce: 0.028332587331533432  (0.03153752064901581)
     | > loss_mel_ce: 4.368755340576172  (nan)
     | > loss: 4.397088050842285  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1864  (0.19536031951357838)
     | > loader_time: 0.009  (0.022387342799409186)


   --> TIME: 2025-05-17 17:37:04 -- STEP: 5914/6836 -- GLOBAL_STEP: 12750
     | > loss_text_ce: 0.033463168889284134  (0.03153519498894234)
     | > loss_mel_ce: 3.351707696914673  (nan)
     | > loss: 3.3851709365844727  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1675  (0.19536776291908814)
     | > loader_time: 0.0092  (0.02228613580285112)


   --> TIME: 2025-05-17 17:37:27 -- STEP: 5964/6836 -- GLOBAL_STEP: 12800
     | > loss_text_ce: 0.03146502375602722  (0.031535737631851246)
     | > loss_mel_ce: 3.5781517028808594  (nan)
     | > loss: 3.609616756439209  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.196  (0.19529728750347836)
     | > loader_time: 0.0082  (0.022189872165720867)


   --> TIME: 2025-05-17 17:37:49 -- STEP: 6014/6836 -- GLOBAL_STEP: 12850
     | > loss_text_ce: 0.03215058892965317  (0.03153233740870236)
     | > loss_mel_ce: 3.9741268157958984  (nan)
     | > loss: 4.006277561187744  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1402  (0.19527050839891283)
     | > loader_time: 0.0086  (0.022104424299653043)


   --> TIME: 2025-05-17 17:38:11 -- STEP: 6064/6836 -- GLOBAL_STEP: 12900
     | > loss_text_ce: 0.02909340150654316  (0.03153066103417905)
     | > loss_mel_ce: 3.703676700592041  (nan)
     | > loss: 3.7327702045440674  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1982  (0.19524933185457855)
     | > loader_time: 0.0075  (0.021997674473986463)


   --> TIME: 2025-05-17 17:38:34 -- STEP: 6114/6836 -- GLOBAL_STEP: 12950
     | > loss_text_ce: 0.031871963292360306  (0.031527587900222726)
     | > loss_mel_ce: 3.5000953674316406  (nan)
     | > loss: 3.5319674015045166  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2859  (0.19526699913612627)
     | > loader_time: 0.0091  (0.021898309857696342)


   --> TIME: 2025-05-17 17:38:56 -- STEP: 6164/6836 -- GLOBAL_STEP: 13000
     | > loss_text_ce: 0.035684242844581604  (0.031532574535965745)
     | > loss_mel_ce: 3.7367122173309326  (nan)
     | > loss: 3.7723965644836426  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2186  (0.1952210101966807)
     | > loader_time: 0.0293  (0.021820146452676624)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

   --> TIME: 2025-05-17 17:39:18 -- STEP: 6214/6836 -- GLOBAL_STEP: 13050
     | > loss_text_ce: 0.026438167318701744  (0.03152960639100459)
     | > loss_mel_ce: 4.309606075286865  (nan)
     | > loss: 4.3360443115234375  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1292  (0.19519459337984038)
     | > loader_time: 0.0083  (0.02171901364321873)


   --> TIME: 2025-05-17 17:39:41 -- STEP: 6264/6836 -- GLOBAL_STEP: 13100
     | > loss_text_ce: 0.027834782376885414  (0.031527781280383194)
     | > loss_mel_ce: 3.215635061264038  (nan)
     | > loss: 3.2434699535369873  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1903  (0.1951432276807372)
     | > loader_time: 0.0083  (0.021632186526082942)


   --> TIME: 2025-05-17 17:40:03 -- STEP: 6314/6836 -- GLOBAL_STEP: 13150
     | > loss_text_ce: 0.03155740350484848  (0.03152632964807413)
     | > loss_mel_ce: 3.3670239448547363  (nan)
     | > loss: 3.3985812664031982  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1618  (0.19511199386428707)
     | > loader_time: 0.0114  (0.021540791730847508)


   --> TIME: 2025-05-17 17:40:25 -- STEP: 6364/6836 -- GLOBAL_STEP: 13200
     | > loss_text_ce: 0.03014920838177204  (0.03151916087465154)
     | > loss_mel_ce: 3.8842597007751465  (nan)
     | > loss: 3.9144089221954346  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1323  (0.19501134343000406)
     | > loader_time: 0.0085  (0.021468826354786256)


   --> TIME: 2025-05-17 17:40:47 -- STEP: 6414/6836 -- GLOBAL_STEP: 13250
     | > loss_text_ce: 0.03129298985004425  (0.03152559468064411)
     | > loss_mel_ce: 3.7863235473632812  (nan)
     | > loss: 3.8176164627075195  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2591  (0.19499435356408948)
     | > loader_time: 0.0193  (0.021390604980273672)


   --> TIME: 2025-05-17 17:41:11 -- STEP: 6464/6836 -- GLOBAL_STEP: 13300
     | > loss_text_ce: 0.03122786432504654  (0.031527597238747665)
     | > loss_mel_ce: 3.1139843463897705  (nan)
     | > loss: 3.145212173461914  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1773  (0.1951142559473466)
     | > loader_time: 0.0099  (0.021326341804596458)


   --> TIME: 2025-05-17 17:41:34 -- STEP: 6514/6836 -- GLOBAL_STEP: 13350
     | > loss_text_ce: 0.028275446966290474  (0.03152342903146695)
     | > loss_mel_ce: 3.4955408573150635  (nan)
     | > loss: 3.5238163471221924  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1457  (0.19519693093099277)
     | > loader_time: 0.009  (0.021256305375712613)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:41:57 -- STEP: 6564/6836 -- GLOBAL_STEP: 13400
     | > loss_text_ce: 0.03370913490653038  (0.031521546447537185)
     | > loss_mel_ce: 4.203556537628174  (nan)
     | > loss: 4.237265586853027  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2026  (0.19533449226149244)
     | > loader_time: 0.0193  (0.021178491154797988)


   --> TIME: 2025-05-17 17:42:20 -- STEP: 6614/6836 -- GLOBAL_STEP: 13450
     | > loss_text_ce: 0.03102218173444271  (0.031520737381834994)
     | > loss_mel_ce: 3.4084393978118896  (nan)
     | > loss: 3.4394614696502686  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2687  (0.1953633314610824)
     | > loader_time: 0.0091  (0.02109699642906962)


   --> TIME: 2025-05-17 17:42:43 -- STEP: 6664/6836 -- GLOBAL_STEP: 13500
     | > loss_text_ce: 0.03475164994597435  (0.031515707748205224)
     | > loss_mel_ce: 3.6298208236694336  (nan)
     | > loss: 3.6645724773406982  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.352  (0.1953877166611234)
     | > loader_time: 0.017  (0.021016029786376678)


   --> TIME: 2025-05-17 17:43:05 -- STEP: 6714/6836 -- GLOBAL_STEP: 13550
     | > loss_text_ce: 0.029930565506219864  (0.0315127199924072)
     | > loss_mel_ce: 3.512272357940674  (nan)
     | > loss: 3.542202949523926  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1852  (0.1953302885330535)
     | > loader_time: 0.0086  (0.020936317340156524)


   --> TIME: 2025-05-17 17:43:27 -- STEP: 6764/6836 -- GLOBAL_STEP: 13600
     | > loss_text_ce: 0.027185674756765366  (0.03150773026260616)
     | > loss_mel_ce: 3.4365692138671875  (nan)
     | > loss: 3.463754892349243  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1386  (0.19531946521338298)
     | > loader_time: 0.0092  (0.02087136579645519)


   --> TIME: 2025-05-17 17:43:49 -- STEP: 6814/6836 -- GLOBAL_STEP: 13650
     | > loss_text_ce: 0.03639132156968117  (0.03150374474649565)
     | > loss_mel_ce: 3.526709794998169  (nan)
     | > loss: 3.563101053237915  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1834  (0.1952802958221143)
     | > loader_time: 0.0229  (0.02080626588501747)

 | > Synthesizing test sentences.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.02077413351760786 (+0.00908111744582785)
     | > avg_step_time: 0.19527243915577383 (+0.0009882465451846179)
     | > avg_loss_text_ce: 0.0315031436229043 (-0.0014884809725636203)
     | > avg_loss_mel_ce: nan (+nan)
     | > avg_loss: nan (+nan)
     | > avg_grad_norm: 0.0 (+0.0)


 > EPOCH: 2/15
 --> /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000

 > TRAINING (2025-05-17 17:44:08)

   --> TIME: 2025-05-17 17:44:22 -- STEP: 28/6836 -- GLOBAL_STEP: 13700
     | > loss_text_ce: 0.024514738470315933  (0.030841696807848557)
     | > loss_mel_ce: 3.992169141769409  (3.736806878021785)
     | > loss: 4.016684055328369  (3.7676485862050737)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.143  (0.19170783247266496)
     | > loader_time: 0.0092  (0.011861034802028112)


   --> TIME: 2025-05-17 17:44:44 -- STEP: 78/6836 -- GLOBAL_STEP: 13750
     | > loss_text_ce: 0.032848041504621506  (0.03125400031701876)
     | > loss_mel_ce: 3.2351975440979004  (3.700965343377529)
     | > loss: 3.268045663833618  (3.7322193582852683)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2751  (0.1894713028883323)
     | > loader_time: 0.0109  (0.0112833273716462)


   --> TIME: 2025-05-17 17:45:08 -- STEP: 128/6836 -- GLOBAL_STEP: 13800
     | > loss_text_ce: 0.02820291742682457  (0.03128981226473114)
     | > loss_mel_ce: 3.194260358810425  (nan)
     | > loss: 3.222463369369507  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1192  (0.19536851160228252)
     | > loader_time: 0.0092  (0.01152041368186474)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:45:30 -- STEP: 178/6836 -- GLOBAL_STEP: 13850
     | > loss_text_ce: 0.03307893127202988  (0.03110338258818627)
     | > loss_mel_ce: 4.882915019989014  (nan)
     | > loss: 4.915994167327881  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.3172  (0.19359727388017642)
     | > loader_time: 0.0156  (0.011380233121721936)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.
[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:45:52 -- STEP: 228/6836 -- GLOBAL_STEP: 13900
     | > loss_text_ce: 0.029838744550943375  (0.030952267642868177)
     | > loss_mel_ce: 4.212335109710693  (nan)
     | > loss: 4.242173671722412  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.2313  (0.19312699426684468)
     | > loader_time: 0.0088  (0.011118639979446147)

[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

   --> TIME: 2025-05-17 17:46:15 -- STEP: 278/6836 -- GLOBAL_STEP: 13950
     | > loss_text_ce: 0.03068539872765541  (0.030978860943276662)
     | > loss_mel_ce: 4.001395225524902  (nan)
     | > loss: 4.03208065032959  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.1408  (0.19379614668784387)
     | > loader_time: 0.0082  (0.011049373544377393)


   --> TIME: 2025-05-17 17:46:38 -- STEP: 328/6836 -- GLOBAL_STEP: 14000
     | > loss_text_ce: 0.027471553534269333  (0.030987937128307604)
     | > loss_mel_ce: 3.651434898376465  (nan)
     | > loss: 3.6789064407348633  (nan)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06
     | > step_time: 0.271  (0.1938414559131717)
     | > loader_time: 0.0118  (0.01103677182662778)

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========
[!] Warning: The text length exceeds the character limit of 166 for language 'ar', this might cause truncated audio.

 > Keyboard interrupt detected.
 > Saving model before exiting...

 > CHECKPOINT : /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000/checkpoint_14035.pth

========Ignoring artifact: checkpoint /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000========

 ! Run is kept in /content/gdrive/MyDrive/models/finetuned_egtts_v2_dz-May-17-2025_03+59PM-0000000